"""PR #8 (v0.8) -- 50 NEW validated us-conlaw cards (301-350) under the
standing rule (CLAUDE.md sec 5.2). Topic mix per sec 5.2:
  Federalism (8), Fed Courts/Justiciability (6), State sovereignty (4),
  Sep of powers (8), 1A (7), EP/DP (6), Death penalty (3),
  4A/5A/6A (5), 8A (3) = 50.

Citation URL convention (PR #8): cite_scotus appends the keyword
"supremecourt.gov" so Google ranks the official PDF higher, since the
owner prefers that format.

Run from repo root:
    python scripts\\add_pr8_cards.py
"""
from __future__ import annotations

import json
from pathlib import Path
from urllib.parse import quote_plus

CARDS_PATH = Path(__file__).resolve().parent.parent / "src" / "main" / "resources" / "subjects" / "us-conlaw" / "cards.json"


def _google_url(query: str) -> str:
    return f"https://www.google.com/search?q={quote_plus(query)}"


def cite_scotus(label: str) -> dict:
    # PR #8: bias the search toward the official supremecourt.gov PDF.
    return {"label": label, "url": _google_url(label + " supremecourt.gov"), "type": "scotus"}


def cite_circuit(label: str) -> dict:
    return {"label": label, "url": _google_url(label), "type": "circuit"}


def cite_lr(label: str) -> dict:
    return {"label": label, "url": _google_url(label), "type": "law-review"}


def card(id_, stem, choices_with_correct, explanation, citations,
         tags="us-conlaw", grammar_point="", difficulty=3):
    return {
        "id": id_, "kind": "grammar", "level": "",
        "stem": stem, "grammar_point": grammar_point,
        "choices": [{"text": t, "is_correct": c} for t, c in choices_with_correct],
        "translation_zh_tw": "", "translation_zh_cn": "", "translation_en": "",
        "explanation": explanation, "difficulty": difficulty, "tags": tags,
        "source": "claude-authored-may-2026",
        "provenance": "human_curated",
        "attribution": "Claude PR #8 (validated bank). Awaiting expert review.",
        "citations": citations,
    }


NEW_CARDS = [
    # --- Federalism / Necessary & Proper / Contract Clause / etc. (8) ---
    card("usconlaw-301",
         "Congress enacts a federal statute authorizing civil commitment of mentally ill, sexually dangerous federal prisoners after their criminal sentences expire. Per Supreme Court doctrine, the statute is:",
         [("Beyond Congress's enumerated powers", False),
          ("Constitutional under the Necessary and Proper Clause as adapted to running the federal criminal system", True),
          ("Constitutional only under the Commerce Clause", False),
          ("Subject to political-question doctrine", False)],
         "United States v. Comstock (2010) upheld 18 U.S.C. § 4248 (civil commitment of sexually dangerous federal prisoners) under the NECESSARY AND PROPER CLAUSE. The Court applied a multi-factor test: (1) breadth of N&P power, (2) sound history of related federal involvement, (3) the statute's accommodation of state interests, (4) limited links between the statute and an enumerated power, and (5) narrow scope. Important modern N&P precedent.",
         [cite_scotus("United States v. Comstock, 560 U.S. 126 (2010)"),
          cite_scotus("McCulloch v. Maryland, 17 U.S. (4 Wheat.) 316 (1819)")],
         tags="us-conlaw,federalism,necessary-and-proper", grammar_point="Comstock / N&P"),
    card("usconlaw-302",
         "A state law substantially impairs the obligations of an existing private contract. Per Supreme Court doctrine, the law is:",
         [("Per se unconstitutional under the Contract Clause", False),
          ("Subject to a substantial-impairment / significant-and-legitimate-public-purpose / reasonable-and-appropriate analysis", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "Allied Structural Steel Co. v. Spannaus (1978) and Energy Reserves Group v. Kansas Power & Light (1983) supplied the modern Contract Clause framework: (1) does the law SUBSTANTIALLY IMPAIR the contractual relationship? (2) is the impairment justified by a SIGNIFICANT AND LEGITIMATE PUBLIC PURPOSE? (3) is it REASONABLE AND APPROPRIATE? Public contracts (state's own) face stricter review (US Trust v. NJ, 1977). Sveen v. Melin (2018) reaffirmed the framework.",
         [cite_scotus("Sveen v. Melin, 584 U.S. 811 (2018)"),
          cite_scotus("Allied Structural Steel Co. v. Spannaus, 438 U.S. 234 (1978)"),
          cite_scotus("United States Trust Co. v. New Jersey, 431 U.S. 1 (1977)")],
         tags="us-conlaw,federalism,contract-clause", grammar_point="Allied Structural / Sveen"),
    card("usconlaw-303",
         "A state statute imposes special burdens on out-of-state corporations conducting business within the state, in violation of the Privileges and Immunities Clause of Article IV. Per Supreme Court doctrine, the statute is:",
         [("Constitutional -- Art. IV P&I applies only to natural persons, not corporations", True),
          ("Unconstitutional under the P&I Clause", False),
          ("Subject to strict scrutiny", False),
          ("Constitutional only under the Commerce Clause", False)],
         "Article IV's PRIVILEGES AND IMMUNITIES CLAUSE protects only NATURAL PERSONS who are CITIZENS of other states, not corporations (Paul v. Virginia, 1869) and not aliens. Corporate discrimination by states is addressed instead under the DORMANT COMMERCE CLAUSE. Camden v. Camden Council on Building & Construction Trades (1984) applied Art. IV P&I to municipal contracting; United Building & Construction Trades Council v. Camden (1984) requires substantial-reason scrutiny.",
         [cite_scotus("Paul v. Virginia, 75 U.S. (8 Wall.) 168 (1869)"),
          cite_scotus("United Building & Construction Trades Council v. Camden, 465 U.S. 208 (1984)")],
         tags="us-conlaw,federalism,privileges-immunities", grammar_point="Art. IV P&I (corporations)"),
    card("usconlaw-304",
         "A state imposes a one-year residency requirement before a new resident can receive welfare benefits at the same level as long-term residents. Per Supreme Court doctrine, the requirement is:",
         [("Constitutional under the state's police power", False),
          ("Unconstitutional -- the constitutional right to travel includes the right to be treated equally upon establishing residency in a new state", True),
          ("Subject to rational basis review", False),
          ("Subject to political-question doctrine", False)],
         "Saenz v. Roe (1999) revived the Privileges or Immunities Clause of the 14A: a state may not discriminate against newly-arrived residents in benefits because the right to travel encompasses the right to be treated like other residents on arrival. Shapiro v. Thompson (1969) had earlier struck down welfare residency requirements under EP. Saenz is one of the few modern cases recognizing 14A P&I substantive content.",
         [cite_scotus("Saenz v. Roe, 526 U.S. 489 (1999)"),
          cite_scotus("Shapiro v. Thompson, 394 U.S. 618 (1969)")],
         tags="us-conlaw,federalism,right-to-travel", grammar_point="Saenz v. Roe"),
    card("usconlaw-305",
         "A state alleges that a federal statute, otherwise within Congress's enumerated powers, intrudes on the state's sovereignty so substantially as to be unconstitutional. Per Supreme Court doctrine, the alleged intrusion:",
         [("Is reviewed under traditional 11A doctrine", False),
          ("Generally is committed to the political process; structural state-sovereignty constraints on otherwise-valid Article I powers are limited (Garcia)", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "Garcia v. SAMTA (1985) held that the structural interests of states in the federal system are protected primarily by the political process (the Senate, electoral college, etc.), not by judicially-enforced restraints on otherwise-valid Article I legislation. New York v. United States (1992) and Printz v. United States (1997) created important EXCEPTIONS via anti-commandeering. South Dakota v. Dole (1987) cabined coercive Spending. But Garcia's general principle stands.",
         [cite_scotus("Garcia v. San Antonio Metropolitan Transit Authority, 469 U.S. 528 (1985)"),
          cite_scotus("New York v. United States, 505 U.S. 144 (1992)")],
         tags="us-conlaw,federalism,structural", grammar_point="Garcia structural protection"),
    card("usconlaw-306",
         "A state statute is challenged as preempted by an unwritten federal common-law rule of foreign affairs. Per Supreme Court doctrine, the doctrine controlling the analysis is:",
         [("Field preemption only", False),
          ("Foreign-affairs preemption / 'Zschernig' doctrine -- state laws that interfere with the federal foreign-affairs power may be preempted even without express federal regulation", True),
          ("Subject to political-question doctrine", False),
          ("Subject to rational basis review", False)],
         "Zschernig v. Miller (1968) struck down an Oregon probate statute that intruded on federal foreign-affairs authority by requiring state-court evaluation of foreign governments' fairness. American Insurance Ass'n v. Garamendi (2003) reaffirmed and applied this 'foreign-affairs preemption' to a California Holocaust Era Insurance Relief Act. Crosby v. National Foreign Trade Council (2000) used conflict-preemption analysis for a Massachusetts Burma sanctions statute.",
         [cite_scotus("Zschernig v. Miller, 389 U.S. 429 (1968)"),
          cite_scotus("American Insurance Ass'n v. Garamendi, 539 U.S. 396 (2003)"),
          cite_scotus("Crosby v. National Foreign Trade Council, 530 U.S. 363 (2000)")],
         tags="us-conlaw,federalism,foreign-affairs-preemption", grammar_point="Zschernig / Garamendi"),
    card("usconlaw-307",
         "Congress enacts a statute creating a federal cause of action for individual citizens to sue states for alleged violations of an international treaty. Per Supreme Court doctrine, the statute is:",
         [("Constitutional under the Treaty Power", False),
          ("Unconstitutional -- the Treaty Power does not authorize Congress to abrogate state sovereign immunity (Seminole Tribe principle)", True),
          ("Subject to political-question doctrine", False),
          ("Subject to strict scrutiny", False)],
         "Bond v. United States (2014) construed the Chemical Weapons Convention Implementation Act narrowly to avoid the federalism question, using the canon of CONSTITUTIONAL AVOIDANCE. The Court did not squarely address whether the Treaty Power could abrogate state sovereign immunity, but Seminole Tribe's logic (only 14A sec 5 abrogates) implies the Treaty Power cannot. Missouri v. Holland (1920) gave the Treaty Power expansive reach for ordinary federal-law authority but predates modern abrogation doctrine.",
         [cite_scotus("Bond v. United States, 572 U.S. 844 (2014)"),
          cite_scotus("Missouri v. Holland, 252 U.S. 416 (1920)"),
          cite_scotus("Seminole Tribe v. Florida, 517 U.S. 44 (1996)")],
         tags="us-conlaw,federalism,treaty-power", grammar_point="Bond / Missouri v. Holland"),
    card("usconlaw-308",
         "Congress, exercising the Spending Clause, conditions federal highway funds on a state's adoption of a 21-year-old minimum drinking age. Per Supreme Court doctrine, the condition is:",
         [("Beyond Congress's spending power", False),
          ("Constitutional under South Dakota v. Dole (5%-of-funds, related, unambiguous, no other constitutional violation, not unduly coercive)", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "South Dakota v. Dole (1987) upheld the conditional federal grant. Congress's spending power is constrained by FOUR requirements (1-4) plus a fifth (5): (1) general welfare, (2) unambiguous condition, (3) condition related to federal interest, (4) no other constitutional bar, (5) not unduly coercive. The 5% withholding here was small enough to be persuasive, not coercive. NFIB v. Sebelius (2012) sharpened the coercion limit (Medicaid expansion all-or-nothing crossed the line).",
         [cite_scotus("South Dakota v. Dole, 483 U.S. 203 (1987)")],
         tags="us-conlaw,federalism,spending-clause", grammar_point="South Dakota v. Dole"),
    # --- Federal Courts / Justiciability (6) -------------------
    card("usconlaw-309",
         "A federal-court diversity action involves a federal claim and supplemental state-law claims arising from the same case or controversy. Per the supplemental-jurisdiction statute (28 U.S.C. § 1367), the federal court:",
         [("Must dismiss the supplemental claims for lack of jurisdiction", False),
          ("Has supplemental jurisdiction over the related state-law claims (subject to certain exceptions for joinder by plaintiffs in diversity actions)", True),
          ("Must apply Younger abstention", False),
          ("Subject to political-question doctrine", False)],
         "28 U.S.C. § 1367 codifies SUPPLEMENTAL JURISDICTION over claims forming part of the same case or controversy as the basis of original jurisdiction. Exxon Mobil Corp. v. Allapattah Services (2005) held that § 1367 confers jurisdiction even over class members who individually fail to meet the amount-in-controversy requirement, IF at least one named plaintiff does. § 1367(c) gives discretion to decline supplemental jurisdiction in specified circumstances.",
         [cite_scotus("Exxon Mobil Corp. v. Allapattah Services, 545 U.S. 546 (2005)")],
         tags="us-conlaw,fed-courts,supplemental-jurisdiction", grammar_point="§ 1367 / Allapattah"),
    card("usconlaw-310",
         "A federal-question case is filed in state court. The defendant timely removes to federal court. Per Supreme Court doctrine, removal is proper if:",
         [("The case raises a substantial federal question on the face of the well-pleaded complaint", True),
          ("The defendant raises a federal-law defense", False),
          ("The case is brought under state law", False),
          ("The defendant is a federal officer (only)", False)],
         "The WELL-PLEADED COMPLAINT RULE (Louisville & Nashville R.R. v. Mottley, 1908) limits federal-question jurisdiction to cases where the federal question appears on the FACE OF THE PLAINTIFF'S COMPLAINT. Anticipated federal defenses do NOT trigger federal-question jurisdiction. Grable & Sons Metal Products v. Darue Engineering (2005) reaffirmed the doctrine while permitting jurisdiction for substantial embedded federal questions in state-law claims.",
         [cite_scotus("Louisville & Nashville R.R. v. Mottley, 211 U.S. 149 (1908)"),
          cite_scotus("Grable & Sons Metal Products v. Darue Engineering, 545 U.S. 308 (2005)")],
         tags="us-conlaw,fed-courts,federal-question", grammar_point="Mottley well-pleaded complaint"),
    card("usconlaw-311",
         "A plaintiff sues a federal officer for damages caused by an alleged constitutional violation. The officer asserts qualified immunity. Per Supreme Court doctrine, the officer is entitled to qualified immunity unless:",
         [("The right was generally known", False),
          ("The conduct violated CLEARLY ESTABLISHED statutory or constitutional rights of which a reasonable officer would have known", True),
          ("The plaintiff exhausted administrative remedies", False),
          ("The officer's actions were ultra vires", False)],
         "Harlow v. Fitzgerald (1982) replaced subjective-good-faith with the OBJECTIVE 'clearly established law' standard. Pearson v. Callahan (2009) gave courts discretion to decide either prong (clearly-established or constitutional violation) first. Saucier v. Katz (2001) had required deciding the constitutional question first; Pearson reversed. Recent cases (Mullenihan v. Luna, Kisela v. Hughes) have tightened 'clearly established' to require nearly identical precedent.",
         [cite_scotus("Harlow v. Fitzgerald, 457 U.S. 800 (1982)"),
          cite_scotus("Pearson v. Callahan, 555 U.S. 223 (2009)")],
         tags="us-conlaw,fed-courts,qualified-immunity", grammar_point="Harlow / Pearson"),
    card("usconlaw-312",
         "A plaintiff sues a federal official under Bivens for an alleged constitutional tort in a context not previously recognized. Per Supreme Court doctrine post-Ziglar / Hernandez, the suit is:",
         [("Permitted -- Bivens applies broadly to constitutional violations by federal officers", False),
          ("Disfavored -- expanding Bivens to new contexts is now disfavored absent special factors counseling extension", True),
          ("Subject to political-question doctrine", False),
          ("Subject to strict scrutiny", False)],
         "Ziglar v. Abbasi (2017), Hernandez v. Mesa (2020), and Egbert v. Boule (2022) progressively NARROWED Bivens v. Six Unknown Named Agents (1971). The Court has refused every Bivens extension since 1980. Egbert in particular suggested that ANY new context counsels caution, and most cases will fail. Bivens lives only for its three original contexts (4A search, 5A DP gender discrimination - Davis, 8A medical care - Carlson) and even there with caveats.",
         [cite_scotus("Egbert v. Boule, 596 U.S. 482 (2022)"),
          cite_scotus("Ziglar v. Abbasi, 582 U.S. 120 (2017)"),
          cite_scotus("Bivens v. Six Unknown Named Agents, 403 U.S. 388 (1971)")],
         tags="us-conlaw,fed-courts,bivens", grammar_point="Ziglar / Egbert (Bivens narrowing)"),
    card("usconlaw-313",
         "A federal court is asked to enjoin enforcement of an existing FEDERAL court judgment by a state court. Per Supreme Court doctrine, the court must consider:",
         [("Younger abstention", False),
          ("The Anti-Injunction Act (28 U.S.C. § 2283) -- federal courts may not enjoin state-court proceedings except as expressly authorized by Congress, in aid of jurisdiction, or to protect/effectuate judgments", True),
          ("Pullman abstention", False),
          ("Subject to political-question doctrine", False)],
         "The ANTI-INJUNCTION ACT (28 U.S.C. § 2283) prohibits federal courts from enjoining state-court proceedings except in three narrow circumstances: (1) expressly authorized by Congress, (2) where necessary in aid of jurisdiction, or (3) to PROTECT OR EFFECTUATE its judgments (the 'relitigation exception'). Atlantic Coast Line R.R. v. Brotherhood of Locomotive Engineers (1970) held the exceptions are exclusive and narrowly construed. Vendo v. Lektro-Vend (1977) narrowed the in-aid-of-jurisdiction exception further.",
         [cite_scotus("Atlantic Coast Line R.R. v. Brotherhood of Locomotive Engineers, 398 U.S. 281 (1970)"),
          cite_scotus("Mitchum v. Foster, 407 U.S. 225 (1972)")],
         tags="us-conlaw,fed-courts,anti-injunction-act", grammar_point="Anti-Injunction Act"),
    card("usconlaw-314",
         "A class action is filed in federal court under Rule 23 alleging mass-tort injuries. The class members' interests vary substantially. Per Supreme Court doctrine, the class:",
         [("Must be certified to permit aggregate adjudication", False),
          ("Cannot be certified under Rule 23(b)(3) absent showing predominance of common questions over individualized issues", True),
          ("Subject to Younger abstention", False),
          ("Subject to political-question doctrine", False)],
         "Wal-Mart Stores Inc. v. Dukes (2011) and Comcast Corp. v. Behrend (2013) substantially TIGHTENED Rule 23 class-certification requirements. Dukes held that the COMMONALITY requirement of Rule 23(a)(2) requires common contention capable of classwide resolution; mass-tort or sex-discrimination classes with individualized circumstances often fail. Comcast required predominance under Rule 23(b)(3) including damages methodology applicable classwide.",
         [cite_scotus("Wal-Mart Stores Inc. v. Dukes, 564 U.S. 338 (2011)"),
          cite_scotus("Comcast Corp. v. Behrend, 569 U.S. 27 (2013)")],
         tags="us-conlaw,fed-courts,class-action", grammar_point="Dukes / Comcast"),
    # --- State Sovereignty (4) ---------------------------------
    card("usconlaw-315",
         "Congress enacts the Trademark Remedy Clarification Act, abrogating state sovereign immunity for trademark infringement. Per Supreme Court doctrine, the abrogation is:",
         [("Valid under the Commerce Clause", False),
          ("Invalid -- Congress did not document a pattern of state trademark infringement warranting prophylactic legislation under 14A sec 5", True),
          ("Subject to strict scrutiny", False),
          ("Valid only with state consent", False)],
         "College Savings Bank v. Florida Prepaid Postsecondary Education Expense Board (1999) struck down Trademark Remedy Clarification Act abrogation. Florida Prepaid Postsecondary Educ. Expense Bd. v. College Savings Bank (1999) struck down the Patent Remedy Act's abrogation. The Court held that Congress's record of state intellectual-property infringement did NOT show a pattern of constitutional violations sufficient to justify prophylactic abrogation under Boerne. Allen v. Cooper (2020) extended this to the Copyright Remedy Clarification Act.",
         [cite_scotus("College Savings Bank v. Florida Prepaid Postsecondary Education Expense Board, 527 U.S. 666 (1999)"),
          cite_scotus("Allen v. Cooper, 589 U.S. 248 (2020)")],
         tags="us-conlaw,state-sovereignty,abrogation,ip", grammar_point="College Savings Bank / Allen v. Cooper"),
    card("usconlaw-316",
         "Plaintiffs sue a state agency for damages under the Patent Act, alleging state-government infringement of patented technology. Per Supreme Court doctrine, the suit is:",
         [("Permitted under federal supremacy", False),
          ("Barred -- the Patent Remedy Act's purported abrogation was unconstitutional under Boerne", True),
          ("Subject to strict scrutiny", False),
          ("Permitted only with state consent or constitutional violation", False)],
         "Florida Prepaid Postsecondary Educ. Expense Bd. v. College Savings Bank (1999) struck down the Patent Remedy Act's abrogation of state sovereign immunity. The Court held that property rights protected by 14A DP could in principle support sec 5 abrogation, but Congress's record did not show a pattern of state infringement WITHOUT adequate state remedies. Without adequate proof of constitutional violations, the abrogation was disproportionate under Boerne.",
         [cite_scotus("Florida Prepaid Postsecondary Educ. Expense Bd. v. College Savings Bank, 527 U.S. 627 (1999)")],
         tags="us-conlaw,state-sovereignty,abrogation,patents", grammar_point="Florida Prepaid"),
    card("usconlaw-317",
         "Congress enacts the Copyright Remedy Clarification Act abrogating state sovereign immunity for copyright infringement. Per Supreme Court doctrine, the abrogation is:",
         [("Valid under the Article I Copyright Clause", False),
          ("Invalid -- Congress did not document a pattern of constitutional violations by states (intentional infringement under 14A DP) sufficient to justify abrogation", True),
          ("Subject to strict scrutiny", False),
          ("Valid only with state consent", False)],
         "Allen v. Cooper (2020) struck down the Copyright Remedy Clarification Act's abrogation. Following Florida Prepaid (patents) and College Savings Bank (trademarks), the Court held that Congress's record of state copyright infringement did not establish a pattern of intentional, uncompensated 14A violations. The Article I Copyright Clause cannot itself abrogate state sovereign immunity (Seminole Tribe). Without adequate evidence of constitutional violations, sec 5 abrogation fails Boerne.",
         [cite_scotus("Allen v. Cooper, 589 U.S. 248 (2020)")],
         tags="us-conlaw,state-sovereignty,abrogation,copyright", grammar_point="Allen v. Cooper"),
    card("usconlaw-318",
         "Congress enacts a statute permitting interstate-pipeline companies to exercise federal eminent domain powers, including against state-owned land. Per Supreme Court doctrine, the statute is:",
         [("Unconstitutional as commandeering of state sovereignty", False),
          ("Constitutional -- delegation of federal eminent domain to private parties does not violate state sovereignty when authorized by Congress", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "PennEast Pipeline Co. v. New Jersey (2021) upheld the Natural Gas Act's grant of federal eminent-domain authority to private interstate-pipeline companies, including the power to condemn state-owned land. The Court held that since the Founding, states surrendered their sovereign immunity to suits by other sovereigns -- and the federal government's eminent-domain power, when delegated, may be exercised against the states. A narrow holding tied to a long history of federal eminent-domain delegation.",
         [cite_scotus("PennEast Pipeline Co. v. New Jersey, 594 U.S. 482 (2021)")],
         tags="us-conlaw,state-sovereignty,eminent-domain", grammar_point="PennEast v. New Jersey"),
    # --- Sep of Powers (8) -------------------------------------
    card("usconlaw-319",
         "Congress passes a statute permitting the Comptroller General (an officer removable by Congress) to make binding budgetary determinations. Per Supreme Court doctrine, the statute is:",
         [("Constitutional under Congress's spending power", False),
          ("Unconstitutional -- vesting executive functions in an officer removable by Congress violates separation of powers", True),
          ("Subject to political-question doctrine", False),
          ("Subject to strict scrutiny", False)],
         "Bowsher v. Synar (1986) struck down the Gramm-Rudman-Hollings Act's automatic deficit-reduction sequester. The Comptroller General was removable by Congress (joint resolution). Vesting EXECUTIVE FUNCTIONS in an officer subject to congressional removal violated separation of powers -- Congress cannot retain control over execution of laws after they are enacted. Compare INS v. Chadha (1983) on legislative-veto restraint on executive action.",
         [cite_scotus("Bowsher v. Synar, 478 U.S. 714 (1986)"),
          cite_scotus("INS v. Chadha, 462 U.S. 919 (1983)")],
         tags="us-conlaw,sep-of-powers,removal", grammar_point="Bowsher v. Synar"),
    card("usconlaw-320",
         "An executive-branch independent counsel is appointed pursuant to the Ethics in Government Act and is removable only for-cause by the AG. Per Supreme Court doctrine, the structure is:",
         [("Unconstitutional as inferior-officer aggrandizement", False),
          ("Constitutional -- the independent counsel is an INFERIOR OFFICER properly appointed and reasonably insulated from at-will removal (Morrison v. Olson)", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "Morrison v. Olson (1988) upheld the Ethics in Government Act's independent counsel. The Court held: (1) the counsel was an INFERIOR OFFICER (limited duties, jurisdiction, tenure) properly appointed under the Appointments Clause via court appointment; (2) for-cause removal was constitutional because it did not impede the President's ability to perform his constitutional duty. Justice Scalia's dissent forcefully predicted current unitary-executive jurisprudence (Seila, Free Enterprise Fund).",
         [cite_scotus("Morrison v. Olson, 487 U.S. 654 (1988)"),
          cite_scotus("Seila Law LLC v. CFPB, 591 U.S. 197 (2020)")],
         tags="us-conlaw,sep-of-powers,removal,inferior-officer", grammar_point="Morrison v. Olson"),
    card("usconlaw-321",
         "A federal statute purports to deprive courts of jurisdiction over claims arising from a particular subject. Per Supreme Court doctrine:",
         [("Congress's power to strip jurisdiction is plenary", False),
          ("Congress generally has broad authority over lower federal courts' jurisdiction (Sheldon v. Sill) and over Supreme Court appellate jurisdiction (Article III sec 2 cl. 2), but cannot use jurisdiction-stripping as a means to dictate a constitutionally-impermissible result (US v. Klein)", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "Article III sec 1 vests Congress with power to create lower federal courts; sec 2 cl. 2 grants Congress power over Supreme Court APPELLATE jurisdiction (with EXCEPTIONS). Sheldon v. Sill (1850) confirmed broad lower-court jurisdiction control; Ex parte McCardle (1869) upheld jurisdiction-stripping mid-case. United States v. Klein (1872) established a LIMIT: Congress may not use jurisdiction-stripping to direct a particular constitutionally-impermissible outcome (e.g., requiring courts to ignore presidential pardons).",
         [cite_scotus("Ex parte McCardle, 74 U.S. (7 Wall.) 506 (1869)"),
          cite_scotus("United States v. Klein, 80 U.S. (13 Wall.) 128 (1872)")],
         tags="us-conlaw,sep-of-powers,jurisdiction-stripping", grammar_point="Klein / McCardle"),
    card("usconlaw-322",
         "The President signs a treaty negotiated with a foreign sovereign. Per the Constitution, the treaty becomes binding US law:",
         [("Upon presidential signature alone", False),
          ("Only after Senate advice and consent by 2/3 supermajority (Art. II sec 2 cl. 2)", True),
          ("Upon publication", False),
          ("Upon House concurrence by simple majority", False)],
         "Article II sec 2 cl. 2 (the TREATY CLAUSE) requires the President to negotiate treaties but conditions their domestic legal effect on Senate ADVICE AND CONSENT by TWO-THIRDS supermajority. Congressional-executive agreements (Bricker debates) avoid the 2/3 requirement by using ordinary bicameral majorities. Medellin v. Texas (2008) held that treaties may be SELF-EXECUTING (directly enforceable) or NON-SELF-EXECUTING (requiring implementing legislation), depending on textual indications and historical practice.",
         [cite_scotus("Medellin v. Texas, 552 U.S. 491 (2008)")],
         tags="us-conlaw,sep-of-powers,treaty-power", grammar_point="Treaty Clause / Medellin"),
    card("usconlaw-323",
         "The President invokes inherent constitutional authority to enter into a sole-executive agreement with a foreign sovereign without Senate consent. Per Supreme Court doctrine, the agreement:",
         [("Has no domestic legal effect", False),
          ("May have legal effect within the President's independent constitutional authority (e.g., recognition, settlement of foreign claims)", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "United States v. Belmont (1937) and United States v. Pink (1942) upheld sole-executive agreements settling claims following the Litvinov Assignment recognizing the Soviet Union. Dames & Moore v. Regan (1981) upheld President Carter's executive agreement settling Iranian asset claims, finding congressional acquiescence in the long history of similar agreements. The President's recognition power (Zivotofsky II) is exclusive and may support sole-executive agreements in that domain.",
         [cite_scotus("Dames & Moore v. Regan, 453 U.S. 654 (1981)"),
          cite_scotus("United States v. Belmont, 301 U.S. 324 (1937)")],
         tags="us-conlaw,sep-of-powers,executive-agreement", grammar_point="Dames & Moore / Belmont"),
    card("usconlaw-324",
         "The President orders detention of a US citizen captured on foreign soil and designated an enemy combatant. The detainee challenges his detention via habeas. Per Supreme Court doctrine:",
         [("The detention is per se beyond judicial review", False),
          ("The detainee is entitled to fundamental due process: notice of factual basis and a fair opportunity to rebut the government's assertions before a neutral decisionmaker", True),
          ("Subject to political-question doctrine", False),
          ("Subject to rational basis review", False)],
         "Hamdi v. Rumsfeld (2004) (plurality) held that a US-citizen enemy combatant must receive fundamental DUE PROCESS in detention review: notice of the factual basis, opportunity to rebut before a neutral decisionmaker. The plurality construed the AUMF as authorizing detention but recognized continuing judicial role. Boumediene v. Bush (2008) extended habeas to non-citizen Guantanamo detainees, struck down DTA's habeas-substitute, holding the writ may not be suspended by inadequate substitution.",
         [cite_scotus("Hamdi v. Rumsfeld, 542 U.S. 507 (2004)"),
          cite_scotus("Boumediene v. Bush, 553 U.S. 723 (2008)")],
         tags="us-conlaw,sep-of-powers,habeas,war-on-terror", grammar_point="Hamdi / Boumediene"),
    card("usconlaw-325",
         "The President invokes wartime authority to establish military commissions to try suspected terrorists, without congressional authorization for the procedures. Per Supreme Court doctrine, the commissions are:",
         [("Constitutional under Commander-in-Chief power", False),
          ("Unconstitutional -- the commissions' procedures lacked authorization in the AUMF, UCMJ, or Geneva Conventions (Hamdan v. Rumsfeld)", True),
          ("Subject to political-question doctrine", False),
          ("Subject to strict scrutiny", False)],
         "Hamdan v. Rumsfeld (2006) struck down President Bush's military commissions as exceeding statutory and treaty authorization. The Court held the procedures violated the UCMJ and Common Article 3 of the Geneva Conventions. Following Hamdan, Congress passed the Military Commissions Act of 2006 providing authorization (later modified after Boumediene). The decision is a major Youngstown-step-3 holding -- presidential action against congressional/treaty constraints fails.",
         [cite_scotus("Hamdan v. Rumsfeld, 548 U.S. 557 (2006)"),
          cite_scotus("Boumediene v. Bush, 553 U.S. 723 (2008)")],
         tags="us-conlaw,sep-of-powers,war-powers", grammar_point="Hamdan v. Rumsfeld"),
    card("usconlaw-326",
         "Congress enacts a statute requiring agency rules of major economic and political significance to be approved by joint resolution before taking effect. Per Supreme Court doctrine, the statute is:",
         [("Constitutional as congressional oversight", False),
          ("Unconstitutional -- a one-house veto provision violates bicameralism and presentment, INS v. Chadha", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "INS v. Chadha (1983), if applied here, would invalidate any provision allowing congressional reversal of agency action OUTSIDE the bicameralism-and-presentment process. The Congressional Review Act (CRA), enacted post-Chadha, properly uses BICAMERAL JOINT RESOLUTION subject to presidential signature/veto -- avoiding Chadha. So the question turns on whether the new statute is structured as bicameral resolution + presentment (constitutional CRA-style) or as a one-house/two-house veto (unconstitutional Chadha-violation).",
         [cite_scotus("INS v. Chadha, 462 U.S. 919 (1983)")],
         tags="us-conlaw,sep-of-powers,legislative-veto", grammar_point="Chadha / CRA"),
    # --- 1A (7) -----------------------------------------------
    card("usconlaw-327",
         "A church group pickets a soldier's funeral with offensive signs about national policy. Per Supreme Court doctrine, the group's speech is:",
         [("Subject to civil liability for intentional infliction of emotional distress", False),
          ("Protected -- speech on matters of public concern, on public property, in compliance with public-protest regulations, cannot give rise to tort liability under the 1A", True),
          ("Subject to strict scrutiny", False),
          ("Subject to rational basis review", False)],
         "Snyder v. Phelps (2011) held the Westboro Baptist Church's funeral picketing protected by the 1A from IIED tort liability. The speech addressed matters of PUBLIC CONCERN (national policy, military, religious topics), occurred on PUBLIC PROPERTY at a permitted distance, and complied with state regulations. The Court emphasized that 'speech on public issues occupies the highest rung of the hierarchy of First Amendment values.'",
         [cite_scotus("Snyder v. Phelps, 562 U.S. 443 (2011)")],
         tags="us-conlaw,first-amendment,public-concern", grammar_point="Snyder v. Phelps"),
    card("usconlaw-328",
         "Congress enacts the Stolen Valor Act criminalizing knowing falsehoods about having received military decorations. Per Supreme Court doctrine, the Act is most likely:",
         [("Constitutional under the false-speech exception", False),
          ("Unconstitutional -- false statements as a category are NOT outside 1A protection; the Act fails strict scrutiny", True),
          ("Subject to rational basis review", False),
          ("Subject to political-question doctrine", False)],
         "United States v. Alvarez (2012) struck down the Stolen Valor Act of 2005. The plurality and concurrence rejected the government's argument that false statements categorically fall outside 1A protection -- they are protected absent specific harm contexts (defamation, perjury, fraud, false statements to government officials). The Act was content-based and failed strict scrutiny; less-restrictive means (counter-speech, narrowly drawn fraud statutes) were available.",
         [cite_scotus("United States v. Alvarez, 567 U.S. 709 (2012)")],
         tags="us-conlaw,first-amendment,false-speech", grammar_point="US v. Alvarez"),
    card("usconlaw-329",
         "A federal statute criminalizes the creation, sale, or possession of depictions of animal cruelty. Per Supreme Court doctrine, the statute is:",
         [("Constitutional as part of the obscenity exception", False),
          ("Unconstitutional -- the Court refuses to recognize new categorical exclusions from the 1A based on a categorical balancing test", True),
          ("Subject to rational basis review", False),
          ("Subject to political-question doctrine", False)],
         "United States v. Stevens (2010) struck down 18 U.S.C. § 48 (depictions of animal cruelty). The Court rejected the government's argument that the Court should recognize new categorical 1A exclusions through a categorical balancing test. The categories of unprotected speech (fighting words, obscenity, true threats, child pornography, incitement) are HISTORICAL AND TRADITIONAL, not the product of judicial balancing. The statute was overbroad.",
         [cite_scotus("United States v. Stevens, 559 U.S. 460 (2010)")],
         tags="us-conlaw,first-amendment,categorical-exclusions", grammar_point="US v. Stevens"),
    card("usconlaw-330",
         "A city accepts a Ten Commandments monument from a private donor in a public park, displays it permanently, and rejects requests from other donors to display competing monuments. Per Supreme Court doctrine, the city's permanent display is:",
         [("Government endorsement of religion", False),
          ("Government speech, not subject to forum-analysis; the city may select messages without 1A scrutiny", True),
          ("A traditional public forum", False),
          ("Subject to strict scrutiny", False)],
         "Pleasant Grove City v. Summum (2009) classified permanent monuments in public parks as GOVERNMENT SPEECH. The doctrine: when the government itself speaks (or its chosen monuments display its message), 1A speech-clause forum analysis does NOT apply. The city was free to accept some monuments and reject others without viewpoint-neutrality requirements. Walker v. Sons of Confederate Veterans (2015) extended government-speech doctrine to specialty license plates (controversially).",
         [cite_scotus("Pleasant Grove City v. Summum, 555 U.S. 460 (2009)"),
          cite_scotus("Walker v. Texas Division Sons of Confederate Veterans, 576 U.S. 200 (2015)")],
         tags="us-conlaw,first-amendment,government-speech", grammar_point="Pleasant Grove / Walker"),
    card("usconlaw-331",
         "A government employee is fired for speech made during the course of his official duties on a matter related to his official responsibilities. Per Supreme Court doctrine, the firing is:",
         [("Per se unconstitutional", False),
          ("Constitutional -- statements made by public employees pursuant to their OFFICIAL DUTIES are NOT protected by the 1A from employer discipline", True),
          ("Subject to Pickering-Connick balancing", False),
          ("Subject to strict scrutiny", False)],
         "Garcetti v. Ceballos (2006) held that public employees speaking PURSUANT TO THEIR OFFICIAL DUTIES are not speaking as citizens for 1A purposes; the 1A does not insulate them from employer discipline for that speech. Pickering v. Board of Education (1968) and Connick v. Myers (1983) protect employees speaking AS CITIZENS on MATTERS OF PUBLIC CONCERN, subject to balancing of employer interests. Lane v. Franks (2014) clarified that subpoenaed truthful testimony about job activities IS protected.",
         [cite_scotus("Garcetti v. Ceballos, 547 U.S. 410 (2006)"),
          cite_scotus("Pickering v. Board of Education, 391 U.S. 563 (1968)"),
          cite_scotus("Lane v. Franks, 573 U.S. 228 (2014)")],
         tags="us-conlaw,first-amendment,employee-speech", grammar_point="Garcetti / Pickering"),
    card("usconlaw-332",
         "A government licensing scheme grants a public official unbridled discretion to deny permits for parades or speakers in public places. Per Supreme Court doctrine, the scheme is:",
         [("Constitutional under intermediate scrutiny", False),
          ("Unconstitutional as a prior restraint -- licensing schemes for speech in public fora must contain narrow, objective, and definite standards", True),
          ("Subject to rational basis review", False),
          ("Subject to political-question doctrine", False)],
         "Forsyth County v. Nationalist Movement (1992) and Lakewood v. Plain Dealer Publishing Co. (1988) held that licensing schemes for speech in traditional public fora must contain NARROW, OBJECTIVE, AND DEFINITE STANDARDS. Unbridled official discretion creates a prior restraint that risks viewpoint discrimination. Cox v. New Hampshire (1941) had upheld neutral time/place/manner permitting if procedurally fair.",
         [cite_scotus("Forsyth County v. Nationalist Movement, 505 U.S. 123 (1992)"),
          cite_scotus("Lakewood v. Plain Dealer Publishing Co., 486 U.S. 750 (1988)")],
         tags="us-conlaw,first-amendment,prior-restraint", grammar_point="Forsyth / Lakewood"),
    card("usconlaw-333",
         "A federal statute regulates 'true threats' against the President, requiring proof that the speaker subjectively intended to communicate a threat. Per Supreme Court doctrine, the statute's scienter requirement is:",
         [("Excessive -- objective intent suffices", False),
          ("Required -- the 1A's true-threats exception now requires proof of SUBJECTIVE awareness of the threatening nature, at least to a recklessness standard", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "Counterman v. Colorado (2023) clarified the SCIENTER requirement for true-threats prosecutions: the prosecution must show the speaker had a SUBJECTIVE understanding of the threatening nature of the statements, AT LEAST to a RECKLESSNESS standard. Pure objective tests (would a reasonable person feel threatened) are insufficient under the 1A. Builds on Virginia v. Black (2003)'s definition of true threats and Elonis v. United States (2015)'s narrowing.",
         [cite_scotus("Counterman v. Colorado, 600 U.S. 66 (2023)"),
          cite_scotus("Virginia v. Black, 538 U.S. 343 (2003)")],
         tags="us-conlaw,first-amendment,true-threats", grammar_point="Counterman v. Colorado"),
    # --- EP/DP (6) ---------------------------------------------
    card("usconlaw-334",
         "A facially neutral local ordinance regulating laundries is enforced almost exclusively against Chinese-owned laundries. Per Supreme Court doctrine, the enforcement is:",
         [("Constitutional under the state's police power", False),
          ("Unconstitutional under the 14A EP Clause -- discriminatory enforcement of a facially-neutral law is itself an EP violation", True),
          ("Subject to rational basis review", False),
          ("Constitutional if facially valid", False)],
         "Yick Wo v. Hopkins (1886) struck down San Francisco's discriminatory enforcement of an ordinance against Chinese laundries. Even a facially-neutral law is unconstitutional if administered with an UNEQUAL HAND and UNJUST EYE. Foundational equal-protection case for AS-APPLIED challenges. Subsequent doctrine (Washington v. Davis, 1976) tightened proof of discriminatory PURPOSE for facially-neutral laws -- but Yick Wo's overt enforcement disparity remains compelling.",
         [cite_scotus("Yick Wo v. Hopkins, 118 U.S. 356 (1886)"),
          cite_scotus("Washington v. Davis, 426 U.S. 229 (1976)")],
         tags="us-conlaw,equal-protection,discriminatory-enforcement", grammar_point="Yick Wo v. Hopkins"),
    card("usconlaw-335",
         "A state criminalizes interracial marriage. Per Supreme Court doctrine, the statute is:",
         [("Constitutional under the state's marriage power", False),
          ("Unconstitutional -- racial classifications subject to strict scrutiny; marriage is also a fundamental right under DP", True),
          ("Subject to rational basis review", False),
          ("Subject to political-question doctrine", False)],
         "Loving v. Virginia (1967) struck down Virginia's anti-miscegenation statute. The Court held: (1) racial classifications under the EP Clause are subject to STRICT SCRUTINY, and the statute could not survive (white supremacy is not a compelling interest); (2) marriage is a fundamental right under SUBSTANTIVE DUE PROCESS, and the racial restriction violated that liberty as well. Loving anchored later marriage cases (Zablocki, Turner v. Safley, Obergefell).",
         [cite_scotus("Loving v. Virginia, 388 U.S. 1 (1967)")],
         tags="us-conlaw,equal-protection,race,marriage", grammar_point="Loving v. Virginia"),
    card("usconlaw-336",
         "A state amends its constitution to prohibit any state or local law that protects sexual orientation as a class. Per Supreme Court doctrine, the amendment is:",
         [("Constitutional as a state political-process choice", False),
          ("Unconstitutional under the EP Clause -- the amendment manifests a bare desire to harm a politically unpopular group", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "Romer v. Evans (1996) struck down Colorado's Amendment 2 prohibiting state and local protections against sexual-orientation discrimination. Even on rational-basis review, the amendment's breadth and singling-out of one group revealed an unconstitutional 'animus' -- a 'bare desire to harm a politically unpopular group' is not a legitimate government interest. Romer's animus doctrine became important for later sexual-orientation cases (Lawrence, Windsor, Obergefell).",
         [cite_scotus("Romer v. Evans, 517 U.S. 620 (1996)")],
         tags="us-conlaw,equal-protection,sexual-orientation,animus", grammar_point="Romer v. Evans"),
    card("usconlaw-337",
         "A city zoning ordinance excludes group homes for the developmentally disabled. Per Supreme Court doctrine, the exclusion receives:",
         [("Strict scrutiny -- disability is a quasi-suspect class", False),
          ("Rational-basis review with bite -- disability is not a suspect class but the exclusion still must rest on a legitimate interest, not on irrational fear or stereotype", True),
          ("Intermediate scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "City of Cleburne v. Cleburne Living Center (1985) declined to make disability a quasi-suspect class but struck down the zoning ordinance under 'rational basis with bite' / 'rational basis with teeth.' The Court found the asserted interests (negative attitudes of neighbors, congestion) impermissible because they rested on irrational fear and stereotype, not on legitimate concerns. Foundation for the rational-basis-with-bite doctrine recurring in Romer, Lawrence, Windsor.",
         [cite_scotus("City of Cleburne v. Cleburne Living Center, 473 U.S. 432 (1985)")],
         tags="us-conlaw,equal-protection,disability,rational-basis-with-bite", grammar_point="City of Cleburne"),
    card("usconlaw-338",
         "A federal statute regulates the activities of religious organizations applying for a public benefit, requiring secular use of funds. Per Supreme Court doctrine, the requirement is:",
         [("Required by the Establishment Clause", False),
          ("Constitutional if neutrally available, but strict scrutiny if it discriminates against religious applicants on the basis of religious status", True),
          ("Subject to political-question doctrine", False),
          ("Subject to rational basis review", False)],
         "Trinity Lutheran Church of Columbia v. Comer (2017), Espinoza v. Montana Dept. of Revenue (2020), and Carson v. Makin (2022) progressively held that EXCLUDING religious entities from neutral public benefits BECAUSE OF THEIR RELIGIOUS STATUS violates the Free Exercise Clause and triggers strict scrutiny. The decisions effectively restrict states' use of Blaine-amendment-style exclusions of religious schools/entities from neutrally-available benefits.",
         [cite_scotus("Trinity Lutheran Church of Columbia v. Comer, 582 U.S. 449 (2017)"),
          cite_scotus("Espinoza v. Montana Dept. of Revenue, 591 U.S. 464 (2020)"),
          cite_scotus("Carson v. Makin, 596 U.S. 767 (2022)")],
         tags="us-conlaw,first-amendment,free-exercise,benefits", grammar_point="Trinity Lutheran / Carson"),
    card("usconlaw-339",
         "A state statute criminalizes the medically-induced termination of a viable pregnancy without exception for the life or health of the pregnant woman. Per Supreme Court doctrine post-Dobbs:",
         [("The statute is unconstitutional under Roe/Casey", False),
          ("The statute is constitutional in most applications -- Dobbs returned abortion regulation to the political process; rational-basis review applies. Maternal-life exceptions, however, raise serious DP / Equal Protection questions", True),
          ("Subject to undue-burden analysis", False),
          ("Subject to strict scrutiny", False)],
         "Dobbs v. Jackson Women's Health Organization (2022) overruled Roe v. Wade (1973) and Planned Parenthood v. Casey (1992). State abortion regulations now receive rational-basis review. However, narrow life-of-the-mother exceptions remain a serious unresolved question under SUBSTANTIVE DUE PROCESS (the right not to die from forced gestation) and EQUAL PROTECTION (sex discrimination). State courts have varied on enforcement of total bans without medical-emergency exceptions.",
         [cite_scotus("Dobbs v. Jackson Women's Health Organization, 597 U.S. 215 (2022)"),
          cite_scotus("Planned Parenthood v. Casey, 505 U.S. 833 (1992)")],
         tags="us-conlaw,due-process,abortion,post-dobbs", grammar_point="Dobbs (post-overruling)"),
    # --- Death penalty (3) -------------------------------------
    card("usconlaw-340",
         "A state imposes the death penalty for an adult conviction of raping a woman. Per Supreme Court doctrine, the sentence is:",
         [("Constitutional with proper aggravators", False),
          ("Unconstitutional -- the 8A categorically prohibits the death penalty for the rape of an adult woman", True),
          ("Subject to political-question doctrine", False),
          ("Subject to rational basis review", False)],
         "Coker v. Georgia (1977) categorically barred the death penalty for the rape of an adult woman as 'grossly disproportionate' under the 8A. Kennedy v. Louisiana (2008) extended this to rape of a child where the victim survived (the death penalty is reserved for crimes that 'take' the life of the victim or are crimes against the state -- treason, espionage). Limits on capital crimes for non-homicide offenses remain firm post-Kennedy.",
         [cite_scotus("Coker v. Georgia, 433 U.S. 584 (1977)"),
          cite_scotus("Kennedy v. Louisiana, 554 U.S. 407 (2008)")],
         tags="us-conlaw,eighth-amendment,death-penalty,proportionality", grammar_point="Coker / Kennedy"),
    card("usconlaw-341",
         "A defendant participates as an accomplice in an armed robbery during which his co-felon kills the victim. The defendant did not personally kill, intend to kill, or contemplate that life would be taken. Per Supreme Court doctrine, the death penalty is:",
         [("Constitutional under the felony-murder rule", False),
          ("Unconstitutional under Enmund v. Florida -- mere accomplice liability without major participation and reckless indifference to human life is insufficient", True),
          ("Subject to political-question doctrine", False),
          ("Subject to rational basis review", False)],
         "Enmund v. Florida (1982) held that the death penalty is disproportionate for a felony-murder accomplice who did not kill, attempt to kill, or intend that a killing occur. Tison v. Arizona (1987) modified Enmund: MAJOR PARTICIPATION in the felony combined with RECKLESS INDIFFERENCE TO HUMAN LIFE suffices for the death penalty under Enmund's test, even without an intent to kill.",
         [cite_scotus("Enmund v. Florida, 458 U.S. 782 (1982)"),
          cite_scotus("Tison v. Arizona, 481 U.S. 137 (1987)")],
         tags="us-conlaw,eighth-amendment,death-penalty,accomplice", grammar_point="Enmund / Tison"),
    card("usconlaw-342",
         "A state imposes the death penalty for a defendant who is intellectually disabled. Per Supreme Court doctrine, the sentence is:",
         [("Constitutional with proper aggravators", False),
          ("Unconstitutional -- execution of intellectually disabled persons is categorically barred under the 8A", True),
          ("Subject to political-question doctrine", False),
          ("Subject to individualized determination only", False)],
         "Atkins v. Virginia (2002) categorically barred the execution of intellectually disabled (then 'mentally retarded') persons under the 8A. The Court relied on a national consensus and on diminished culpability. Hall v. Florida (2014) struck down Florida's strict IQ-cutoff for determining intellectual disability, requiring consideration of the standard error of measurement. Moore v. Texas (2017) further restricted use of outdated medical standards.",
         [cite_scotus("Atkins v. Virginia, 536 U.S. 304 (2002)"),
          cite_scotus("Hall v. Florida, 572 U.S. 701 (2014)"),
          cite_scotus("Moore v. Texas, 581 U.S. 1 (2017)")],
         tags="us-conlaw,eighth-amendment,death-penalty,intellectual-disability", grammar_point="Atkins / Hall / Moore"),
    # --- 4A/5A/6A (5) ------------------------------------------
    card("usconlaw-343",
         "Police bring a drug-detection dog onto a homeowner's front porch and conduct a sniff. Per Supreme Court doctrine, the action:",
         [("Is not a search -- dog sniffs are non-intrusive", False),
          ("Is a 4A search -- bringing a trained drug-detection dog onto the curtilage to investigate the home is a physical-trespass search requiring a warrant", True),
          ("Subject to good-faith exception", False),
          ("Subject to rational basis review", False)],
         "Florida v. Jardines (2013) held that a drug-dog sniff at the front porch of a home is a 4A SEARCH under the trespass theory revived in United States v. Jones (2012). The CURTILAGE is part of the home for 4A purposes; using a trained drug dog as an instrument to gather information from within the curtilage exceeds the implicit license that visitors enjoy to approach a front door.",
         [cite_scotus("Florida v. Jardines, 569 U.S. 1 (2013)"),
          cite_scotus("United States v. Jones, 565 U.S. 400 (2012)")],
         tags="us-conlaw,fourth-amendment,curtilage,dog-sniff", grammar_point="Florida v. Jardines"),
    card("usconlaw-344",
         "Police, without a warrant, attach a GPS tracking device to a suspect's vehicle and monitor his movements for 28 days. Per Supreme Court doctrine, the action:",
         [("Is not a search -- public movements have no expectation of privacy", False),
          ("Is a 4A search under both the trespass theory (physical attachment to vehicle) and the privacy theory (long-term comprehensive surveillance)", True),
          ("Subject to good-faith exception", False),
          ("Subject to rational basis review", False)],
         "United States v. Jones (2012) revived the TRESPASS theory of 4A search: physical attachment of a GPS device to a vehicle to gather information IS a search regardless of privacy analysis. Justice Scalia's majority focused on trespass; Justice Sotomayor's concurrence and Justice Alito's concurrence emphasized that long-term comprehensive surveillance also raises distinct privacy concerns under Katz. Carpenter v. United States (2018) extended Jones's privacy reasoning to historical CSLI.",
         [cite_scotus("United States v. Jones, 565 U.S. 400 (2012)"),
          cite_scotus("Katz v. United States, 389 U.S. 347 (1967)")],
         tags="us-conlaw,fourth-amendment,gps", grammar_point="US v. Jones"),
    card("usconlaw-345",
         "Police, from a public street, use a thermal-imaging device to detect heat patterns inside a home indicating marijuana cultivation. Per Supreme Court doctrine, the use is:",
         [("Not a search -- the heat radiates outside the home", False),
          ("A 4A search -- using sense-enhancing technology not in general public use to gather information from the home's interior is a search", True),
          ("Subject to good-faith exception", False),
          ("Subject to rational basis review", False)],
         "Kyllo v. United States (2001) held that using a thermal-imaging device to detect heat patterns inside a home is a 4A SEARCH. The Court rejected a 'public use' or 'sense enhancement' carve-out: where the government uses technology NOT IN GENERAL PUBLIC USE to obtain information from the interior of the home that could not otherwise be obtained without physical intrusion, the surveillance is a search and presumptively unreasonable without a warrant.",
         [cite_scotus("Kyllo v. United States, 533 U.S. 27 (2001)")],
         tags="us-conlaw,fourth-amendment,thermal-imaging", grammar_point="Kyllo v. United States"),
    card("usconlaw-346",
         "Officers violate the knock-and-announce rule when executing a search warrant. The defendant moves to suppress evidence found during the search. Per Supreme Court doctrine, the motion:",
         [("Should be granted under the exclusionary rule", False),
          ("Should be denied -- knock-and-announce violations do not trigger exclusion (Hudson v. Michigan)", True),
          ("Subject to good-faith exception only", False),
          ("Subject to political-question doctrine", False)],
         "Hudson v. Michigan (2006) held that violations of the knock-and-announce rule do NOT trigger the exclusionary rule. The Court emphasized the disconnect between the interests protected by knock-and-announce (privacy, dignity, property protection) and the evidence found inside (which would have been found with proper announcement). Hudson signaled the Court's willingness to LIMIT the exclusionary rule's application -- a trend reinforced in Herring (2009), Davis (2011), and Strieff (2016).",
         [cite_scotus("Hudson v. Michigan, 547 U.S. 586 (2006)"),
          cite_scotus("Utah v. Strieff, 579 U.S. 232 (2016)")],
         tags="us-conlaw,fourth-amendment,exclusionary-rule", grammar_point="Hudson v. Michigan"),
    card("usconlaw-347",
         "After an unconstitutional stop, an officer discovers an outstanding arrest warrant on the suspect, then arrests him and finds drugs incident to arrest. Per Supreme Court doctrine, the drugs are:",
         [("Suppressed as fruit of the poisonous tree", False),
          ("Admissible -- the discovery of the valid warrant attenuated the connection between the unlawful stop and the discovery of evidence", True),
          ("Subject to good-faith exception only", False),
          ("Subject to political-question doctrine", False)],
         "Utah v. Strieff (2016) applied the ATTENUATION DOCTRINE to admit drugs found incident to a valid-warrant arrest, even though the initial stop was unconstitutional. The Court applied the Brown v. Illinois (1975) factors: (1) TEMPORAL PROXIMITY (close, against admission), (2) INTERVENING CIRCUMSTANCES (valid warrant, strong for admission), (3) PURPOSE/FLAGRANCY (no flagrant misconduct, against suppression). Justice Sotomayor's dissent powerfully criticized the doctrine's racial-justice implications.",
         [cite_scotus("Utah v. Strieff, 579 U.S. 232 (2016)"),
          cite_scotus("Brown v. Illinois, 422 U.S. 590 (1975)")],
         tags="us-conlaw,fourth-amendment,attenuation", grammar_point="Utah v. Strieff"),
    # --- 8A non-capital (3) ------------------------------------
    card("usconlaw-348",
         "California prison conditions, including overcrowding causing serious medical and mental-health failures, constitute an 8A violation. The federal court orders prisoner-population reduction to remedy the violation. Per Supreme Court doctrine, the order is:",
         [("Beyond federal-court authority", False),
          ("Constitutional under the Prison Litigation Reform Act and 8A (population-reduction can be a remedy where less-intrusive alternatives have failed)", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "Brown v. Plata (2011) upheld a federal three-judge court order requiring California to reduce its prison population by tens of thousands to remedy ongoing 8A violations from overcrowding-driven medical and mental-health failures. The Prison Litigation Reform Act allows population caps as a LAST RESORT remedy when narrower remedies have failed. Justice Kennedy's majority opinion described the conditions in graphic detail; Justice Scalia's dissent characterized the remedy as judicial overreach.",
         [cite_scotus("Brown v. Plata, 563 U.S. 493 (2011)")],
         tags="us-conlaw,eighth-amendment,prison,remedy", grammar_point="Brown v. Plata"),
    card("usconlaw-349",
         "A state prison places a prisoner in solitary confinement for an extended period without meaningful periodic review. The prisoner challenges the placement. Per Supreme Court doctrine, the placement may:",
         [("Per se violate the 8A", False),
          ("Trigger procedural-due-process claims (Wilkinson v. Austin) and potentially 8A claims if conditions impose an objectively serious deprivation with deliberate indifference", True),
          ("Subject to strict scrutiny", False),
          ("Be unreviewable under deference to prison administration", False)],
         "Wilkinson v. Austin (2005) held that placement in a 'supermax' facility imposes an ATYPICAL AND SIGNIFICANT HARDSHIP triggering procedural due-process protections. Modern litigation increasingly explores 8A claims for prolonged solitary confinement, citing developing scientific consensus on psychological harm. Apodaca v. Raemisch (2018, denial of cert with Sotomayor opinion respecting denial) and ongoing circuit-court development illustrate continued attention without final SCOTUS resolution.",
         [cite_scotus("Wilkinson v. Austin, 545 U.S. 209 (2005)")],
         tags="us-conlaw,eighth-amendment,solitary-confinement", grammar_point="Wilkinson v. Austin"),
    card("usconlaw-350",
         "A state takes private property for transfer to a private developer under an economic-development plan. Per Supreme Court doctrine, the taking is:",
         [("Unconstitutional -- economic development is not a public use", False),
          ("Constitutional -- 'public use' under the 5A includes 'public purpose' broadly defined to include economic development (Kelo v. New London)", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "Kelo v. City of New London (2005) upheld an economic-development taking against 5A 'public use' challenge. The Court read 'public use' as 'public PURPOSE' broadly defined to include economic-development plans. The decision was widely unpopular -- many states subsequently amended their constitutions or laws to BAR economic-development takings under state law. The 5A 'public use' floor remains low; just compensation must of course be paid (which Kelo does not displace).",
         [cite_scotus("Kelo v. City of New London, 545 U.S. 469 (2005)"),
          cite_scotus("Berman v. Parker, 348 U.S. 26 (1954)")],
         tags="us-conlaw,fifth-amendment,takings,public-use", grammar_point="Kelo v. New London"),
]


def main():
    data = json.loads(CARDS_PATH.read_text(encoding="utf-8"))
    cards = data["cards"]
    existing_ids = {c["id"] for c in cards}
    added = 0
    for card_dict in NEW_CARDS:
        if card_dict["id"] not in existing_ids:
            cards.append(card_dict)
            added += 1
    tmp = CARDS_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps({"cards": cards}, ensure_ascii=False, indent=2) + "\n",
                   encoding="utf-8")
    tmp.replace(CARDS_PATH)
    print(f"Added {added} new cards. Total cards now: {len(cards)}.")


if __name__ == "__main__":
    main()
