"""PR #6 (v0.6) — 50 NEW validated us-conlaw cards (201-250) under the
standing rule (CLAUDE.md §5.2). Topic mix per §5.2:
  Federalism (8), Federal Courts/Justiciability (6), State sovereignty (4),
  Sep of powers (8), 1A (7), EP/DP (6), Death penalty (3),
  4A/5A/6A (5), 8A (3) = 50.

Run from repo root:
    python scripts\\add_pr6_cards.py
"""
from __future__ import annotations

import json
from pathlib import Path
from urllib.parse import quote_plus

CARDS_PATH = Path(__file__).resolve().parent.parent / "src" / "main" / "resources" / "subjects" / "us-conlaw" / "cards.json"


def google_url(label: str) -> str:
    return f"https://www.google.com/search?q={quote_plus(label)}"


def cite_scotus(label: str) -> dict:
    return {"label": label, "url": google_url(label), "type": "scotus"}


def cite_circuit(label: str) -> dict:
    return {"label": label, "url": google_url(label), "type": "circuit"}


def cite_lr(label: str) -> dict:
    return {"label": label, "url": google_url(label), "type": "law-review"}


def card(id_, stem, choices_with_correct, explanation, citations,
         tags="us-conlaw", grammar_point="", difficulty=3):
    return {
        "id": id_, "kind": "grammar", "level": "",
        "stem": stem, "grammar_point": grammar_point,
        "choices": [{"text": t, "is_correct": c} for t, c in choices_with_correct],
        "translation_zh_tw": "", "translation_zh_cn": "", "translation_en": "",
        "explanation": explanation, "difficulty": difficulty, "tags": tags,
        "source": "claude-authored-may-2026",
        "provenance": "human_curated",
        "attribution": "Claude PR #6 (validated bank). Awaiting expert review.",
        "citations": citations,
    }


NEW_CARDS = [
    # ─── Federalism (8) ────────────────────────────────────────
    card("usconlaw-201",
         "Congress enacts a statute requiring state legislatures to either pass federal-prescribed regulations OR have the federal government regulate directly. Per Supreme Court doctrine, the statute is most likely:",
         [("Constitutional under the Commerce Clause", False),
          ("Unconstitutional as commandeering of state legislative process", True),
          ("Constitutional under the Necessary and Proper Clause", False),
          ("Constitutional under the Spending Clause", False)],
         "New York v. United States (1992) struck down the Low-Level Radioactive Waste Policy Act's 'take title' provision as unconstitutional commandeering of state legislatures. Congress may not compel states to enact or enforce a federal regulatory program. Murphy v. NCAA (2018) reaffirmed and extended the anti-commandeering principle to prohibitions on state action.",
         [cite_scotus("New York v. United States, 505 U.S. 144 (1992)"),
          cite_scotus("Murphy v. NCAA, 584 U.S. 453 (2018)")],
         tags="us-conlaw,federalism,anti-commandeering", grammar_point="New York v. US (commandeering)"),
    card("usconlaw-202",
         "Congress enacts a federal statute requiring local sheriffs to perform background checks on handgun purchasers. Per Supreme Court doctrine, the statute is:",
         [("Constitutional under the Commerce Clause", False),
          ("Unconstitutional as commandeering of state executive officials", True),
          ("Constitutional under the Necessary and Proper Clause", False),
          ("Constitutional under the 14A § 5 enforcement power", False)],
         "Printz v. United States (1997) struck down the Brady Act's interim provisions requiring local CLEOs to conduct background checks. Justice Scalia: 'the Federal Government may not compel the States to enact or administer a federal regulatory program.' Anti-commandeering applies to state EXECUTIVE officials as well as legislatures.",
         [cite_scotus("Printz v. United States, 521 U.S. 898 (1997)"),
          cite_scotus("New York v. United States, 505 U.S. 144 (1992)")],
         tags="us-conlaw,federalism,anti-commandeering", grammar_point="Printz v. United States"),
    card("usconlaw-203",
         "Congress enacts a federal statute prohibiting states from authorizing sports gambling. Per Supreme Court doctrine, the statute is most likely:",
         [("Constitutional as preemption", False),
          ("Unconstitutional as anti-commandeering — Congress cannot dictate what state law must be", True),
          ("Constitutional under the Commerce Clause", False),
          ("Constitutional under the Necessary and Proper Clause", False)],
         "Murphy v. NCAA (2018) struck down PASPA's prohibition on state authorization of sports betting. The Court held that the anti-commandeering doctrine prohibits Congress from issuing direct orders to state legislatures, including orders NOT to enact certain laws. Distinguish preemption (Congress regulates private actors directly, displacing state law) from commandeering (Congress conscripts states themselves).",
         [cite_scotus("Murphy v. NCAA, 584 U.S. 453 (2018)")],
         tags="us-conlaw,federalism,anti-commandeering", grammar_point="Murphy v. NCAA"),
    card("usconlaw-204",
         "Congress, acting under the Commerce Clause, regulates wholly intrastate, non-economic activity (e.g., gun possession in school zones). Per Supreme Court doctrine, the regulation is:",
         [("Constitutional — Congress's commerce power is plenary", False),
          ("Unconstitutional — non-economic intrastate activity falls outside the substantial-effects test", True),
          ("Constitutional under the Necessary and Proper Clause", False),
          ("Constitutional under the aggregation principle", False)],
         "United States v. Lopez (1995) struck down the Gun-Free School Zones Act, marking the first Commerce Clause limit since the New Deal. Lopez (and Morrison, 2000, on VAWA) held that wholly NON-ECONOMIC activity cannot be regulated under the substantial-effects branch of the Commerce Clause. Aggregation (Wickard) applies only to economic activity (Raich).",
         [cite_scotus("United States v. Lopez, 514 U.S. 549 (1995)"),
          cite_scotus("United States v. Morrison, 529 U.S. 598 (2000)"),
          cite_scotus("Gonzales v. Raich, 545 U.S. 1 (2005)")],
         tags="us-conlaw,federalism,commerce-clause", grammar_point="Lopez/Morrison non-economic limit"),
    card("usconlaw-205",
         "Congress enacts the individual mandate of the ACA, requiring individuals to maintain minimum health coverage or pay a penalty. Per Supreme Court doctrine in NFIB v. Sebelius, the mandate is:",
         [("Constitutional under the Commerce Clause", False),
          ("Constitutional only as an exercise of the Taxing Power, not the Commerce Clause", True),
          ("Unconstitutional in its entirety", False),
          ("Constitutional under the Necessary and Proper Clause", False)],
         "NFIB v. Sebelius (2012) split the Court: a 5-Justice majority held the individual mandate exceeded the Commerce Clause (cannot compel inactivity into commerce) and the Necessary and Proper Clause, but a different 5-Justice majority (CJ Roberts + 4 liberals) saved it as a constitutional exercise of the Taxing Power, since the 'penalty' functioned as a tax.",
         [cite_scotus("NFIB v. Sebelius, 567 U.S. 519 (2012)"),
          cite_scotus("California v. Texas, 593 U.S. 659 (2021)")],
         tags="us-conlaw,federalism,commerce-clause,taxing-power", grammar_point="NFIB v. Sebelius"),
    card("usconlaw-206",
         "Congress conditions the receipt of federal Medicaid funds on a state's expansion of Medicaid eligibility, threatening to withdraw ALL existing Medicaid funding if the state declines. Per Supreme Court doctrine, the condition is:",
         [("Constitutional under the Spending Clause", False),
          ("Unconstitutional — coercion that crosses from pressure into compulsion", True),
          ("Constitutional under the Commerce Clause", False),
          ("Subject to rational basis review", False)],
         "NFIB v. Sebelius (2012) held the ACA's Medicaid expansion coercive when conditioned on loss of all preexisting Medicaid funds. South Dakota v. Dole (1987) had upheld conditional federal spending if the conditions were unambiguous, related to the federal interest, did not violate other constitutional provisions, and were not unduly coercive — Sebelius held that ALL-or-nothing leverage over a major existing program crossed Dole's coercion line.",
         [cite_scotus("NFIB v. Sebelius, 567 U.S. 519 (2012)"),
          cite_scotus("South Dakota v. Dole, 483 U.S. 203 (1987)")],
         tags="us-conlaw,federalism,spending-clause", grammar_point="Sebelius/Dole coercion"),
    card("usconlaw-207",
         "A state law is challenged as preempted by federal law. The federal statute does not expressly preempt the state law, but the federal regulatory scheme is comprehensive. Per Supreme Court doctrine, the state law may be preempted under:",
         [("Express preemption only", False),
          ("Field preemption — Congress occupied the entire regulatory field", True),
          ("Conflict preemption — direct conflict required", False),
          ("Anti-commandeering doctrine", False)],
         "Federal preemption (Supremacy Clause, Art. VI) takes three forms: (1) EXPRESS preemption (statute says so), (2) CONFLICT preemption (compliance with both is impossible OR state law obstructs federal purposes), (3) FIELD preemption (Congress so comprehensively regulated that there is no room for state law). Arizona v. United States (2012) applied field preemption to part of Arizona's immigration enforcement statute.",
         [cite_scotus("Arizona v. United States, 567 U.S. 387 (2012)"),
          cite_scotus("Geier v. American Honda Motor Co., 529 U.S. 861 (2000)")],
         tags="us-conlaw,federalism,preemption", grammar_point="Field preemption"),
    card("usconlaw-208",
         "A state law facially discriminates against out-of-state economic actors (e.g., a tax on out-of-state milk producers). Per Supreme Court doctrine, the law is:",
         [("Subject to rational basis review", False),
          ("Subject to virtually per se invalidity under the Dormant Commerce Clause", True),
          ("Constitutional under the state's police power", False),
          ("Subject to intermediate scrutiny", False)],
         "Philadelphia v. New Jersey (1978) and West Lynn Creamery v. Healy (1994) held that state laws facially discriminating against interstate commerce are virtually per se invalid under the Dormant Commerce Clause, absent a showing the discrimination serves a legitimate local purpose unattainable by nondiscriminatory means. Non-discriminatory laws receive Pike balancing instead.",
         [cite_scotus("Philadelphia v. New Jersey, 437 U.S. 617 (1978)"),
          cite_scotus("West Lynn Creamery v. Healy, 512 U.S. 186 (1994)"),
          cite_scotus("Pike v. Bruce Church, 397 U.S. 137 (1970)")],
         tags="us-conlaw,federalism,dormant-commerce-clause", grammar_point="Philadelphia v. NJ / Pike"),
    # ─── Federal Courts / Justiciability (6) ─────────────────────
    card("usconlaw-209",
         "A federal court is asked to enjoin a pending state criminal prosecution. The defendant alleges the state statute violates the First Amendment. Per Supreme Court doctrine, the federal court should:",
         [("Issue the injunction if the constitutional claim is meritorious", False),
          ("Abstain under Younger absent extraordinary circumstances (bad faith / harassment / patently unconstitutional statute)", True),
          ("Stay proceedings under Pullman", False),
          ("Dismiss for lack of jurisdiction", False)],
         "Younger v. Harris (1971) held that federal courts must abstain from enjoining ongoing state criminal proceedings absent extraordinary circumstances: (1) prosecution in bad faith / for harassment, (2) statute is flagrantly and patently unconstitutional, or (3) other extraordinary circumstances making equitable relief proper. Sprint Communications v. Jacobs (2013) limited Younger to (a) state criminal prosecutions, (b) certain civil enforcement, and (c) civil orders involving state-court orders for the judicial function.",
         [cite_scotus("Younger v. Harris, 401 U.S. 37 (1971)"),
          cite_scotus("Sprint Communications v. Jacobs, 571 U.S. 69 (2013)")],
         tags="us-conlaw,fed-courts,abstention", grammar_point="Younger abstention"),
    card("usconlaw-210",
         "A federal court is asked to interpret an unsettled state statute that may, depending on construction, raise a federal constitutional question. The federal court should typically:",
         [("Reach the constitutional question first", False),
          ("Abstain under Pullman to permit state courts to construe the statute first", True),
          ("Dismiss for lack of jurisdiction", False),
          ("Certify the question to the SCOTUS", False)],
         "Railroad Commission of Texas v. Pullman Co. (1941) established Pullman abstention: federal courts should abstain when (1) the federal constitutional question turns on an unsettled question of state law, and (2) state-court resolution might moot or alter the federal question. Pullman avoids unnecessary constitutional adjudication and federal-state friction. Distinct from Burford (review of complex state regulatory schemes), Colorado River (parallel state proceedings, exceptional circumstances), and Thibodaux (eminent domain).",
         [cite_scotus("Railroad Commission of Texas v. Pullman Co., 312 U.S. 496 (1941)"),
          cite_scotus("Burford v. Sun Oil Co., 319 U.S. 315 (1943)")],
         tags="us-conlaw,fed-courts,abstention", grammar_point="Pullman abstention"),
    card("usconlaw-211",
         "A federal district court diversity case applies state substantive law and federal procedural law. The doctrine governing this allocation derives from:",
         [("Sosa v. Alvarez-Machain", False),
          ("Erie R.R. Co. v. Tompkins (and refinements: Hanna v. Plumer)", True),
          ("Younger v. Harris", False),
          ("Cooper v. Aaron", False)],
         "Erie R.R. v. Tompkins (1938) overruled Swift v. Tyson and held that federal courts sitting in diversity must apply state substantive law (no general federal common law). Hanna v. Plumer (1965) refined the substance/procedure line: where a Federal Rule of Civil Procedure is on point and is valid under the Rules Enabling Act, it applies even if state procedure differs. Where no Federal Rule is on point, the 'outcome-determinative' test of Guaranty Trust v. York governs.",
         [cite_scotus("Erie R.R. Co. v. Tompkins, 304 U.S. 64 (1938)"),
          cite_scotus("Hanna v. Plumer, 380 U.S. 460 (1965)")],
         tags="us-conlaw,fed-courts,erie", grammar_point="Erie doctrine"),
    card("usconlaw-212",
         "A losing state-court litigant files a federal action in district court seeking effectively to overturn the state-court judgment. Per Supreme Court doctrine, the action is barred by:",
         [("Younger abstention", False),
          ("Rooker-Feldman doctrine — only SCOTUS may review state-court judgments", True),
          ("Erie", False),
          ("Burford abstention", False)],
         "Rooker v. Fidelity Trust Co. (1923) and District of Columbia Court of Appeals v. Feldman (1983) bar federal district courts from reviewing state-court judgments — that appellate function belongs only to the U.S. Supreme Court (28 U.S.C. § 1257). Exxon Mobil Corp. v. Saudi Basic Industries (2005) narrowed Rooker-Feldman to cases brought by state-court losers complaining of injuries caused by the state-court judgment and seeking review thereof.",
         [cite_scotus("Rooker v. Fidelity Trust Co., 263 U.S. 413 (1923)"),
          cite_scotus("Exxon Mobil Corp. v. Saudi Basic Industries Corp., 544 U.S. 280 (2005)")],
         tags="us-conlaw,fed-courts,rooker-feldman", grammar_point="Rooker-Feldman"),
    card("usconlaw-213",
         "Plaintiffs seek injunctive relief against a state official to enjoin enforcement of an allegedly unconstitutional state statute. The state asserts 11A sovereign immunity. Per Supreme Court doctrine, the suit:",
         [("Is barred by 11A immunity in all events", False),
          ("May proceed against the state official in his official capacity for prospective injunctive relief under Ex parte Young", True),
          ("May proceed only against the state itself", False),
          ("Is converted to a state-court matter", False)],
         "Ex parte Young (1908) created the foundational fiction that a state official enforcing an unconstitutional statute is 'stripped of his official representative character' — making the suit one against the individual, not the state. Ex parte Young permits PROSPECTIVE INJUNCTIVE RELIEF against state officials despite 11A. It does NOT permit retroactive monetary relief from the state treasury (Edelman v. Jordan).",
         [cite_scotus("Ex parte Young, 209 U.S. 123 (1908)"),
          cite_scotus("Edelman v. Jordan, 415 U.S. 651 (1974)")],
         tags="us-conlaw,fed-courts,ex-parte-young,11a", grammar_point="Ex parte Young"),
    card("usconlaw-214",
         "Plaintiffs sue based on a future, hypothetical injury that may or may not occur if certain government action takes place. The federal court should:",
         [("Decide the merits", False),
          ("Dismiss for lack of standing — Article III requires concrete, particularized, actual or imminent injury", True),
          ("Apply Pullman abstention", False),
          ("Certify the question to the SCOTUS", False)],
         "Lujan v. Defenders of Wildlife (1992) articulated the constitutional minimum of standing under Article III: (1) concrete and particularized INJURY in fact (actual or imminent), (2) CAUSATION traceable to defendant's conduct, and (3) REDRESSABILITY. Hypothetical, conjectural, or 'some day' injuries fail the imminence requirement. Spokeo v. Robins (2016) reinforced that statutory violations alone don't satisfy concreteness without separate harm.",
         [cite_scotus("Lujan v. Defenders of Wildlife, 504 U.S. 555 (1992)"),
          cite_scotus("Spokeo Inc. v. Robins, 578 U.S. 330 (2016)"),
          cite_scotus("TransUnion LLC v. Ramirez, 594 U.S. 413 (2021)")],
         tags="us-conlaw,fed-courts,standing", grammar_point="Lujan tripartite test"),
    # ─── State Sovereignty (4) ───────────────────────────────────
    card("usconlaw-215",
         "A state agency proceeding against a private party under state law is challenged on federal grounds. The state asserts 11A immunity in this administrative-adjudication forum. Per Supreme Court doctrine, the agency proceeding is:",
         [("Permitted because 11A applies only to courts", False),
          ("Barred under Federal Maritime Commission v. South Carolina State Ports Authority — sovereign immunity extends to federal agency adjudication", True),
          ("Permitted under the Spending Clause", False),
          ("Subject to abstention", False)],
         "FMC v. South Carolina State Ports Authority (2002) held that state sovereign immunity bars private-party adjudication against a state in a federal administrative agency, just as it would in a federal court. The Court reasoned that sovereign immunity protects against the indignity of being sued, not just the courthouse forum.",
         [cite_scotus("FMC v. South Carolina State Ports Authority, 535 U.S. 743 (2002)"),
          cite_scotus("Alden v. Maine, 527 U.S. 706 (1999)")],
         tags="us-conlaw,state-sovereignty,11a", grammar_point="FMC v. SC Ports"),
    card("usconlaw-216",
         "A private party sues a state in state court under a federal statute (FLSA). The state asserts sovereign immunity. Per Supreme Court doctrine, the suit:",
         [("May proceed because 11A applies only in federal court", False),
          ("Is barred — sovereign immunity is broader than 11A and extends to private suits in state court under federal law", True),
          ("Is barred only if Congress did not abrogate immunity", False),
          ("Is permitted under Ex parte Young", False)],
         "Alden v. Maine (1999) held that state sovereign immunity protects states from private suits in their OWN STATE COURTS for federal-law violations, even though 11A's text addresses only federal court. Sovereign immunity is a structural principle predating the Constitution. Congress may abrogate only via 14A § 5 enforcement power (not Article I), and only with clear statement.",
         [cite_scotus("Alden v. Maine, 527 U.S. 706 (1999)"),
          cite_scotus("Seminole Tribe v. Florida, 517 U.S. 44 (1996)")],
         tags="us-conlaw,state-sovereignty,11a,abrogation", grammar_point="Alden v. Maine"),
    card("usconlaw-217",
         "Congress, citing 14A § 5, enacts a statute creating a private cause of action against states for an alleged constitutional injury. The remedial measures are not 'congruent and proportional' to the constitutional violation. Per Supreme Court doctrine, the abrogation is:",
         [("Valid — Congress's § 5 power is plenary", False),
          ("Invalid under City of Boerne v. Flores's congruence and proportionality test", True),
          ("Valid under the Spending Clause", False),
          ("Subject to rational basis review", False)],
         "City of Boerne v. Flores (1997) struck down RFRA as applied to states. Congress's 14A § 5 enforcement power is REMEDIAL/PREVENTIVE, not substantive — § 5 legislation must show 'congruence and proportionality' between the constitutional injury identified and the means adopted. Boerne held RFRA was disproportionate to the records of religious-discrimination violations Congress had documented.",
         [cite_scotus("City of Boerne v. Flores, 521 U.S. 507 (1997)"),
          cite_scotus("Nevada Dep't of Human Resources v. Hibbs, 538 U.S. 721 (2003)")],
         tags="us-conlaw,state-sovereignty,boerne,abrogation", grammar_point="Boerne congruence-proportionality"),
    card("usconlaw-218",
         "A state employee sues the state under a federal age-discrimination statute. Congress purported to abrogate state sovereign immunity. Per Supreme Court doctrine, the abrogation is:",
         [("Valid under the Commerce Clause", False),
          ("Invalid — age is not a suspect class and Congress did not show a pattern of unconstitutional state age discrimination warranting prophylactic legislation", True),
          ("Valid under Boerne's congruence test", False),
          ("Subject to strict scrutiny", False)],
         "Kimel v. Florida Bd. of Regents (2000) struck down ADEA's abrogation of state immunity. Age classifications receive only RATIONAL BASIS review (Murgia, 1976), so Congress's record of state age-related conduct did not show widespread constitutional violations. Without a documented pattern of unconstitutional state discrimination, ADEA's prophylactic measures failed Boerne's congruence-proportionality test.",
         [cite_scotus("Kimel v. Florida Bd. of Regents, 528 U.S. 62 (2000)"),
          cite_scotus("Massachusetts Bd. of Retirement v. Murgia, 427 U.S. 307 (1976)")],
         tags="us-conlaw,state-sovereignty,abrogation,age", grammar_point="Kimel v. Florida"),
    # ─── Separation of Powers (8) ────────────────────────────────
    card("usconlaw-219",
         "The President orders the seizure of private steel mills during wartime to avert a labor strike. No statutory authorization exists; Congress has implicitly considered and rejected such authorization. Per Supreme Court doctrine, the seizure is:",
         [("Constitutional as Commander-in-Chief power", False),
          ("Unconstitutional — at the lowest ebb of presidential power per Justice Jackson's Youngstown framework", True),
          ("Constitutional under the Take Care Clause", False),
          ("Subject to political-question doctrine", False)],
         "Youngstown Sheet & Tube Co. v. Sawyer (1952) struck down President Truman's seizure of steel mills during the Korean War. Justice Jackson's concurrence (the canonical SoP framework): (1) when President acts WITH congressional authorization, presidential power is at its MAXIMUM; (2) when Congress is SILENT, in a 'zone of twilight'; (3) when President acts AGAINST congressional will, power is at its 'LOWEST EBB' and may be sustained only on his constitutional authority minus Congress's.",
         [cite_scotus("Youngstown Sheet & Tube Co. v. Sawyer, 343 U.S. 579 (1952)")],
         tags="us-conlaw,sep-of-powers,executive", grammar_point="Youngstown Jackson framework"),
    card("usconlaw-220",
         "Congress enacts a one-house veto provision allowing either chamber, by simple majority, to override an executive deportation suspension. Per Supreme Court doctrine, the legislative veto is:",
         [("Constitutional — Congress may oversee delegated power", False),
          ("Unconstitutional — legislative action requires bicameralism and presentment", True),
          ("Subject to political-question doctrine", False),
          ("Constitutional only for foreign-affairs matters", False)],
         "INS v. Chadha (1983) struck down the one-house legislative veto. The Court held that any congressional action with the purpose and effect of altering legal rights, duties, and relations of persons outside the legislative branch is 'legislative' and therefore must satisfy ARTICLE I § 7's BICAMERALISM and PRESENTMENT requirements. Hundreds of legislative-veto provisions across federal statutes were invalidated.",
         [cite_scotus("INS v. Chadha, 462 U.S. 919 (1983)")],
         tags="us-conlaw,sep-of-powers,legislative-veto", grammar_point="INS v. Chadha"),
    card("usconlaw-221",
         "Congress enacts the Line Item Veto Act, allowing the President to cancel specific items of new direct spending after signing the bill. Per Supreme Court doctrine, the Act is:",
         [("Constitutional under the Take Care Clause", False),
          ("Unconstitutional — violates the Presentment Clause's requirement that the President sign or veto bills as passed", True),
          ("Constitutional — Congress may delegate cancellation power", False),
          ("Subject to rational basis review", False)],
         "Clinton v. City of New York (1998) struck down the Line Item Veto Act. The Court held that the Presentment Clause requires the President to approve OR veto bills as a whole — the Act's grant of authority to cancel parts of a duly enacted statute amounted to amending or repealing federal law unilaterally, contrary to the constitutional design.",
         [cite_scotus("Clinton v. City of New York, 524 U.S. 417 (1998)")],
         tags="us-conlaw,sep-of-powers,line-item-veto", grammar_point="Clinton v. NYC"),
    card("usconlaw-222",
         "The President makes appointments to NLRB seats during a 3-day intra-session Senate recess, claiming the Recess Appointments Clause. Per Supreme Court doctrine, the appointments are:",
         [("Constitutional — any recess permits recess appointments", False),
          ("Unconstitutional — recess of less than 10 days is presumptively too short to trigger the Clause", True),
          ("Constitutional under inherent executive authority", False),
          ("Subject to political-question doctrine", False)],
         "NLRB v. Noel Canning (2014) sharply curtailed recess appointments. The Court held: (1) the Clause covers both inter-session AND intra-session recesses, BUT (2) only recesses of substantial length — recesses of less than 10 days are presumptively too short to permit recess appointments absent unusual circumstances. The President's 3-day intra-session appointments were invalidated.",
         [cite_scotus("NLRB v. Noel Canning, 573 U.S. 513 (2014)")],
         tags="us-conlaw,sep-of-powers,recess-appointments", grammar_point="NLRB v. Noel Canning"),
    card("usconlaw-223",
         "Congress creates an independent agency headed by a single director, removable by the President only for inefficiency, neglect, or malfeasance. Per Supreme Court doctrine, the structure is:",
         [("Constitutional under Humphrey's Executor", False),
          ("Unconstitutional — single-director independent agencies violate separation of powers; for-cause removal is incompatible with the unitary executive", True),
          ("Constitutional under the Take Care Clause", False),
          ("Subject to political-question doctrine", False)],
         "Seila Law LLC v. CFPB (2020) held that a SINGLE-director independent agency (CFPB) violates separation of powers. While Humphrey's Executor (1935) permits for-cause removal restrictions on multi-member commissions, and Morrison v. Olson (1988) upheld restrictions on inferior officers, the President must retain at-will removal of single principal officers. Collins v. Yellen (2021) extended this to FHFA.",
         [cite_scotus("Seila Law LLC v. CFPB, 591 U.S. 197 (2020)"),
          cite_scotus("Collins v. Yellen, 594 U.S. 220 (2021)"),
          cite_scotus("Free Enterprise Fund v. PCAOB, 561 U.S. 477 (2010)")],
         tags="us-conlaw,sep-of-powers,removal", grammar_point="Seila Law / Collins"),
    card("usconlaw-224",
         "An agency adopts a major regulatory rule of broad economic and political significance. The agency's authorizing statute does not clearly grant such sweeping power. Per Supreme Court doctrine, the rule is most likely:",
         [("Entitled to Chevron deference", False),
          ("Invalid under the major questions doctrine — clear congressional authorization is required", True),
          ("Constitutional under the necessary and proper clause", False),
          ("Subject to rational basis review", False)],
         "West Virginia v. EPA (2022) and Biden v. Nebraska (2023) consolidated the MAJOR QUESTIONS DOCTRINE: when an agency claims regulatory authority over questions of vast economic and political significance, courts require CLEAR congressional authorization, not mere ambiguity. The doctrine works in tandem with the post-Loper Bright (2024) elimination of Chevron deference.",
         [cite_scotus("West Virginia v. EPA, 597 U.S. 697 (2022)"),
          cite_scotus("Biden v. Nebraska, 600 U.S. 477 (2023)"),
          cite_scotus("Loper Bright Enterprises v. Raimondo, 603 U.S. 369 (2024)")],
         tags="us-conlaw,sep-of-powers,admin", grammar_point="Major questions doctrine"),
    card("usconlaw-225",
         "A federal grand jury subpoenas the President's personal financial records held by his accountants in the context of a state criminal investigation. Per Supreme Court doctrine, the subpoena is:",
         [("Per se invalid — the President is absolutely immune from state criminal process", False),
          ("Permitted — Article II affords no absolute immunity from state grand-jury subpoenas, though enforcement may be subject to challenge on traditional grounds", True),
          ("Subject to political-question doctrine", False),
          ("Permitted only with congressional authorization", False)],
         "Trump v. Vance (2020) held that a sitting President is NOT absolutely immune from state criminal subpoenas served on third parties for the President's personal records. The President may, however, raise traditional subpoena objections (relevance, undue burden). Trump v. Mazars (2020), the companion case, applied a more demanding balancing test to congressional subpoenas for the same records.",
         [cite_scotus("Trump v. Vance, 591 U.S. 786 (2020)"),
          cite_scotus("Trump v. Mazars USA LLP, 591 U.S. 848 (2020)"),
          cite_scotus("United States v. Nixon, 418 U.S. 683 (1974)")],
         tags="us-conlaw,sep-of-powers,executive-privilege", grammar_point="Trump v. Vance / Mazars"),
    card("usconlaw-226",
         "A former President is criminally indicted for actions allegedly taken while in office. Per Supreme Court doctrine, the prosecution is:",
         [("Per se barred", False),
          ("Subject to a presumption of immunity for official conduct (absolute immunity for core constitutional powers; presumptive immunity for other official acts; no immunity for unofficial conduct)", True),
          ("Subject to political-question doctrine", False),
          ("Constitutional only with congressional authorization", False)],
         "Trump v. United States (2024) created a tiered immunity framework for former Presidents facing criminal prosecution: (1) ABSOLUTE immunity for actions within the President's CORE constitutional powers, (2) PRESUMPTIVE immunity for OTHER OFFICIAL acts (rebuttable on showing prosecution poses no danger to executive function), and (3) NO immunity for UNOFFICIAL conduct. The decision reshapes presidential accountability for official-capacity conduct.",
         [cite_scotus("Trump v. United States, 603 U.S. 593 (2024)"),
          cite_scotus("Nixon v. Fitzgerald, 457 U.S. 731 (1982)")],
         tags="us-conlaw,sep-of-powers,immunity", grammar_point="Trump v. United States (2024)"),
    # ─── 1A (7) ──────────────────────────────────────────────────
    card("usconlaw-227",
         "The federal government seeks a prior restraint to prevent publication of the Pentagon Papers, classified documents on Vietnam War policy. Per Supreme Court doctrine, the government must:",
         [("Show probable harm to national security", False),
          ("Carry a heavy burden — prior restraints bear a strong presumption against constitutionality", True),
          ("Show a compelling interest only", False),
          ("Subject the issue to political-question analysis", False)],
         "New York Times Co. v. United States (1971) (Pentagon Papers) refused to enjoin publication of the classified study. The Court reaffirmed Near v. Minnesota (1931): prior restraints on speech bear a HEAVY presumption against constitutionality. The government failed to meet that burden even with national-security claims. Each Justice wrote separately; the per curiam was a single paragraph.",
         [cite_scotus("New York Times Co. v. United States, 403 U.S. 713 (1971)"),
          cite_scotus("Near v. Minnesota, 283 U.S. 697 (1931)")],
         tags="us-conlaw,first-amendment,prior-restraint", grammar_point="Pentagon Papers / Near"),
    card("usconlaw-228",
         "Congress enacts a federal statute prohibiting registration of trademarks that 'disparage' particular groups. Per Supreme Court doctrine, the statute is most likely:",
         [("Constitutional as government speech", False),
          ("Unconstitutional as viewpoint discrimination in violation of the 1A", True),
          ("Constitutional under intermediate scrutiny", False),
          ("Constitutional under rational basis review", False)],
         "Matal v. Tam (2017) struck down the Lanham Act's disparagement clause as unconstitutional viewpoint discrimination. Iancu v. Brunetti (2019) extended this and struck the immoral/scandalous clause. Trademark registration is not government speech; the statute's restriction on registration based on viewpoint violates the First Amendment.",
         [cite_scotus("Matal v. Tam, 582 U.S. 218 (2017)"),
          cite_scotus("Iancu v. Brunetti, 588 U.S. 388 (2019)")],
         tags="us-conlaw,first-amendment,viewpoint-discrimination", grammar_point="Matal v. Tam"),
    card("usconlaw-229",
         "Congress enacts an aggregate cap on individual political contributions across all federal candidates per election cycle. Per Supreme Court doctrine, the aggregate cap is:",
         [("Constitutional under intermediate scrutiny", False),
          ("Unconstitutional — aggregate caps unconstitutionally restrict political speech and association", True),
          ("Subject to rational basis review", False),
          ("Constitutional under Buckley's anti-corruption rationale", False)],
         "McCutcheon v. FEC (2014) struck down BCRA's aggregate limits on contributions across federal candidates. The Court reaffirmed Buckley v. Valeo's distinction between INDIVIDUAL CANDIDATE LIMITS (constitutional, anti-quid-pro-quo rationale) and EXPENDITURE LIMITS (unconstitutional). Aggregate limits, like expenditure caps, do not target quid pro quo corruption and burden core political speech.",
         [cite_scotus("McCutcheon v. FEC, 572 U.S. 185 (2014)"),
          cite_scotus("Buckley v. Valeo, 424 U.S. 1 (1976)"),
          cite_scotus("Citizens United v. FEC, 558 U.S. 310 (2010)")],
         tags="us-conlaw,first-amendment,campaign-finance", grammar_point="McCutcheon v. FEC"),
    card("usconlaw-230",
         "A state university student-activity fund subsidizes religious-themed publications on the same terms as secular publications. The university denies funding to a religious publication. Per Supreme Court doctrine, the denial is:",
         [("Required by the Establishment Clause", False),
          ("Unconstitutional viewpoint discrimination — religious viewpoint may not be excluded from a viewpoint-neutral subsidy", True),
          ("Constitutional under intermediate scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "Rosenberger v. Rector & Visitors of Univ. of Virginia (1995) held that a public university's exclusion of a religious student publication from a viewpoint-neutral student-activity-fee subsidy was unconstitutional viewpoint discrimination. The Establishment Clause does not require, and the Free Speech Clause does not permit, exclusion of religious viewpoints from a public forum. Trinity Lutheran (2017), Espinoza (2020), and Carson (2022) extend this principle to state aid programs.",
         [cite_scotus("Rosenberger v. Rector and Visitors, 515 U.S. 819 (1995)"),
          cite_scotus("Carson v. Makin, 596 U.S. 767 (2022)")],
         tags="us-conlaw,first-amendment,viewpoint,religion", grammar_point="Rosenberger v. UVA"),
    card("usconlaw-231",
         "A public school district adopts a policy of student-led prayer at football games over loudspeakers. Per Supreme Court doctrine, the policy is:",
         [("Constitutional under Lemon's accommodation prong", False),
          ("Unconstitutional under the Establishment Clause as government endorsement of religion", True),
          ("Constitutional under historical practice", False),
          ("Subject to rational basis review", False)],
         "Santa Fe Independent School Dist. v. Doe (2000) struck down a school-sponsored, student-led prayer-at-football-games policy. The Court held the policy effectively endorsed religion in a school-controlled setting. NOTE: Kennedy v. Bremerton (2022) abandoned the Lemon test in favor of a historical-practices-and-understandings approach, but Santa Fe's specific holding on coercive school prayer remains persuasive.",
         [cite_scotus("Santa Fe Indep. School Dist. v. Doe, 530 U.S. 290 (2000)"),
          cite_scotus("Kennedy v. Bremerton School District, 597 U.S. 507 (2022)")],
         tags="us-conlaw,first-amendment,establishment", grammar_point="Santa Fe v. Doe"),
    card("usconlaw-232",
         "A state requires a public-employee union to receive 'agency fees' (an amount equal to dues) from non-members in the bargaining unit to cover collective-bargaining costs. Per Supreme Court doctrine, the agency-fee requirement is:",
         [("Constitutional under Abood v. Detroit Bd. of Education", False),
          ("Unconstitutional — compelled subsidization of public-sector union speech violates 1A", True),
          ("Constitutional under intermediate scrutiny", False),
          ("Subject to rational basis review", False)],
         "Janus v. AFSCME (2018) overruled Abood (1977) and held that compelling non-members to subsidize public-sector union activity violates the First Amendment. Public-sector collective bargaining is inherently political, and forcing non-members to fund such advocacy compels speech. Affirmative consent (opt-in) is required.",
         [cite_scotus("Janus v. AFSCME, 585 U.S. 878 (2018)"),
          cite_scotus("Abood v. Detroit Bd. of Education, 431 U.S. 209 (1977)")],
         tags="us-conlaw,first-amendment,compelled-speech", grammar_point="Janus v. AFSCME"),
    card("usconlaw-233",
         "A public school disciplines a student for off-campus social-media speech criticizing the school's cheerleading program. Per Supreme Court doctrine, the discipline is most likely:",
         [("Constitutional under Tinker's substantial-disruption rule", False),
          ("Unconstitutional — schools' disciplinary authority over OFF-CAMPUS student speech is sharply diminished", True),
          ("Constitutional under in loco parentis", False),
          ("Subject to rational basis review", False)],
         "Mahanoy Area School District v. B.L. (2021) held that a public school's discipline of a student for off-campus social-media speech (a Snapchat outburst about cheerleading tryouts) violated the First Amendment. While schools retain SOME authority over off-campus speech in narrow circumstances (e.g., true threats, harassment, classroom integrity), the Tinker substantial-disruption test applies with diminished force off-campus.",
         [cite_scotus("Mahanoy Area School District v. B.L., 594 U.S. 180 (2021)"),
          cite_scotus("Tinker v. Des Moines, 393 U.S. 503 (1969)")],
         tags="us-conlaw,first-amendment,student-speech", grammar_point="Mahanoy v. B.L."),
    # ─── EP/DP (6) ───────────────────────────────────────────────
    card("usconlaw-234",
         "A state revokes a public-employee benefit. The employee challenges the revocation procedure as denying due process. Per Supreme Court doctrine, the analysis applies:",
         [("Strict scrutiny", False),
          ("The Mathews v. Eldridge balancing test (private interest × risk of error × government interest)", True),
          ("Rational basis review", False),
          ("Heightened scrutiny", False)],
         "Mathews v. Eldridge (1976) supplied the canonical procedural-due-process balancing test: courts weigh (1) the PRIVATE interest at stake, (2) the RISK of erroneous deprivation under existing procedures and the value of additional safeguards, and (3) the GOVERNMENT's interest (efficiency, fiscal/administrative burden). Cleveland Board of Education v. Loudermill (1985) applied this to public-employee terminations.",
         [cite_scotus("Mathews v. Eldridge, 424 U.S. 319 (1976)"),
          cite_scotus("Cleveland Bd. of Education v. Loudermill, 470 U.S. 532 (1985)")],
         tags="us-conlaw,due-process,procedural", grammar_point="Mathews v. Eldridge"),
    card("usconlaw-235",
         "A state denies a 17-year-old a driver's license while granting them to 18-year-olds. The classification is challenged. Per Supreme Court doctrine, the classification receives:",
         [("Strict scrutiny", False),
          ("Rational basis review — age is not a suspect class", True),
          ("Intermediate scrutiny", False),
          ("Heightened scrutiny", False)],
         "Massachusetts Bd. of Retirement v. Murgia (1976) held that age classifications receive only RATIONAL BASIS review under the Equal Protection Clause. Age is not a suspect class — the elderly are not a discrete and insular minority lacking political power. Kimel v. Florida (2000) relied on Murgia to invalidate ADEA's abrogation of state immunity.",
         [cite_scotus("Massachusetts Bd. of Retirement v. Murgia, 427 U.S. 307 (1976)"),
          cite_scotus("Kimel v. Florida Bd. of Regents, 528 U.S. 62 (2000)")],
         tags="us-conlaw,equal-protection,age", grammar_point="Murgia v. Massachusetts"),
    card("usconlaw-236",
         "A state grants public-school benefits to legitimate children but denies them to children born out of wedlock. Per Supreme Court doctrine, the classification receives:",
         [("Strict scrutiny", False),
          ("Intermediate scrutiny — illegitimacy is a quasi-suspect classification", True),
          ("Rational basis review", False),
          ("Heightened scrutiny", False)],
         "Clark v. Jeter (1988) and Mills v. Habluetzel (1982) hold that classifications based on illegitimacy receive INTERMEDIATE SCRUTINY: the law must be substantially related to an important governmental interest. Like sex classifications, illegitimacy is quasi-suspect — the children bear no responsibility for the conduct of their parents and have suffered historic discrimination.",
         [cite_scotus("Clark v. Jeter, 486 U.S. 456 (1988)"),
          cite_scotus("Mills v. Habluetzel, 456 U.S. 91 (1982)"),
          cite_scotus("Trimble v. Gordon, 430 U.S. 762 (1977)")],
         tags="us-conlaw,equal-protection,illegitimacy", grammar_point="Clark v. Jeter"),
    card("usconlaw-237",
         "A state criminal statute prohibits adult, consensual, same-sex intimate conduct in private. Per Supreme Court doctrine, the statute is:",
         [("Constitutional under traditional moral disapprobation", False),
          ("Unconstitutional — substantive due process protects intimate adult relationships", True),
          ("Subject to rational basis review", False),
          ("Constitutional under the state's police power", False)],
         "Lawrence v. Texas (2003) overruled Bowers v. Hardwick (1986) and held that adult consensual same-sex intimate conduct is protected by substantive due process under the 14A. The Court applied something more than rational-basis (though did not formally announce a new tier), emphasizing autonomy in intimate relationships. Foundation for Obergefell v. Hodges (2015).",
         [cite_scotus("Lawrence v. Texas, 539 U.S. 558 (2003)"),
          cite_scotus("Obergefell v. Hodges, 576 U.S. 644 (2015)")],
         tags="us-conlaw,due-process,substantive,intimate-conduct", grammar_point="Lawrence v. Texas"),
    card("usconlaw-238",
         "A state denies a marriage license to a same-sex couple. Per Supreme Court doctrine, the denial:",
         [("Is constitutional under the state's police power", False),
          ("Violates the 14A's Due Process and Equal Protection Clauses — marriage is a fundamental right that may not be denied based on sexual orientation", True),
          ("Subject to rational basis review only", False),
          ("Subject to political-question doctrine", False)],
         "Obergefell v. Hodges (2015) held that the right to marry is a fundamental right inherent in the liberty of the person, protected by the Due Process and Equal Protection Clauses. States must license same-sex marriages and must recognize same-sex marriages lawfully performed in other states. The decision relied on history of marriage as a foundational institution and modern understanding of equal dignity.",
         [cite_scotus("Obergefell v. Hodges, 576 U.S. 644 (2015)"),
          cite_scotus("United States v. Windsor, 570 U.S. 744 (2013)")],
         tags="us-conlaw,due-process,equal-protection,marriage", grammar_point="Obergefell v. Hodges"),
    card("usconlaw-239",
         "A state law prohibits abortion at all stages of pregnancy except for limited exceptions (medical emergency). Per Supreme Court doctrine post-Dobbs, the law is most likely:",
         [("Unconstitutional under Roe/Casey", False),
          ("Constitutional — Dobbs returned the abortion question to the political process; rational basis review applies", True),
          ("Subject to strict scrutiny", False),
          ("Subject to undue-burden analysis", False)],
         "Dobbs v. Jackson Women's Health Organization (2022) overruled Roe v. Wade (1973) and Planned Parenthood v. Casey (1992), holding the Constitution does not confer a right to abortion. Abortion regulation is returned to the states (and Congress); rational-basis review applies. The dissent argued (and many scholars maintain) that Dobbs's reasoning could destabilize other unenumerated substantive-due-process rights.",
         [cite_scotus("Dobbs v. Jackson Women's Health Organization, 597 U.S. 215 (2022)"),
          cite_scotus("Planned Parenthood v. Casey, 505 U.S. 833 (1992)"),
          cite_scotus("Roe v. Wade, 410 U.S. 113 (1973)")],
         tags="us-conlaw,due-process,abortion", grammar_point="Dobbs v. Jackson"),
    # ─── Death penalty (3) ───────────────────────────────────────
    card("usconlaw-240",
         "A state imposes the death penalty for a defendant who was 17 at the time of the crime. Per Supreme Court doctrine, the sentence is:",
         [("Constitutional if the defendant is competent", False),
          ("Unconstitutional under the 8A — execution of those under 18 at the time of the crime is categorically barred", True),
          ("Subject to individualized determination", False),
          ("Constitutional under death penalty statutes generally", False)],
         "Roper v. Simmons (2005) categorically barred the death penalty for offenders under 18 at the time of the crime, overruling Stanford v. Kentucky (1989). The Court relied on a national consensus against juvenile executions and on developmental science showing diminished culpability of juveniles. This extended Atkins v. Virginia's (2002) categorical bar on executing the intellectually disabled.",
         [cite_scotus("Roper v. Simmons, 543 U.S. 551 (2005)"),
          cite_scotus("Atkins v. Virginia, 536 U.S. 304 (2002)")],
         tags="us-conlaw,eighth-amendment,death-penalty,juvenile", grammar_point="Roper v. Simmons"),
    card("usconlaw-241",
         "A death-row inmate challenges the state's lethal injection protocol as cruel and unusual. Per Supreme Court doctrine post-Glossip, the inmate must:",
         [("Show the protocol is cruel and unusual under contemporary standards", False),
          ("Show a known and available alternative method that significantly reduces the risk of severe pain", True),
          ("Show categorical unconstitutionality", False),
          ("Demonstrate a violation of due process", False)],
         "Glossip v. Gross (2015) and Bucklew v. Precythe (2019) require an 8A method-of-execution challenger to demonstrate that the State's chosen method poses a SUBSTANTIAL RISK of SEVERE PAIN compared to a KNOWN, AVAILABLE ALTERNATIVE that significantly reduces that risk. The alternative may be from another State or feasible to implement. Bucklew further held that the 8A requires no painless death.",
         [cite_scotus("Glossip v. Gross, 576 U.S. 863 (2015)"),
          cite_scotus("Bucklew v. Precythe, 587 U.S. 119 (2019)"),
          cite_scotus("Baze v. Rees, 553 U.S. 35 (2008)")],
         tags="us-conlaw,eighth-amendment,death-penalty,method", grammar_point="Glossip v. Gross"),
    card("usconlaw-242",
         "A defendant challenges his death sentence as racially biased, citing statistical evidence (the Baldus study) of statewide racial disparities in capital sentencing. Per Supreme Court doctrine, the challenge:",
         [("Is sufficient to vacate the sentence", False),
          ("Fails — the defendant must show purposeful discrimination in HIS case, not statewide patterns", True),
          ("Triggers strict scrutiny", False),
          ("Is subject to political-question analysis", False)],
         "McCleskey v. Kemp (1987) held that statistical evidence of statewide racial disparities in capital sentencing is INSUFFICIENT to establish an 8A or 14A violation. The defendant must show that decisionmakers in HIS particular case acted with discriminatory purpose. McCleskey is widely cited as one of the most criticized post-Furman death penalty decisions; Justice Powell later expressed regret.",
         [cite_scotus("McCleskey v. Kemp, 481 U.S. 279 (1987)"),
          cite_scotus("Furman v. Georgia, 408 U.S. 238 (1972)")],
         tags="us-conlaw,eighth-amendment,death-penalty,race", grammar_point="McCleskey v. Kemp"),
    # ─── 4A/5A/6A (5) ────────────────────────────────────────────
    card("usconlaw-243",
         "Police obtain evidence under a search warrant later deemed invalid for lack of probable cause, but the officers acted in objectively reasonable reliance on the warrant. Per Supreme Court doctrine, the evidence is:",
         [("Suppressed under the exclusionary rule", False),
          ("Admissible under the good-faith exception", True),
          ("Admissible only if the warrant was facially valid", False),
          ("Subject to fruit-of-the-poisonous-tree analysis", False)],
         "United States v. Leon (1984) created the GOOD-FAITH EXCEPTION to the exclusionary rule: evidence obtained in OBJECTIVELY REASONABLE RELIANCE on a warrant later determined invalid is admissible. The exception does not apply if the magistrate was misled, abandoned the judicial role, or the warrant was facially deficient or based on a 'bare-bones' affidavit. Davis v. United States (2011) extended good-faith to reliance on appellate precedent later overruled.",
         [cite_scotus("United States v. Leon, 468 U.S. 897 (1984)"),
          cite_scotus("Davis v. United States, 564 U.S. 229 (2011)")],
         tags="us-conlaw,fourth-amendment,exclusionary-rule", grammar_point="Leon good-faith exception"),
    card("usconlaw-244",
         "Police, with reasonable suspicion but without probable cause, immediately ask a suspect a question necessary to address an imminent public-safety threat (e.g., 'Where is the gun?') without first giving Miranda warnings. The suspect's answer is then offered against him. Per Supreme Court doctrine, the answer is:",
         [("Inadmissible under Miranda", False),
          ("Admissible under the public-safety exception", True),
          ("Inadmissible as fruit of the poisonous tree", False),
          ("Subject to attenuation analysis", False)],
         "New York v. Quarles (1984) established the public-safety exception to Miranda: officers may ask questions reasonably prompted by concern for public safety (e.g., locating a gun in a public store) without first giving Miranda warnings. The unwarned answer is admissible. The exception is narrow — questions must be objectively related to ensuring public safety, not investigatory.",
         [cite_scotus("New York v. Quarles, 467 U.S. 649 (1984)"),
          cite_scotus("Miranda v. Arizona, 384 U.S. 436 (1966)")],
         tags="us-conlaw,fifth-amendment,miranda,public-safety", grammar_point="Quarles public-safety exception"),
    card("usconlaw-245",
         "A criminal defendant invokes his right to counsel during custodial interrogation. Police cease questioning. Two weeks later, after the defendant has been released to general prison population, police re-initiate questioning with Miranda warnings; the defendant waives. Per Supreme Court doctrine, the waiver is:",
         [("Per se invalid under Edwards v. Arizona", False),
          ("Valid — release from custodial pressure for at least 14 days breaks the Edwards bar", True),
          ("Valid only with re-invocation", False),
          ("Subject to the totality of circumstances", False)],
         "Edwards v. Arizona (1981) held that once a suspect invokes Miranda right to counsel, police may not resume interrogation until counsel has been made available, UNLESS the suspect himself initiates further communication. Maryland v. Shatzer (2010) carved a 14-DAY break-in-custody exception: if the suspect has been released from custodial pressures (including return to general prison population) for at least 14 days, the Edwards bar lifts.",
         [cite_scotus("Edwards v. Arizona, 451 U.S. 477 (1981)"),
          cite_scotus("Maryland v. Shatzer, 559 U.S. 98 (2010)")],
         tags="us-conlaw,fifth-amendment,miranda,counsel", grammar_point="Edwards / Shatzer"),
    card("usconlaw-246",
         "At a defendant's trial, the prosecution introduces a forensic lab report through a surrogate analyst who did not perform the underlying tests. The defendant did not have an opportunity to cross-examine the original analyst. Per Supreme Court doctrine, the admission:",
         [("Is constitutional if the report is reliable", False),
          ("Violates the 6A Confrontation Clause — testimonial statements require live witness subject to cross-examination", True),
          ("Is constitutional under business-records exception", False),
          ("Subject to harmless-error review only", False)],
         "Bullcoming v. New Mexico (2011), following Crawford v. Washington (2004) and Melendez-Diaz v. Massachusetts (2009), held that forensic lab reports are TESTIMONIAL statements subject to the Confrontation Clause. The prosecution must produce the actual analyst who performed the tests, not a surrogate. Williams v. Illinois (2012, plurality) created some uncertainty about expert testimony based on others' work.",
         [cite_scotus("Bullcoming v. New Mexico, 564 U.S. 647 (2011)"),
          cite_scotus("Crawford v. Washington, 541 U.S. 36 (2004)"),
          cite_scotus("Melendez-Diaz v. Massachusetts, 557 U.S. 305 (2009)")],
         tags="us-conlaw,sixth-amendment,confrontation", grammar_point="Bullcoming / Crawford"),
    card("usconlaw-247",
         "A prosecutor uses peremptory challenges to strike all Black potential jurors in a capital trial of a Black defendant. The state offers race-neutral reasons for each strike. Per Supreme Court doctrine, the strikes are:",
         [("Constitutional under Swain v. Alabama", False),
          ("Subject to Batson's three-step framework — defendant prima facie case → state's race-neutral reason → trial court's pretext determination", True),
          ("Per se constitutional", False),
          ("Subject to harmless-error review only", False)],
         "Batson v. Kentucky (1986) established the 14A framework barring race-based peremptory challenges, overruling the more permissive Swain (1965) rule. Three-step framework: (1) defendant's prima facie case of racial discrimination, (2) state's race-neutral explanation, (3) trial court's determination of pretext. Flowers v. Mississippi (2019) reaffirmed Batson's vitality across multiple retrials.",
         [cite_scotus("Batson v. Kentucky, 476 U.S. 79 (1986)"),
          cite_scotus("Flowers v. Mississippi, 588 U.S. 284 (2019)"),
          cite_scotus("J.E.B. v. Alabama ex rel. T.B., 511 U.S. 127 (1994)")],
         tags="us-conlaw,sixth-amendment,batson", grammar_point="Batson three-step"),
    # ─── 8A non-capital (3) ──────────────────────────────────────
    card("usconlaw-248",
         "A juvenile is sentenced to mandatory life without parole for a non-homicide offense. Per Supreme Court doctrine, the sentence is:",
         [("Constitutional if individualized", False),
          ("Categorically unconstitutional under the 8A", True),
          ("Constitutional under the state's police power", False),
          ("Subject to rational basis review", False)],
         "Graham v. Florida (2010) categorically barred LWOP sentences for juveniles convicted of NON-HOMICIDE offenses. Miller v. Alabama (2012) extended this to bar MANDATORY LWOP for juvenile homicide offenders (the sentencer must consider youth and attendant circumstances). Montgomery v. Louisiana (2016) made Miller retroactive on collateral review. Jones v. Mississippi (2021) did not require an explicit finding of permanent incorrigibility before discretionary LWOP.",
         [cite_scotus("Graham v. Florida, 560 U.S. 48 (2010)"),
          cite_scotus("Miller v. Alabama, 567 U.S. 460 (2012)"),
          cite_scotus("Montgomery v. Louisiana, 577 U.S. 190 (2016)")],
         tags="us-conlaw,eighth-amendment,juvenile-lwop", grammar_point="Graham / Miller"),
    card("usconlaw-249",
         "Prison officials are deliberately indifferent to a prisoner's serious medical needs, resulting in significant harm. Per Supreme Court doctrine, this constitutes:",
         [("Mere negligence", False),
          ("An 8A violation — cruel and unusual punishment", True),
          ("A 14A due process violation only", False),
          ("Constitutional under prison administration deference", False)],
         "Estelle v. Gamble (1976) held that DELIBERATE INDIFFERENCE to a prisoner's SERIOUS MEDICAL NEEDS constitutes cruel and unusual punishment under the 8A. Mere negligence is insufficient — the official must know of and disregard an excessive risk. Farmer v. Brennan (1994) clarified that deliberate indifference is a SUBJECTIVE standard requiring actual knowledge of the risk. Helling v. McKinney (1993) extended this to future health risks (secondhand smoke).",
         [cite_scotus("Estelle v. Gamble, 429 U.S. 97 (1976)"),
          cite_scotus("Farmer v. Brennan, 511 U.S. 825 (1994)")],
         tags="us-conlaw,eighth-amendment,prison-conditions", grammar_point="Estelle / Farmer deliberate indifference"),
    card("usconlaw-250",
         "A state imposes a $10 million civil penalty for a regulatory violation that caused $50,000 in actual harm. Per Supreme Court doctrine, the penalty is:",
         [("Constitutional under the state's police power", False),
          ("Subject to 8A excessive-fines analysis (incorporated against the states via 14A) and may be unconstitutional if grossly disproportional", True),
          ("Constitutional under intermediate scrutiny", False),
          ("Subject to rational basis review", False)],
         "Timbs v. Indiana (2019) incorporated the 8A's Excessive Fines Clause against the states via the 14A, in the context of civil-asset forfeiture. United States v. Bajakajian (1998) supplied the test: a fine is excessive if it is GROSSLY DISPROPORTIONAL to the gravity of the offense. The clause applies to both criminal punishments and civil-in-rem forfeitures that are at least partly punitive.",
         [cite_scotus("Timbs v. Indiana, 586 U.S. 146 (2019)"),
          cite_scotus("United States v. Bajakajian, 524 U.S. 321 (1998)")],
         tags="us-conlaw,eighth-amendment,excessive-fines", grammar_point="Timbs / Bajakajian"),
]


def main():
    data = json.loads(CARDS_PATH.read_text(encoding="utf-8"))
    cards = data["cards"]
    existing_ids = {c["id"] for c in cards}
    added = 0
    for card_dict in NEW_CARDS:
        if card_dict["id"] not in existing_ids:
            cards.append(card_dict)
            added += 1
    tmp = CARDS_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps({"cards": cards}, ensure_ascii=False, indent=2) + "\n",
                   encoding="utf-8")
    tmp.replace(CARDS_PATH)
    print(f"Added {added} new cards. Total cards now: {len(cards)}.")


if __name__ == "__main__":
    main()
