"""PR #5 (v0.5) — 50 NEW validated us-conlaw cards (151-200) under the
standing rule (CLAUDE.md §5.2). Topics emphasize areas not yet covered
in cards 001-150: 4A/5A/6A continuations, takings, habeas, race-conscious
districting, affirmative action history, more religion clauses.

Run from repo root:
    python scripts\\add_pr5_cards.py
"""
from __future__ import annotations

import json
from pathlib import Path
from urllib.parse import quote_plus

CARDS_PATH = Path(__file__).resolve().parent.parent / "src" / "main" / "resources" / "subjects" / "us-conlaw" / "cards.json"


def google_url(label: str) -> str:
    return f"https://www.google.com/search?q={quote_plus(label)}"


def cite_scotus(label: str) -> dict:
    return {"label": label, "url": google_url(label), "type": "scotus"}


def cite_lr(label: str) -> dict:
    return {"label": label, "url": google_url(label), "type": "law-review"}


def card(id_, stem, choices_with_correct, explanation, citations,
         tags="us-conlaw", grammar_point="", difficulty=3):
    return {
        "id": id_, "kind": "grammar", "level": "",
        "stem": stem, "grammar_point": grammar_point,
        "choices": [{"text": t, "is_correct": c} for t, c in choices_with_correct],
        "translation_zh_tw": "", "translation_zh_cn": "", "translation_en": "",
        "explanation": explanation, "difficulty": difficulty, "tags": tags,
        "source": "claude-authored-may-2026",
        "provenance": "human_curated",
        "attribution": "Claude PR #5 (validated bank). Awaiting expert review.",
        "citations": citations,
    }


NEW_CARDS = [
    # ─── 4A continued (8) ────────────────────────────────────────
    card("usconlaw-151",
         "Police, with probable cause to believe a vehicle contains contraband, search the vehicle without a warrant. Per Supreme Court doctrine, the search is most likely:",
         [("Unconstitutional without a warrant", False),
          ("Constitutional under the automobile exception", True),
          ("Constitutional only with consent", False),
          ("Constitutional only after arrest", False)],
         "Carroll v. United States (1925) established the automobile exception: vehicles' inherent mobility and reduced expectation of privacy permit warrantless searches if police have probable cause that the vehicle contains contraband or evidence of crime. The exception extends to the entire vehicle, including containers within (United States v. Ross). Mobility AND lower privacy expectation are both rationales.",
         [cite_scotus("Carroll v. United States, 267 U.S. 132 (1925)"),
          cite_scotus("United States v. Ross, 456 U.S. 798 (1982)")],
         tags="us-conlaw,fourth-amendment,automobile-exception", grammar_point="Carroll automobile exception"),
    card("usconlaw-152",
         "Police request consent to search a suspect's home without informing him he can refuse. The suspect agrees. Per Supreme Court doctrine, the consent is:",
         [("Per se invalid because the officer did not warn of the right to refuse", False),
          ("Valid if voluntary under the totality of circumstances", True),
          ("Valid only with written consent", False),
          ("Valid only with Miranda-style warnings", False)],
         "Schneckloth v. Bustamonte (1973) held that consent searches are valid if the consent was VOLUNTARY under the totality of circumstances. Officers need not affirmatively warn the subject of the right to refuse — though knowledge of that right is a factor in voluntariness. The Court rejected applying Miranda-style warnings to consent searches.",
         [cite_scotus("Schneckloth v. Bustamonte, 412 U.S. 218 (1973)"),
          cite_scotus("Florida v. Bostick, 501 U.S. 429 (1991)")],
         tags="us-conlaw,fourth-amendment,consent", grammar_point="Schneckloth voluntariness"),
    card("usconlaw-153",
         "An officer makes a traffic stop based on a minor traffic violation, intending the stop primarily to investigate suspected drug activity for which there is no probable cause. Per Supreme Court doctrine, the stop is:",
         [("Unconstitutional as pretextual", False),
          ("Constitutional if there was an objectively valid reason for the stop", True),
          ("Constitutional only if the officer was in uniform", False),
          ("Constitutional only with reasonable suspicion of drug activity", False)],
         "Whren v. United States (1996) held that traffic stops are constitutional if the officer had probable cause to believe a traffic violation occurred — regardless of the officer's subjective motivations. Subjective intent is irrelevant to Fourth Amendment validity if there is an objectively valid basis. Equal-protection challenges to selective enforcement remain available but require different proof.",
         [cite_scotus("Whren v. United States, 517 U.S. 806 (1996)")],
         tags="us-conlaw,fourth-amendment,pretext", grammar_point="Whren v. United States"),
    card("usconlaw-154",
         "An officer completes a traffic stop's purpose but extends the stop several minutes to await a drug-detection dog. Per Supreme Court doctrine, the extension is:",
         [("Constitutional if reasonable in scope", False),
          ("Unconstitutional absent independent reasonable suspicion", True),
          ("Constitutional under Whren", False),
          ("Constitutional with the driver's consent (presumed from silence)", False)],
         "Rodriguez v. United States (2015) held that a traffic stop becomes unlawful if it is prolonged beyond the time reasonably required to complete the stop's mission, absent INDEPENDENT reasonable suspicion of other criminal activity. A dog sniff that extends the stop, without separate reasonable suspicion of drug activity, violates the Fourth Amendment.",
         [cite_scotus("Rodriguez v. United States, 575 U.S. 348 (2015)"),
          cite_scotus("Illinois v. Caballes, 543 U.S. 405 (2005)")],
         tags="us-conlaw,fourth-amendment,traffic-stops", grammar_point="Rodriguez extension rule"),
    card("usconlaw-155",
         "An officer approaches a person on a public sidewalk and asks questions. The person is free to walk away. Per Supreme Court doctrine, the encounter is:",
         [("A 4A seizure requiring justification", False),
          ("Not a seizure — no Fourth Amendment implications until the officer's conduct constrains the person's liberty", True),
          ("Constitutional only with reasonable suspicion", False),
          ("Constitutional only with consent", False)],
         "United States v. Mendenhall (1980) established that a person is 'seized' for Fourth Amendment purposes only when, by means of physical force or show of authority, the officer has restrained the person's liberty such that a reasonable person would not feel free to leave. Mere approach + questioning is not a seizure. Bostick refined this for confined spaces (a reasonable person would feel free to terminate the encounter).",
         [cite_scotus("United States v. Mendenhall, 446 U.S. 544 (1980)"),
          cite_scotus("Florida v. Bostick, 501 U.S. 429 (1991)")],
         tags="us-conlaw,fourth-amendment,seizure", grammar_point="Mendenhall test"),
    card("usconlaw-156",
         "Police officers board a stationary bus and approach passengers individually, asking if they consent to a search. Per Supreme Court doctrine, the encounter is:",
         [("A per se seizure because the bus is a confined space", False),
          ("Not a seizure if a reasonable passenger would feel free to terminate the encounter", True),
          ("Unconstitutional without individualized suspicion", False),
          ("Constitutional only with consent obtained at the bus station", False)],
         "United States v. Drayton (2002) and Florida v. Bostick (1991) held that police-passenger encounters on buses are not Fourth Amendment seizures unless a reasonable passenger would feel UNABLE to terminate the encounter. The passenger's freedom-to-leave analysis adapts to the confined context: would a reasonable person feel free to refuse the request and decline to consent?",
         [cite_scotus("United States v. Drayton, 536 U.S. 194 (2002)"),
          cite_scotus("Florida v. Bostick, 501 U.S. 429 (1991)")],
         tags="us-conlaw,fourth-amendment,seizure", grammar_point="Drayton / Bostick — bus encounters"),
    card("usconlaw-157",
         "Police obtain evidence through an unconstitutional search and use that evidence to develop additional, otherwise-untainted leads. The defendant moves to suppress all evidence derived from the original illegality. Per Supreme Court doctrine, the additional evidence is:",
         [("Always admissible if obtained from independent investigation", False),
          ("Inadmissible as 'fruit of the poisonous tree' unless an exception applies", True),
          ("Always admissible if not obtained directly from the illegal search", False),
          ("Subject to harmless-error review only", False)],
         "Wong Sun v. United States (1963) established the 'fruit of the poisonous tree' doctrine: evidence derived from an unconstitutional search is generally inadmissible, but exceptions include (1) independent source, (2) inevitable discovery, (3) attenuation. The exclusionary rule extends to indirect derivative evidence to deter Fourth Amendment violations.",
         [cite_scotus("Wong Sun v. United States, 371 U.S. 471 (1963)"),
          cite_scotus("Murray v. United States, 487 U.S. 533 (1988)")],
         tags="us-conlaw,fourth-amendment,exclusionary-rule", grammar_point="Wong Sun / fruit of poisonous tree"),
    card("usconlaw-158",
         "Police make an unconstitutional entry to a home, observe contraband, then later return with a valid warrant based on independent information not derived from the entry. Per Supreme Court doctrine, evidence seized under the warrant is:",
         [("Always inadmissible as fruit of the poisonous tree", False),
          ("Admissible under the independent-source doctrine if the warrant was based on lawfully-obtained information", True),
          ("Admissible only if the entry was made in good faith", False),
          ("Admissible only with attenuation showing", False)],
         "Murray v. United States (1988) clarified the independent-source doctrine: even when officers initially make an unconstitutional entry, evidence later seized under a warrant supported by an independent lawful source is admissible. The key is that the warrant's probable-cause basis must not derive from the unconstitutional entry.",
         [cite_scotus("Murray v. United States, 487 U.S. 533 (1988)"),
          cite_scotus("Segura v. United States, 468 U.S. 796 (1984)")],
         tags="us-conlaw,fourth-amendment,independent-source", grammar_point="Murray v. United States"),
    # ─── 5A continued (3) ────────────────────────────────────────
    card("usconlaw-159",
         "Police lawfully stop a person they suspect of involvement in a crime and demand his name. The state has a stop-and-identify statute. Per Supreme Court doctrine, the demand is:",
         [("Per se unconstitutional under the Fourth and Fifth Amendments", False),
          ("Constitutional if the stop was lawful and the identification statute is reasonable", True),
          ("Constitutional only with Miranda warnings", False),
          ("Constitutional only after arrest", False)],
         "Hiibel v. Sixth Judicial District Court of Nevada (2004) upheld Nevada's stop-and-identify statute requiring detained persons (during a lawful Terry stop) to identify themselves. The Court held the statute does not violate the Fourth Amendment (request was during lawful stop) or the Fifth Amendment self-incrimination privilege (mere identification is not testimonial in this context).",
         [cite_scotus("Hiibel v. Sixth Judicial District Court of Nevada, 542 U.S. 177 (2004)"),
          cite_scotus("Terry v. Ohio, 392 U.S. 1 (1968)")],
         tags="us-conlaw,fifth-amendment,stop-and-identify", grammar_point="Hiibel"),
    card("usconlaw-160",
         "During a non-custodial police interview, the suspect remains silent in response to certain questions but does not invoke his Fifth Amendment privilege. The prosecution offers the silence as substantive evidence of guilt. Per Supreme Court doctrine, the silence is most likely:",
         [("Inadmissible because silence cannot be used against a defendant", False),
          ("Admissible because the suspect did not expressly invoke the privilege in a non-custodial setting", True),
          ("Inadmissible under Miranda v. Arizona", False),
          ("Subject to harmless-error review only", False)],
         "Salinas v. Texas (2013) held that a defendant's pre-arrest, pre-Miranda silence in a non-custodial interview is admissible as substantive evidence of guilt UNLESS the defendant expressly invokes the Fifth Amendment privilege. Miranda's protections kick in only at custodial interrogation; pre-Miranda silence in voluntary encounters does not automatically invoke the privilege.",
         [cite_scotus("Salinas v. Texas, 570 U.S. 178 (2013)")],
         tags="us-conlaw,fifth-amendment,silence", grammar_point="Salinas v. Texas"),
    card("usconlaw-161",
         "Police give Miranda warnings to a suspect who then sits silently for nearly 3 hours of questioning before finally answering one question. Per Supreme Court doctrine, the answer is most likely:",
         [("Inadmissible because the suspect's prolonged silence invoked his Miranda right to remain silent", False),
          ("Admissible because the suspect did not unambiguously invoke his right to remain silent", True),
          ("Inadmissible under the Sixth Amendment", False),
          ("Admissible only with re-Mirandizing", False)],
         "Berghuis v. Thompkins (2010) held that to invoke the Miranda right to remain silent, a suspect must do so UNAMBIGUOUSLY. Mere silence — even prolonged — does not invoke the right; without an unambiguous invocation, police may continue questioning. A subsequent statement can be admissible. This parallels Davis v. United States (1994) for unambiguous invocation of counsel.",
         [cite_scotus("Berghuis v. Thompkins, 560 U.S. 370 (2010)"),
          cite_scotus("Davis v. United States, 512 U.S. 452 (1994)")],
         tags="us-conlaw,fifth-amendment,miranda", grammar_point="Berghuis v. Thompkins"),
    # ─── 6A speedy/jury (3) ──────────────────────────────────────
    card("usconlaw-162",
         "A criminal defendant's trial is delayed for 5 years between indictment and trial. He alleges a Sixth Amendment speedy-trial violation. Per Supreme Court doctrine, the analysis applies:",
         [("A bright-line one-year-from-indictment rule", False),
          ("The Barker v. Wingo four-factor balancing test", True),
          ("Strict scrutiny", False),
          ("The Mathews v. Eldridge test", False)],
         "Barker v. Wingo (1972) established the four-factor balancing test for Sixth Amendment speedy-trial claims: (1) length of delay (must be presumptively prejudicial to trigger analysis); (2) reason for the delay (deliberate? negligent? justified?); (3) defendant's assertion of the right; (4) prejudice to the defendant. No factor is dispositive.",
         [cite_scotus("Barker v. Wingo, 407 U.S. 514 (1972)"),
          cite_scotus("Doggett v. United States, 505 U.S. 647 (1992)")],
         tags="us-conlaw,sixth-amendment,speedy-trial", grammar_point="Barker v. Wingo"),
    card("usconlaw-163",
         "A criminal defendant is arrested 8.5 years after indictment. Most of the delay is due to government negligence; the defendant did not know of the indictment. Per Supreme Court doctrine, the speedy-trial claim is:",
         [("Defeated because the defendant did not assert his rights", False),
          ("Sustained — extreme government-attributable delay creates presumed prejudice", True),
          ("Defeated because no actual prejudice was shown", False),
          ("Subject to harmless-error review", False)],
         "Doggett v. United States (1992) held that extreme government-attributable delay (8.5 years of negligent post-indictment delay) supports a Sixth Amendment violation even without proof of specific prejudice. Presumptive prejudice from extreme delay outweighs the absence of demonstrated harm or the defendant's late assertion of the right (he didn't know of the indictment).",
         [cite_scotus("Doggett v. United States, 505 U.S. 647 (1992)"),
          cite_scotus("Barker v. Wingo, 407 U.S. 514 (1972)")],
         tags="us-conlaw,sixth-amendment,speedy-trial", grammar_point="Doggett v. United States"),
    card("usconlaw-164",
         "At a criminal trial, the prosecution offers a forensic analyst's lab report as evidence of the substance's identity, without calling the analyst. Per Supreme Court doctrine, the report is most likely:",
         [("Admissible under the business-records exception", False),
          ("Inadmissible under the Confrontation Clause unless the analyst testifies and is cross-examinable", True),
          ("Admissible if the report is reliable", False),
          ("Admissible only if the substance is non-perishable", False)],
         "Bullcoming v. New Mexico (2011) and Melendez-Diaz v. Massachusetts (2009) held that forensic lab reports are TESTIMONIAL hearsay subject to the Confrontation Clause. The actual analyst (not a substitute) must testify and be subject to cross-examination, unless the analyst is unavailable AND the defendant had a prior opportunity to cross-examine. Williams v. Illinois (2012) created some confusion via fragmented holdings.",
         [cite_scotus("Bullcoming v. New Mexico, 564 U.S. 647 (2011)"),
          cite_scotus("Melendez-Diaz v. Massachusetts, 557 U.S. 305 (2009)")],
         tags="us-conlaw,sixth-amendment,confrontation", grammar_point="Bullcoming / Melendez-Diaz"),
    # ─── 8A continued (3) ────────────────────────────────────────
    card("usconlaw-165",
         "A state criminalizes the status of being addicted to narcotics, regardless of any conduct. Per Supreme Court doctrine, the law is most likely:",
         [("Constitutional under the state's police power", False),
          ("Unconstitutional under the Eighth Amendment as criminalizing status", True),
          ("Constitutional with treatment alternatives", False),
          ("Subject to rational basis review", False)],
         "Robinson v. California (1962) struck down a California law criminalizing the STATUS of being addicted to narcotics. The Court held that punishing a person for a status (rather than conduct) violates the Eighth Amendment. Powell v. Texas (1968) limited Robinson, allowing punishment for related conduct (public intoxication) even if the conduct is compelled by the status.",
         [cite_scotus("Robinson v. California, 370 U.S. 660 (1962)"),
          cite_scotus("Powell v. Texas, 392 U.S. 514 (1968)")],
         tags="us-conlaw,eighth-amendment,status-crimes", grammar_point="Robinson v. California"),
    card("usconlaw-166",
         "Congress strips a citizen of U.S. nationality as punishment for desertion in wartime. Per Supreme Court doctrine, the punishment is most likely:",
         [("Constitutional under Congress's war powers", False),
          ("Unconstitutional under the Eighth Amendment", True),
          ("Constitutional under the Necessary and Proper Clause", False),
          ("Subject to rational basis review", False)],
         "Trop v. Dulles (1958) struck down denationalization as punishment for desertion. The Court held that loss of citizenship is 'a fate forbidden by the principle of civilized treatment guaranteed by the Eighth Amendment.' Chief Justice Warren articulated the 'evolving standards of decency' framework that has shaped modern Eighth Amendment doctrine.",
         [cite_scotus("Trop v. Dulles, 356 U.S. 86 (1958)")],
         tags="us-conlaw,eighth-amendment", grammar_point="Trop v. Dulles"),
    card("usconlaw-167",
         "A state imposes a sentence of life without parole on a juvenile (under 18) for a non-homicide offense. Per Supreme Court doctrine, the sentence is most likely:",
         [("Constitutional because non-homicide does not eliminate sentencing options", False),
          ("Unconstitutional under the Eighth Amendment for non-homicide juveniles", True),
          ("Constitutional with discretionary sentencing", False),
          ("Subject to harmless-error review", False)],
         "Graham v. Florida (2010) held that the Eighth Amendment categorically prohibits LWOP for juveniles in NON-HOMICIDE cases. The Court relied on (1) diminished culpability of juveniles (Roper) and (2) the categorical nature of life-without-parole as the most serious non-death sentence. Miller v. Alabama (2012) extended this approach to mandatory LWOP for juvenile homicide offenses.",
         [cite_scotus("Graham v. Florida, 560 U.S. 48 (2010)"),
          cite_scotus("Miller v. Alabama, 567 U.S. 460 (2012)")],
         tags="us-conlaw,eighth-amendment,juveniles", grammar_point="Graham v. Florida"),
    # ─── Habeas / Detention (3) ──────────────────────────────────
    card("usconlaw-168",
         "Foreign nationals detained at Guantanamo Bay seek habeas review in federal court. Per Supreme Court doctrine, the federal habeas statute:",
         [("Does not extend to non-citizens detained outside U.S. sovereign territory", False),
          ("Extends to detainees at Guantanamo because the U.S. exercises complete jurisdiction and control there", True),
          ("Applies only after a military commission determines status", False),
          ("Is preempted by AUMF", False)],
         "Rasul v. Bush (2004) held that the federal habeas statute (28 U.S.C. § 2241) extends to non-citizen detainees at Guantanamo Bay, where the U.S. exercises complete jurisdiction and control. Boumediene v. Bush (2008) later held that the SUSPENSION CLAUSE itself extends to Guantanamo detainees, and the Detainee Treatment Act's habeas-substitute was inadequate.",
         [cite_scotus("Rasul v. Bush, 542 U.S. 466 (2004)"),
          cite_scotus("Boumediene v. Bush, 553 U.S. 723 (2008)")],
         tags="us-conlaw,habeas,detention", grammar_point="Rasul v. Bush"),
    card("usconlaw-169",
         "A U.S. citizen captured abroad is detained by the military as an 'enemy combatant' without formal charges. Per Supreme Court doctrine, the citizen is entitled to:",
         [("No process because the President's war powers are absolute", False),
          ("Notice of the factual basis and an opportunity to rebut before a neutral decision-maker", True),
          ("A full criminal trial", False),
          ("Immediate release", False)],
         "Hamdi v. Rumsfeld (2004) held that a U.S. citizen detained as an enemy combatant has due process rights to (1) notice of the factual basis for classification AND (2) a fair opportunity to rebut before a neutral decision-maker. The military may not detain citizens indefinitely without process. Justice O'Connor's plurality applied Mathews v. Eldridge balancing.",
         [cite_scotus("Hamdi v. Rumsfeld, 542 U.S. 507 (2004)"),
          cite_scotus("Mathews v. Eldridge, 424 U.S. 319 (1976)")],
         tags="us-conlaw,due-process,detention", grammar_point="Hamdi v. Rumsfeld"),
    card("usconlaw-170",
         "Congress passes legislation purporting to strip federal courts of habeas jurisdiction over Guantanamo detainees and substituting limited military review. Per Supreme Court doctrine, the legislation is most likely:",
         [("Constitutional under Congress's Article I § 8 power to create and abolish lower courts", False),
          ("Unconstitutional under the Suspension Clause unless the substitute provides equivalent protection", True),
          ("Constitutional under Article I § 9 cl. 2 in time of war", False),
          ("Subject to rational basis review", False)],
         "Boumediene v. Bush (2008) held that the Suspension Clause (Art. I § 9 cl. 2) extends to Guantanamo detainees, and the Detainee Treatment Act's substitute review procedures were not an adequate substitute for habeas. Congress can suspend habeas only 'when in Cases of Rebellion or Invasion the public Safety may require it' — and substitutes for habeas must provide equivalent procedural protection.",
         [cite_scotus("Boumediene v. Bush, 553 U.S. 723 (2008)")],
         tags="us-conlaw,habeas,suspension-clause", grammar_point="Boumediene v. Bush"),
    # ─── Takings (5) ─────────────────────────────────────────────
    card("usconlaw-171",
         "A city restricts the height of new construction, reducing the economic value of a developer's planned project but not eliminating all economic use. Per Supreme Court doctrine, the regulation is analyzed under:",
         [("The per se rule for physical takings", False),
          ("The Penn Central three-factor balancing test for regulatory takings", True),
          ("Strict scrutiny", False),
          ("Rational basis review", False)],
         "Penn Central Transportation Co. v. New York City (1978) is the foundational regulatory-takings case. The three-factor analysis: (1) economic impact on the claimant; (2) interference with reasonable investment-backed expectations; (3) character of the government action (e.g., physical invasion vs. general regulatory program). The Court upheld Penn Central historic-preservation restrictions on Grand Central Terminal.",
         [cite_scotus("Penn Central Transp. Co. v. New York City, 438 U.S. 104 (1978)")],
         tags="us-conlaw,5a,takings,regulatory", grammar_point="Penn Central test"),
    card("usconlaw-172",
         "A city uses eminent domain to transfer private property from one owner to another for a comprehensive economic-development plan. Per Supreme Court doctrine, the taking is:",
         [("Per se unconstitutional as not a 'public use'", False),
          ("Constitutional if the taking serves a 'public purpose' even if the property is transferred to another private party", True),
          ("Constitutional only if the new owner is a public utility", False),
          ("Subject to strict scrutiny", False)],
         "Kelo v. City of New London (2005) upheld eminent-domain transfers from one private party to another as part of a comprehensive economic-development plan. The Court interpreted 'public use' broadly as 'public purpose,' deferring to legislative judgments about economic-development needs. Many states subsequently restricted eminent domain by state statute or constitution in response.",
         [cite_scotus("Kelo v. City of New London, 545 U.S. 469 (2005)")],
         tags="us-conlaw,5a,takings,public-use", grammar_point="Kelo v. New London"),
    card("usconlaw-173",
         "A state regulation deprives a property owner of ALL economically beneficial use of his land. Per Supreme Court doctrine, the regulation is most likely:",
         [("Constitutional if rationally related to public welfare", False),
          ("A per se taking unless the regulation merely codifies common-law nuisance principles", True),
          ("Subject to Penn Central balancing", False),
          ("Subject to rational basis review", False)],
         "Lucas v. South Carolina Coastal Council (1992) established a per se takings rule when a regulation deprives the owner of all economically beneficial use, UNLESS the regulation merely codifies background principles of state property law (e.g., common-law nuisance). The Court found beachfront-construction prohibitions worked a total-deprivation taking.",
         [cite_scotus("Lucas v. South Carolina Coastal Council, 505 U.S. 1003 (1992)")],
         tags="us-conlaw,5a,takings,total-deprivation", grammar_point="Lucas v. SC Coastal Council"),
    card("usconlaw-174",
         "An owner holds two adjacent lots; a state regulation severely restricts use of one but not the other. The owner argues the analysis should focus on the restricted lot alone. Per Supreme Court doctrine, the relevant parcel is determined by:",
         [("The owner's preferred parcel definition", False),
          ("A multi-factor analysis considering treatment under state law, physical characteristics, and economic prospects", True),
          ("Whichever parcel is most affected", False),
          ("The smaller of the two lots", False)],
         "Murr v. Wisconsin (2017) held that the 'relevant parcel' for regulatory-takings analysis is determined by a multi-factor inquiry: state law treatment, physical characteristics of the property, and reasonable expectations regarding the parcel as a whole. The Court rejected both lot-line-based formalism and pure 'parcel-as-a-whole' approaches.",
         [cite_scotus("Murr v. Wisconsin, 582 U.S. 383 (2017)")],
         tags="us-conlaw,5a,takings,relevant-parcel", grammar_point="Murr v. Wisconsin"),
    card("usconlaw-175",
         "A state regulation grants union organizers a right to enter agricultural employers' property to communicate with workers. Per recent Supreme Court doctrine, the regulation is most likely:",
         [("Constitutional under the state's labor-relations interest", False),
          ("A per se physical taking requiring just compensation", True),
          ("Constitutional under Penn Central balancing", False),
          ("Subject to rational basis review", False)],
         "Cedar Point Nursery v. Hassid (2021) held that California's regulation granting union organizers access to agricultural employers' property was a PER SE PHYSICAL TAKING. The Court treated even a temporary, intermittent right of physical access as a categorical taking, not subject to Penn Central balancing. The right to exclude is a fundamental property right.",
         [cite_scotus("Cedar Point Nursery v. Hassid, 594 U.S. 139 (2021)")],
         tags="us-conlaw,5a,takings,physical", grammar_point="Cedar Point Nursery"),
    # ─── Standing — recent (3) ───────────────────────────────────
    card("usconlaw-176",
         "Massachusetts sues EPA alleging the agency failed to regulate greenhouse-gas emissions. EPA challenges the state's standing. Per Supreme Court doctrine, the state most likely:",
         [("Lacks standing because climate harms are too generalized", False),
          ("Has standing as a SOVEREIGN with quasi-sovereign interests, accorded special solicitude", True),
          ("Has standing only if it shows traditional Article III injury", False),
          ("Lacks standing under the political question doctrine", False)],
         "Massachusetts v. EPA (2007) held that the state had Article III standing to challenge EPA's denial of a rulemaking petition on greenhouse-gas emissions. States, as sovereigns with quasi-sovereign interests in their territory and citizens, are accorded SPECIAL SOLICITUDE in standing analysis. The Court found injury (loss of coastal land), causation, and redressability.",
         [cite_scotus("Massachusetts v. EPA, 549 U.S. 497 (2007)")],
         tags="us-conlaw,standing,states", grammar_point="Massachusetts v. EPA"),
    card("usconlaw-177",
         "A class action challenges a credit-reporting agency's inaccurate alerts. Many class members never had their inaccurate reports disseminated to third parties. Per recent Supreme Court doctrine, those uninjured class members:",
         [("Have standing because the statutory violation alone constitutes injury", False),
          ("Lack Article III standing — concrete harm requires more than statutory violation alone", True),
          ("Have standing under FCRA", False),
          ("Have standing only as named plaintiffs", False)],
         "TransUnion LLC v. Ramirez (2021) held that statutory violations alone do not confer Article III standing; the plaintiff must show CONCRETE harm. For class members whose inaccurate reports were never disseminated to third parties, no concrete reputational harm occurred. The Court tightened Spokeo's concrete-injury requirement, particularly for statutory standing claims.",
         [cite_scotus("TransUnion LLC v. Ramirez, 594 U.S. 413 (2021)"),
          cite_scotus("Spokeo, Inc. v. Robins, 578 U.S. 330 (2016)")],
         tags="us-conlaw,standing,concrete-injury", grammar_point="TransUnion v. Ramirez"),
    card("usconlaw-178",
         "A state sues to block the federal government's discretionary enforcement priorities, alleging the policies create downstream administrative burdens. Per recent Supreme Court doctrine, the state's standing is:",
         [("Strong because states have special solicitude under Massachusetts v. EPA", False),
          ("Doubtful where the state's claimed injury depends on the federal government's choice not to enforce", True),
          ("Automatic under the parens patriae doctrine", False),
          ("Established by general taxpayer standing", False)],
         "United States v. Texas (2023) held that Texas and Louisiana lacked Article III standing to challenge the federal immigration-enforcement policy guidelines. The Court emphasized that NON-ENFORCEMENT challenges (challenges to the executive's enforcement discretion) face significant standing hurdles, particularly where the alleged injury is downstream of the executive's discretionary choice not to act.",
         [cite_scotus("United States v. Texas, 599 U.S. 670 (2023)")],
         tags="us-conlaw,standing,states", grammar_point="US v. Texas (2023) — non-enforcement standing"),
    # ─── Press / Access (2) ──────────────────────────────────────
    card("usconlaw-179",
         "A reporter is subpoenaed to testify before a grand jury about confidential sources. He invokes a 1A privilege to refuse. Per Supreme Court doctrine, the privilege:",
         [("Exists as a robust constitutional shield for journalists", False),
          ("Does not exist under the First Amendment for federal grand jury subpoenas", True),
          ("Applies only in civil cases", False),
          ("Applies after attempted use of less-intrusive means", False)],
         "Branzburg v. Hayes (1972) held that the First Amendment does not shield journalists from federal grand-jury subpoenas seeking confidential-source information. Justice Powell's concurrence (the operative narrowing) suggested case-by-case balancing. Many states and federal circuits have adopted shield laws or limited common-law privileges; no robust federal constitutional privilege exists.",
         [cite_scotus("Branzburg v. Hayes, 408 U.S. 665 (1972)")],
         tags="us-conlaw,first-amendment,press-privilege", grammar_point="Branzburg v. Hayes"),
    card("usconlaw-180",
         "A trial court closes a criminal trial to the press and public. Per Supreme Court doctrine, the closure is most likely:",
         [("Per se constitutional under the trial court's discretion", False),
          ("Unconstitutional unless narrowly tailored to a compelling government interest", True),
          ("Subject to rational basis review", False),
          ("Constitutional only with the defendant's consent", False)],
         "Richmond Newspapers v. Virginia (1980) held that the public and press have a First Amendment right of access to criminal trials. Closure orders must be narrowly tailored to serve a compelling interest (e.g., witness safety, juvenile sensitivity). Press-Enterprise (I & II) extended this access right to voir dire and preliminary hearings.",
         [cite_scotus("Richmond Newspapers v. Virginia, 448 U.S. 555 (1980)"),
          cite_scotus("Press-Enterprise Co. v. Superior Court, 478 U.S. 1 (1986)")],
         tags="us-conlaw,first-amendment,press-access", grammar_point="Richmond Newspapers"),
    # ─── Affirmative action history (3) ──────────────────────────
    card("usconlaw-181",
         "A state medical school reserves a fixed number of admission slots for racial minorities in a quota system. Per Supreme Court doctrine, the program is most likely:",
         [("Constitutional under intermediate scrutiny", False),
          ("Unconstitutional as a fixed quota; race may be a 'plus' factor but not a quota", True),
          ("Constitutional under the Necessary and Proper Clause", False),
          ("Subject to rational basis review", False)],
         "Regents of UC v. Bakke (1978) struck down UC Davis's quota system but Justice Powell's controlling opinion permitted race as a 'plus' factor in admissions to serve diversity. This narrow rationale survived for decades — Grutter v. Bollinger (2003) reaffirmed it for graduate admissions; Gratz v. Bollinger (2003) struck down a mechanical points system. SFFA (2023) effectively ended race-conscious admissions.",
         [cite_scotus("Regents of UC v. Bakke, 438 U.S. 265 (1978)"),
          cite_scotus("Students for Fair Admissions v. Harvard, 600 U.S. 181 (2023)")],
         tags="us-conlaw,equal-protection,affirmative-action", grammar_point="Bakke / quotas"),
    card("usconlaw-182",
         "A state university uses a points system that automatically awards 20 points (out of 150) to applicants from underrepresented racial minorities. Per Supreme Court doctrine, the system is most likely:",
         [("Constitutional as race being merely a 'plus' factor", False),
          ("Unconstitutional because it functions as a near-quota for race", True),
          ("Constitutional under intermediate scrutiny", False),
          ("Constitutional under educational deference", False)],
         "Gratz v. Bollinger (2003) struck down University of Michigan's UNDERGRADUATE point-system, which awarded 20 points to underrepresented minority applicants out of a 100-point admission threshold. The mechanical, decisive impact of race per applicant violated narrow tailoring. Grutter (2003) upheld Michigan's law-school individualized-review system the same day.",
         [cite_scotus("Gratz v. Bollinger, 539 U.S. 244 (2003)"),
          cite_scotus("Grutter v. Bollinger, 539 U.S. 306 (2003)")],
         tags="us-conlaw,equal-protection,affirmative-action", grammar_point="Gratz v. Bollinger"),
    card("usconlaw-183",
         "A challenge to a public university's race-conscious admissions program asserts that strict scrutiny was applied with insufficient rigor. Per Supreme Court doctrine, the appropriate analysis:",
         [("Defers to the university's good-faith determination", False),
          ("Requires NO deference and rigorous, searching judicial review", True),
          ("Applies intermediate scrutiny", False),
          ("Applies rational basis review", False)],
         "Fisher v. University of Texas (Fisher I, 2013) held that lower courts had given improper deference to the university; strict scrutiny requires NO deference on whether race-conscious admissions are narrowly tailored. The university bears the burden of demonstrating necessity. Fisher II (2016) ultimately upheld UT's program but on a thin record. SFFA (2023) effectively ended this line.",
         [cite_scotus("Fisher v. University of Texas, 570 U.S. 297 (2013) (Fisher I)"),
          cite_scotus("Fisher v. University of Texas, 579 U.S. 365 (2016) (Fisher II)"),
          cite_lr("Texas Law Review — Fisher / SFFA scholarship")],
         tags="us-conlaw,equal-protection,affirmative-action", grammar_point="Fisher v. UT — strict scrutiny rigor"),
    # ─── Race-conscious districting (3) ─────────────────────────
    card("usconlaw-184",
         "A state's voting district has a bizarre, irregular shape that can only be explained by attempting to gather minority voters into one district. Per Supreme Court doctrine, the district is reviewed under:",
         [("Rational basis review", False),
          ("Strict scrutiny because it constitutes a racial classification", True),
          ("Intermediate scrutiny", False),
          ("The political question doctrine", False)],
         "Shaw v. Reno (1993) held that race-conscious legislative districting that subordinates traditional districting principles to race triggers strict scrutiny under the Equal Protection Clause. Bizarre, irregular shapes that can only be explained by race signal racial gerrymandering. Even majority-minority districts justified by VRA compliance may face strict scrutiny.",
         [cite_scotus("Shaw v. Reno, 509 U.S. 630 (1993)"),
          cite_scotus("Miller v. Johnson, 515 U.S. 900 (1995)")],
         tags="us-conlaw,equal-protection,redistricting", grammar_point="Shaw v. Reno"),
    card("usconlaw-185",
         "A challenger to a redistricting plan must show that race was the PREDOMINANT factor in drawing district lines. Per Supreme Court doctrine, this burden is established by:",
         [("Showing any consideration of race", False),
          ("Showing that race subordinated other traditional districting criteria", True),
          ("Showing reduced minority voting strength", False),
          ("Showing intent to discriminate", False)],
         "Miller v. Johnson (1995) refined Shaw v. Reno: the challenger must show that RACE was the PREDOMINANT factor — that race subordinated traditional, race-neutral districting principles (compactness, contiguity, respect for political subdivisions, communities of interest). Mere consideration of race is not enough; it must be the predominant motivator.",
         [cite_scotus("Miller v. Johnson, 515 U.S. 900 (1995)"),
          cite_scotus("Bush v. Vera, 517 U.S. 952 (1996)")],
         tags="us-conlaw,equal-protection,redistricting", grammar_point="Miller v. Johnson"),
    card("usconlaw-186",
         "A state defends a race-conscious district as motivated by partisan considerations rather than race. Per recent Supreme Court doctrine, the analysis must:",
         [("Defer to the state's race-neutral explanation", False),
          ("Disentangle race and politics — when they substantially correlate, careful inquiry is required", True),
          ("Apply rational basis if politics is plausible", False),
          ("Defer under the political question doctrine", False)],
         "Cooper v. Harris (2017) emphasized that courts must carefully disentangle race-based and politics-based districting motivations when they correlate. The state may not use 'partisan motivation' as a pretextual cover for racial gerrymandering. The challenger bears the burden of showing race-as-predominant, but courts apply rigorous scrutiny when race and politics align.",
         [cite_scotus("Cooper v. Harris, 581 U.S. 285 (2017)"),
          cite_scotus("Bethune-Hill v. Virginia State Bd. of Elections, 580 U.S. 178 (2017)")],
         tags="us-conlaw,equal-protection,redistricting", grammar_point="Cooper v. Harris"),
    # ─── Religion — more (3) ─────────────────────────────────────
    card("usconlaw-187",
         "A city erects a Christmas display on public property that includes a nativity scene alongside secular decorations (Santa, reindeer, candy canes). Per historical Supreme Court doctrine (now superseded by historical-practices), the display was analyzed under:",
         [("Strict scrutiny", False),
          ("The Lemon test, with attention to context and broader holiday celebration", True),
          ("Rational basis review", False),
          ("Per se prohibited as religious endorsement", False)],
         "Lynch v. Donnelly (1983) upheld a city's nativity-scene display in the context of broader holiday decorations. Justice O'Connor's concurrence introduced the 'endorsement test' — would a reasonable observer perceive the display as endorsing religion? Subsequent cases (Allegheny County, McCreary, Van Orden) developed context-specific analysis. Kennedy v. Bremerton (2022) shifted to historical-practices analysis.",
         [cite_scotus("Lynch v. Donnelly, 465 U.S. 668 (1983)"),
          cite_scotus("County of Allegheny v. ACLU, 492 U.S. 573 (1989)")],
         tags="us-conlaw,first-amendment,establishment", grammar_point="Lynch v. Donnelly (history)"),
    card("usconlaw-188",
         "A county courthouse displays the Ten Commandments alongside other historical legal documents. The display was added recently and is positioned to highlight the religious character. Per Supreme Court doctrine (pre-Bremerton), the display was analyzed under:",
         [("Strict scrutiny", False),
          ("The Lemon test with attention to the display's purpose and context", True),
          ("Rational basis review", False),
          ("Per se permitted under Marsh v. Chambers", False)],
         "McCreary County v. ACLU (2005) struck down a Ten Commandments display in a Kentucky courthouse, finding the county's history of religious displays demonstrated a religious purpose. Same day, Van Orden v. Perry (2005) upheld a Ten Commandments monument on the Texas Capitol grounds because of its long history and surrounding secular monuments. Context and history mattered; Kennedy v. Bremerton (2022) now formalizes historical-practices analysis.",
         [cite_scotus("McCreary County v. ACLU, 545 U.S. 844 (2005)"),
          cite_scotus("Van Orden v. Perry, 545 U.S. 677 (2005)")],
         tags="us-conlaw,first-amendment,establishment", grammar_point="McCreary County / Van Orden"),
    card("usconlaw-189",
         "A state-maintained Ten Commandments monument has stood for over 40 years on the grounds of the state capitol, surrounded by other monuments. Per Supreme Court doctrine, the monument is most likely:",
         [("Unconstitutional as religious endorsement", False),
          ("Constitutional given its historical context and surrounding secular monuments", True),
          ("Subject to strict scrutiny", False),
          ("Constitutional only if non-sectarian", False)],
         "Van Orden v. Perry (2005) upheld the Texas Capitol grounds Ten Commandments monument as part of a broader secular display reflecting Texas's heritage. Decided same-day as McCreary, Van Orden emphasized history, surrounding context, and longstanding tolerance. Kennedy v. Bremerton (2022) now formalizes a historical-practices approach that aligns with Van Orden's reasoning.",
         [cite_scotus("Van Orden v. Perry, 545 U.S. 677 (2005)"),
          cite_scotus("Kennedy v. Bremerton School District, 597 U.S. 507 (2022)")],
         tags="us-conlaw,first-amendment,establishment", grammar_point="Van Orden v. Perry"),
    # ─── Federalism / structural (3) ────────────────────────────
    card("usconlaw-190",
         "Congress enacts federal civil-commitment statute permitting indefinite detention of mentally ill federal inmates after their criminal sentences. Per Supreme Court doctrine, the statute is:",
         [("Unconstitutional as exceeding enumerated powers", False),
          ("Constitutional under the Necessary and Proper Clause", True),
          ("Constitutional under the Spending Clause", False),
          ("Subject to strict scrutiny", False)],
         "United States v. Comstock (2010) upheld the federal civil-commitment statute (Adam Walsh Act § 4248) under the Necessary and Proper Clause. The Court applied a five-factor analysis: (1) breadth of N&P; (2) historical federal practice; (3) sound rationale linking the statute to enumerated powers; (4) accommodation of state interests; (5) the statute's limited scope.",
         [cite_scotus("United States v. Comstock, 560 U.S. 126 (2010)")],
         tags="us-conlaw,federalism,necessary-and-proper", grammar_point="US v. Comstock"),
    card("usconlaw-191",
         "After Brown v. Board of Education, a state argues it is not bound by Supreme Court decisions interpreting the U.S. Constitution. Per Supreme Court doctrine, the state's position is:",
         [("Constitutional under federalism principles", False),
          ("Unconstitutional — Supreme Court constitutional interpretations bind all states under judicial supremacy", True),
          ("Subject to political-question analysis", False),
          ("Constitutional only as to dicta", False)],
         "Cooper v. Aaron (1958) emphatically rejected Arkansas's claim of immunity from desegregation orders. The unanimous opinion (signed individually by all nine Justices) reaffirmed Marbury v. Madison (1803): Supreme Court constitutional interpretations are 'the supreme law of the land' binding all states. Judicial supremacy in constitutional interpretation is foundational to American federalism.",
         [cite_scotus("Cooper v. Aaron, 358 U.S. 1 (1958)"),
          cite_scotus("Marbury v. Madison, 5 U.S. (1 Cranch) 137 (1803)")],
         tags="us-conlaw,federalism,judicial-supremacy", grammar_point="Cooper v. Aaron"),
    card("usconlaw-192",
         "A federal taxpayer sues to challenge a federal expenditure as unconstitutional, asserting standing solely as a taxpayer. Per the older but still-cited Supreme Court doctrine, the suit is:",
         [("Permitted under the public-citizen standing doctrine", False),
          ("Barred under Frothingham as a generalized grievance", True),
          ("Permitted only with state authorization", False),
          ("Subject to rational basis review", False)],
         "Frothingham v. Mellon (1923) (companion case Massachusetts v. Mellon) established the foundational rule against general taxpayer standing. The Court held that a taxpayer's interest in the federal treasury is too generalized and remote to support Article III standing. Flast v. Cohen (1968) carved a narrow EC exception, since narrowed by Hein and Winn.",
         [cite_scotus("Frothingham v. Mellon (Massachusetts v. Mellon), 262 U.S. 447 (1923)"),
          cite_scotus("Flast v. Cohen, 392 U.S. 83 (1968)")],
         tags="us-conlaw,standing,taxpayer", grammar_point="Frothingham v. Mellon"),
    # ─── 1A speech (4) ──────────────────────────────────────────
    card("usconlaw-193",
         "During wartime, a defendant distributes leaflets urging resistance to the draft. Per the historical (now superseded) Supreme Court doctrine, the speech could be punished under:",
         [("The Brandenburg incitement test", False),
          ("The 'clear and present danger' test (now displaced by Brandenburg)", True),
          ("The fighting-words doctrine", False),
          ("Strict scrutiny", False)],
         "Schenck v. United States (1919) introduced the 'clear and present danger' test, used to uphold convictions for anti-draft pamphleting during WWI. Justice Holmes's reasoning: 'falsely shouting fire in a theatre.' This test was the dominant speech doctrine until Brandenburg v. Ohio (1969) replaced it with the more speech-protective 'directed to and likely to produce imminent lawless action' standard.",
         [cite_scotus("Schenck v. United States, 249 U.S. 47 (1919)"),
          cite_scotus("Brandenburg v. Ohio, 395 U.S. 444 (1969)")],
         tags="us-conlaw,first-amendment,history", grammar_point="Schenck — clear and present danger (history)"),
    card("usconlaw-194",
         "A state criminalizes the sale of violent video games to minors. Per Supreme Court doctrine, the law is most likely:",
         [("Constitutional under the state's interest in protecting minors", False),
          ("Unconstitutional under strict scrutiny — violence is not unprotected speech", True),
          ("Constitutional under intermediate scrutiny", False),
          ("Constitutional under the obscenity exception", False)],
         "Brown v. Entertainment Merchants Ass'n (2011) struck down a California law restricting violent video-game sales to minors. The Court held that violence is NOT a category of unprotected speech (unlike obscenity). The state cannot create new categories of unprotected speech; strict scrutiny applied and the state failed to show narrow tailoring.",
         [cite_scotus("Brown v. Entertainment Merchants Ass'n, 564 U.S. 786 (2011)"),
          cite_scotus("United States v. Stevens, 559 U.S. 460 (2010)")],
         tags="us-conlaw,first-amendment,speech", grammar_point="Brown v. EMA"),
    card("usconlaw-195",
         "A state law prohibits drug-marketing data resellers from using prescriber-identifying information for marketing. Per Supreme Court doctrine, the restriction is most likely:",
         [("Constitutional under the state's privacy interest", False),
          ("Unconstitutional as content-based commercial-speech restriction", True),
          ("Constitutional under intermediate scrutiny", False),
          ("Constitutional under rational basis review", False)],
         "Sorrell v. IMS Health Inc. (2011) struck down Vermont's restriction on pharmacist-identifying data sales for marketing purposes. The Court held it was a CONTENT-BASED and SPEAKER-BASED restriction on commercial speech, subject to heightened scrutiny. The state's asserted interests were not directly advanced by the restriction.",
         [cite_scotus("Sorrell v. IMS Health Inc., 564 U.S. 552 (2011)")],
         tags="us-conlaw,first-amendment,commercial-speech", grammar_point="Sorrell v. IMS Health"),
    card("usconlaw-196",
         "Public school students wear black armbands to silently protest the Vietnam War. The school suspends them. Per Supreme Court doctrine, the suspensions are:",
         [("Constitutional under in loco parentis", False),
          ("Unconstitutional unless the speech materially and substantially disrupts the school's operation", True),
          ("Subject to rational basis review", False),
          ("Constitutional under educational deference", False)],
         "Tinker v. Des Moines (1969) held that students do not 'shed their constitutional rights to freedom of speech or expression at the schoolhouse gate.' School officials may regulate student speech only when the speech materially and substantially disrupts the educational environment. Subsequent cases (Bethel, Hazelwood, Morse v. Frederick) carved out exceptions for plainly offensive, school-sponsored, and drug-promoting speech.",
         [cite_scotus("Tinker v. Des Moines Indep. Community School Dist., 393 U.S. 503 (1969)"),
          cite_scotus("Mahanoy Area School Dist. v. B.L., 594 U.S. 180 (2021)")],
         tags="us-conlaw,first-amendment,student-speech", grammar_point="Tinker v. Des Moines"),
    # ─── Misc / Recent (4) ──────────────────────────────────────
    card("usconlaw-197",
         "A state law requires drug-store owners to dispense emergency contraception, even if the owner has religious objections. Per Supreme Court doctrine, the analysis turns on:",
         [("Whether the law is generally applicable and neutral", True),
          ("Strict scrutiny because it burdens religion", False),
          ("Whether the owner is a closely-held corporation under RFRA", False),
          ("Per se constitutionality under Smith", False)],
         "Employment Division v. Smith (1990) established that NEUTRAL, generally-applicable laws receive only rational-basis review even if they incidentally burden religion. Church of Lukumi Babalu Aye v. Hialeah (1993) and Fulton v. Philadelphia (2021) clarify that laws must be both NEUTRAL and GENERALLY APPLICABLE to escape strict scrutiny — laws containing individualized exemption regimes face heightened review.",
         [cite_scotus("Employment Division v. Smith, 494 U.S. 872 (1990)"),
          cite_scotus("Church of Lukumi Babalu Aye v. Hialeah, 508 U.S. 520 (1993)")],
         tags="us-conlaw,first-amendment,free-exercise", grammar_point="Smith / Lukumi neutrality"),
    card("usconlaw-198",
         "A federal regulation imposes a substantial burden on religious exercise. The regulated party invokes RFRA. Per Supreme Court doctrine, the regulation must:",
         [("Survive rational basis review", False),
          ("Survive strict scrutiny — least restrictive means to serve a compelling interest", True),
          ("Be neutral and generally applicable", False),
          ("Be authorized by Congress", False)],
         "RFRA (1993, after Smith) restored strict scrutiny for substantial burdens on religious exercise, but only as applied to FEDERAL law (City of Boerne v. Flores, 1997, struck down RFRA's application to states). Burwell v. Hobby Lobby (2014) applied RFRA to closely-held corporations. The standard: the federal regulation must be the LEAST RESTRICTIVE MEANS to further a COMPELLING government interest.",
         [cite_scotus("Burwell v. Hobby Lobby Stores, 573 U.S. 682 (2014)"),
          cite_scotus("City of Boerne v. Flores, 521 U.S. 507 (1997)")],
         tags="us-conlaw,first-amendment,rfra", grammar_point="RFRA strict scrutiny"),
    card("usconlaw-199",
         "Congress enacts a Religious Land Use and Institutionalized Persons Act provision requiring strict scrutiny of laws substantially burdening religious land-use. The act applies to states. Per Supreme Court doctrine, it is:",
         [("Unconstitutional under City of Boerne v. Flores", False),
          ("Constitutional as a valid exercise of Spending Clause and Commerce Clause powers", True),
          ("Constitutional under the 14A § 5 enforcement power only", False),
          ("Subject to strict scrutiny", False)],
         "Cutter v. Wilkinson (2005) upheld RLUIPA's application to state and local prisoner-religion claims as a valid exercise of the Spending Clause power (states accept federal funds for prisons subject to RLUIPA). Holt v. Hobbs (2015) applied RLUIPA's strict scrutiny to a prison grooming policy. Unlike RFRA's broader application (struck down for states in Boerne), RLUIPA's targeted application via Spending and Commerce Clauses is constitutional.",
         [cite_scotus("Cutter v. Wilkinson, 544 U.S. 709 (2005)"),
          cite_scotus("Holt v. Hobbs, 574 U.S. 352 (2015)")],
         tags="us-conlaw,first-amendment,rluipa", grammar_point="Cutter v. Wilkinson"),
    card("usconlaw-200",
         "An incarcerated person sues prison officials, alleging the deprivation of his right to grow a beard for religious reasons (a half-inch beard for Muslim faith). Per Supreme Court doctrine, the prison's no-beard policy is most likely:",
         [("Constitutional under the prison's security interest", False),
          ("Subject to RLUIPA's strict scrutiny — must be the least restrictive means to serve a compelling interest", True),
          ("Subject to rational basis review (Turner v. Safley)", False),
          ("Per se unconstitutional", False)],
         "Holt v. Hobbs (2015) struck down Arkansas's no-beard policy as applied to a Muslim prisoner seeking a half-inch beard for religious reasons. RLUIPA imposes strict scrutiny: the prison must show its policy is the LEAST RESTRICTIVE MEANS to serve a compelling interest. The Court found the prison's security justifications insufficient given the limited beard length and accommodations elsewhere.",
         [cite_scotus("Holt v. Hobbs, 574 U.S. 352 (2015)"),
          cite_scotus("Cutter v. Wilkinson, 544 U.S. 709 (2005)")],
         tags="us-conlaw,first-amendment,rluipa,prisoner", grammar_point="Holt v. Hobbs"),
]


def main():
    data = json.loads(CARDS_PATH.read_text(encoding="utf-8"))
    cards = data["cards"]
    existing_ids = {c["id"] for c in cards}
    added = 0
    for card_dict in NEW_CARDS:
        if card_dict["id"] not in existing_ids:
            cards.append(card_dict)
            added += 1
    tmp = CARDS_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps({"cards": cards}, ensure_ascii=False, indent=2) + "\n",
                   encoding="utf-8")
    tmp.replace(CARDS_PATH)
    print(f"Added {added} new cards. Total cards now: {len(cards)}.")


if __name__ == "__main__":
    main()
