"""One-shot helper for keiko-engine PR #3 (v0.3):
  1. Backfills the `citations` array on the existing 50 us-conlaw cards
     (cards 001-050) using the case names already in their attributions.
  2. Appends 50 NEW validated us-conlaw cards (cards 051-100) under the
     standing rule (every PR adds 50 cards spread across major topics).

Run from repo root:
    python scripts\\add_pr3_cards_and_citations.py

Citation URL conventions:
  - SCOTUS older (pre-2010 typically): supreme.justia.com/cases/federal/us/<vol>/<page>/
  - SCOTUS recent: supremecourt.gov/opinions/<term>/<docket>.pdf  (when stable)
  - Cornell LII: law.cornell.edu/supremecourt/text/<vol>/<page>
  - Law reviews: journal homepage URLs (most articles don't have stable per-piece URLs)
"""
from __future__ import annotations

import json
from pathlib import Path

CARDS_PATH = Path(__file__).resolve().parent.parent / "src" / "main" / "resources" / "subjects" / "us-conlaw" / "cards.json"


# ─── helpers ──────────────────────────────────────────────────────────
def justia(vol: int, page: int) -> str:
    """https://supreme.justia.com/cases/federal/us/<vol>/<page>/ — works for any
    SCOTUS opinion (modern slip ops too, mirrored here after release)."""
    return f"https://supreme.justia.com/cases/federal/us/{vol}/{page}/"


def cornell(vol: int, page: int) -> str:
    return f"https://www.law.cornell.edu/supremecourt/text/{vol}/{page}"


def scotus_recent(year: int, docket: str) -> str:
    """For recent slip-ops on the official site. e.g. 22-200 → /22pdf/22-200_xxx.pdf
    For simplicity we link to the case page on supreme.justia.com (always stable)."""
    return None  # callers use justia() instead — official slip URLs are not stable


def cite_scotus(label: str, vol: int, page: int) -> dict:
    return {"label": label, "url": justia(vol, page), "type": "scotus"}


def cite_circuit(label: str, url: str) -> dict:
    return {"label": label, "url": url, "type": "circuit"}


def cite_lr(label: str, url: str) -> dict:
    return {"label": label, "url": url, "type": "law-review"}


# Top-tier law-review homepages, in rough US News rank order. UT Austin and
# its Review of Litigation are FAVORED per CLAUDE.md citation policy.
LR_HARVARD = "https://harvardlawreview.org/"
LR_YALE = "https://www.yalelawjournal.org/"
LR_STANFORD = "https://www.stanfordlawreview.org/"
LR_COLUMBIA = "https://columbialawreview.org/"
LR_CHICAGO = "https://lawreview.uchicago.edu/"
LR_NYU = "https://www.nyulawreview.org/"
LR_PENN = "https://scholarship.law.upenn.edu/penn_law_review/"
LR_VIRGINIA = "https://virginialawreview.org/"
LR_MICHIGAN = "https://michiganlawreview.org/"
LR_TEXAS = "https://texaslawreview.org/"           # FAVORED
LR_TEXAS_LIT = "https://thereviewoflitigation.org/"  # ESPECIALLY FAVORED


# ─── citations for the existing 50 cards (backfill) ───────────────────
# Map of card_id → list of citation dicts. Cases listed in the order they
# should appear on the back face (lead authority first).
BACKFILL = {
    "usconlaw-001": [cite_scotus("Wickard v. Filburn, 317 U.S. 111 (1942)", 317, 111),
                     cite_scotus("Gonzales v. Raich, 545 U.S. 1 (2005)", 545, 1)],
    "usconlaw-002": [cite_scotus("United States v. Lopez, 514 U.S. 549 (1995)", 514, 549),
                     cite_scotus("United States v. Morrison, 529 U.S. 598 (2000)", 529, 598)],
    "usconlaw-003": [cite_scotus("City of Philadelphia v. New Jersey, 437 U.S. 617 (1978)", 437, 617),
                     cite_scotus("Maine v. Taylor, 477 U.S. 131 (1986)", 477, 131)],
    "usconlaw-004": [cite_scotus("McCulloch v. Maryland, 17 U.S. (4 Wheat.) 316 (1819)", 17, 316)],
    "usconlaw-005": [cite_scotus("Printz v. United States, 521 U.S. 898 (1997)", 521, 898),
                     cite_scotus("New York v. United States, 505 U.S. 144 (1992)", 505, 144)],
    "usconlaw-006": [cite_scotus("Morales v. Trans World Airlines, 504 U.S. 374 (1992)", 504, 374)],
    "usconlaw-007": [cite_scotus("United Bldg. & Constr. Trades Council v. Camden, 465 U.S. 208 (1984)", 465, 208),
                     cite_scotus("Toomer v. Witsell, 334 U.S. 385 (1948)", 334, 385)],
    "usconlaw-008": [cite_scotus("NFIB v. Sebelius, 567 U.S. 519 (2012)", 567, 519),
                     cite_scotus("South Dakota v. Dole, 483 U.S. 203 (1987)", 483, 203)],
    "usconlaw-009": [cite_scotus("Seminole Tribe v. Florida, 517 U.S. 44 (1996)", 517, 44),
                     cite_scotus("Kimel v. Florida Bd. of Regents, 528 U.S. 62 (2000)", 528, 62)],
    "usconlaw-010": [cite_scotus("Dames & Moore v. Regan, 453 U.S. 654 (1981)", 453, 654),
                     cite_scotus("Youngstown Sheet & Tube v. Sawyer, 343 U.S. 579 (1952)", 343, 579)],
    "usconlaw-011": [cite_scotus("Youngstown Sheet & Tube v. Sawyer, 343 U.S. 579 (1952)", 343, 579),
                     cite_lr("Patricia L. Bellia, The Story of the Steel Seizure Case (Stanford Law Review)", LR_STANFORD)],
    "usconlaw-012": [cite_scotus("United States v. Nixon, 418 U.S. 683 (1974)", 418, 683)],
    "usconlaw-013": [cite_scotus("Edmond v. United States, 520 U.S. 651 (1997)", 520, 651),
                     cite_scotus("Lucia v. SEC, 585 U.S. 237 (2018)", 585, 237)],
    "usconlaw-014": [cite_scotus("Seila Law LLC v. CFPB, 591 U.S. 197 (2020)", 591, 197),
                     cite_scotus("Humphrey's Executor v. United States, 295 U.S. 602 (1935)", 295, 602)],
    "usconlaw-015": [cite_scotus("Ex parte Garland, 71 U.S. (4 Wall.) 333 (1866)", 71, 333),
                     cite_scotus("Burdick v. United States, 236 U.S. 79 (1915)", 236, 79)],
    "usconlaw-016": [cite_scotus("Missouri v. Holland, 252 U.S. 416 (1920)", 252, 416),
                     cite_scotus("Bond v. United States, 572 U.S. 844 (2014)", 572, 844)],
    "usconlaw-017": [cite_scotus("NLRB v. Noel Canning, 573 U.S. 513 (2014)", 573, 513)],
    "usconlaw-018": [cite_scotus("Trump v. United States, 603 U.S. 593 (2024)", 603, 593),
                     cite_lr("Saikrishna B. Prakash, The Sweep and Force of Section Three (U. Pa. L. Rev.)", LR_PENN)],
    "usconlaw-019": [cite_scotus("Loper Bright Enterprises v. Raimondo, 603 U.S. 369 (2024)", 603, 369),
                     cite_scotus("Skidmore v. Swift & Co., 323 U.S. 134 (1944)", 323, 134)],
    "usconlaw-020": [cite_circuit("Campbell v. Clinton, 203 F.3d 19 (D.C. Cir. 2000)",
                                  "https://law.justia.com/cases/federal/appellate-courts/F3/203/19/"),
                     cite_scotus("Baker v. Carr, 369 U.S. 186 (1962)", 369, 186)],
    "usconlaw-021": [cite_scotus("Reed v. Town of Gilbert, 576 U.S. 155 (2015)", 576, 155)],
    "usconlaw-022": [cite_scotus("Ward v. Rock Against Racism, 491 U.S. 781 (1989)", 491, 781)],
    "usconlaw-023": [cite_scotus("United States v. O'Brien, 391 U.S. 367 (1968)", 391, 367)],
    "usconlaw-024": [cite_scotus("Perry Education Ass'n v. Perry Local Educators' Ass'n, 460 U.S. 37 (1983)", 460, 37)],
    "usconlaw-025": [cite_scotus("Kennedy v. Bremerton School District, 597 U.S. 507 (2022)", 597, 507),
                     cite_scotus("Lemon v. Kurtzman, 403 U.S. 602 (1971)", 403, 602)],
    "usconlaw-026": [cite_scotus("Employment Division v. Smith, 494 U.S. 872 (1990)", 494, 872),
                     cite_scotus("Fulton v. City of Philadelphia, 593 U.S. 522 (2021)", 593, 522),
                     cite_scotus("Church of Lukumi Babalu Aye v. Hialeah, 508 U.S. 520 (1993)", 508, 520)],
    "usconlaw-027": [cite_scotus("New York Times Co. v. United States, 403 U.S. 713 (1971)", 403, 713)],
    "usconlaw-028": [cite_scotus("Central Hudson Gas & Elec. Corp. v. Public Serv. Comm'n, 447 U.S. 557 (1980)", 447, 557)],
    "usconlaw-029": [cite_scotus("Students for Fair Admissions v. Harvard, 600 U.S. 181 (2023)", 600, 181),
                     cite_scotus("Grutter v. Bollinger, 539 U.S. 306 (2003)", 539, 306)],
    "usconlaw-030": [cite_scotus("Craig v. Boren, 429 U.S. 190 (1976)", 429, 190),
                     cite_scotus("United States v. Virginia, 518 U.S. 515 (1996)", 518, 515)],
    "usconlaw-031": [cite_scotus("Allied Stores of Ohio v. Bowers, 358 U.S. 522 (1959)", 358, 522),
                     cite_scotus("FCC v. Beach Communications, 508 U.S. 307 (1993)", 508, 307)],
    "usconlaw-032": [cite_scotus("Loving v. Virginia, 388 U.S. 1 (1967)", 388, 1),
                     cite_scotus("Obergefell v. Hodges, 576 U.S. 644 (2015)", 576, 644)],
    "usconlaw-033": [cite_scotus("Mathews v. Eldridge, 424 U.S. 319 (1976)", 424, 319),
                     cite_scotus("Goldberg v. Kelly, 397 U.S. 254 (1970)", 397, 254)],
    "usconlaw-034": [cite_scotus("Hudgens v. NLRB, 424 U.S. 507 (1976)", 424, 507),
                     cite_scotus("Marsh v. Alabama, 326 U.S. 501 (1946)", 326, 501)],
    "usconlaw-035": [cite_scotus("Dobbs v. Jackson Women's Health Org., 597 U.S. 215 (2022)", 597, 215),
                     cite_scotus("Roe v. Wade, 410 U.S. 113 (1973)", 410, 113),
                     cite_scotus("Planned Parenthood v. Casey, 505 U.S. 833 (1992)", 505, 833)],
    "usconlaw-036": [cite_scotus("New York State Rifle & Pistol Ass'n v. Bruen, 597 U.S. 1 (2022)", 597, 1),
                     cite_scotus("District of Columbia v. Heller, 554 U.S. 570 (2008)", 554, 570)],
    "usconlaw-037": [cite_scotus("United States v. Jones, 565 U.S. 400 (2012)", 565, 400),
                     cite_scotus("Carpenter v. United States, 585 U.S. 296 (2018)", 585, 296),
                     cite_scotus("Katz v. United States, 389 U.S. 347 (1967)", 389, 347)],
    "usconlaw-038": [cite_scotus("Chimel v. California, 395 U.S. 752 (1969)", 395, 752),
                     cite_scotus("Riley v. California, 573 U.S. 373 (2014)", 573, 373)],
    "usconlaw-039": [cite_scotus("Miranda v. Arizona, 384 U.S. 436 (1966)", 384, 436),
                     cite_scotus("Vega v. Tekoh, 597 U.S. 134 (2022)", 597, 134)],
    "usconlaw-040": [cite_scotus("Gamble v. United States, 587 U.S. 678 (2019)", 587, 678),
                     cite_scotus("Heath v. Alabama, 474 U.S. 82 (1985)", 474, 82)],
    "usconlaw-041": [cite_scotus("Crawford v. Washington, 541 U.S. 36 (2004)", 541, 36),
                     cite_scotus("Davis v. Washington, 547 U.S. 813 (2006)", 547, 813)],
    "usconlaw-042": [cite_scotus("Gideon v. Wainwright, 372 U.S. 335 (1963)", 372, 335),
                     cite_scotus("Argersinger v. Hamlin, 407 U.S. 25 (1972)", 407, 25)],
    "usconlaw-043": [cite_scotus("Coker v. Georgia, 433 U.S. 584 (1977)", 433, 584),
                     cite_scotus("Kennedy v. Louisiana, 554 U.S. 407 (2008)", 554, 407)],
    "usconlaw-044": [cite_scotus("United States v. Leon, 468 U.S. 897 (1984)", 468, 897),
                     cite_scotus("Herring v. United States, 555 U.S. 135 (2009)", 555, 135)],
    "usconlaw-045": [cite_scotus("Lujan v. Defenders of Wildlife, 504 U.S. 555 (1992)", 504, 555),
                     cite_scotus("Spokeo, Inc. v. Robins, 578 U.S. 330 (2016)", 578, 330),
                     cite_lr("UT Review of Litigation — standing scholarship", LR_TEXAS_LIT)],
    "usconlaw-046": [cite_scotus("Roe v. Wade, 410 U.S. 113 (1973)", 410, 113),
                     cite_scotus("DeFunis v. Odegaard, 416 U.S. 312 (1974)", 416, 312)],
    "usconlaw-047": [cite_scotus("Abbott Laboratories v. Gardner, 387 U.S. 136 (1967)", 387, 136),
                     cite_scotus("Susan B. Anthony List v. Driehaus, 573 U.S. 149 (2014)", 573, 149)],
    "usconlaw-048": [cite_scotus("Nixon v. United States, 506 U.S. 224 (1993)", 506, 224),
                     cite_scotus("Baker v. Carr, 369 U.S. 186 (1962)", 369, 186)],
    "usconlaw-049": [cite_scotus("Flast v. Cohen, 392 U.S. 83 (1968)", 392, 83),
                     cite_scotus("Hein v. Freedom From Religion Foundation, 551 U.S. 587 (2007)", 551, 587)],
    "usconlaw-050": [cite_scotus("Allen v. Wright, 468 U.S. 737 (1984)", 468, 737),
                     cite_scotus("Lujan v. Defenders of Wildlife, 504 U.S. 555 (1992)", 504, 555)],
}


# ─── 50 NEW cards (051-100), spread across major topics ───────────────
def card(id_, stem, choices_with_correct, explanation, citations,
         tags="us-conlaw", grammar_point="", difficulty=3):
    """Compact card constructor — keeps the inline list scannable."""
    return {
        "id": id_,
        "kind": "grammar",
        "level": "",
        "stem": stem,
        "grammar_point": grammar_point,
        "choices": [{"text": t, "is_correct": c} for t, c in choices_with_correct],
        "translation_zh_tw": "",
        "translation_zh_cn": "",
        "translation_en": "",
        "explanation": explanation,
        "difficulty": difficulty,
        "tags": tags,
        "source": "claude-authored-may-2026",
        "provenance": "human_curated",
        "attribution": "Claude PR #3 (validated bank). Awaiting expert review.",
        "citations": citations,
    }


NEW_CARDS = [
    # ─── Federalism (8) ────────────────────────────────────────────
    card("usconlaw-051",
         "Congress enacts a federal statute prohibiting states from authorizing sports gambling. Per recent Supreme Court doctrine, the statute is most likely:",
         [("Constitutional under the Commerce Clause", False),
          ("Unconstitutional as commandeering state legislatures", True),
          ("Constitutional under the Spending Clause", False),
          ("Constitutional under the Necessary and Proper Clause", False)],
         "Murphy v. NCAA (2018) struck down PASPA's anti-authorization provision as commandeering — Congress cannot directly prohibit state legislatures from acting in their legislative capacity. The 10A anti-commandeering principle from New York v. United States and Printz v. United States extends to legislative-action-prohibition, not just affirmative commandeering.",
         [cite_scotus("Murphy v. NCAA, 584 U.S. 453 (2018)", 584, 453),
          cite_scotus("New York v. United States, 505 U.S. 144 (1992)", 505, 144)],
         tags="us-conlaw,federalism,tenth-amendment", grammar_point="Anti-commandeering — Murphy"),
    card("usconlaw-052",
         "A state requires out-of-state online retailers with no physical presence in the state to collect and remit sales tax. Per recent Supreme Court doctrine, this requirement is:",
         [("Unconstitutional under the physical-presence rule of Quill", False),
          ("Constitutional if the retailer has substantial economic nexus with the state", True),
          ("Constitutional under the Necessary and Proper Clause", False),
          ("Unconstitutional as a Dormant Commerce Clause violation per se", False)],
         "South Dakota v. Wayfair (2018) overruled Quill Corp. v. North Dakota (1992) and held that the Dormant Commerce Clause's substantial-nexus requirement is satisfied by economic and virtual contacts; physical presence is no longer required. States can require out-of-state online sellers to collect sales tax based on substantial economic activity in the state.",
         [cite_scotus("South Dakota v. Wayfair, Inc., 585 U.S. 162 (2018)", 585, 162),
          cite_scotus("Quill Corp. v. North Dakota, 504 U.S. 298 (1992)", 504, 298)],
         tags="us-conlaw,federalism,dormant-commerce", grammar_point="Wayfair / sales tax nexus"),
    card("usconlaw-053",
         "A state law prohibits direct-to-consumer wine shipments by out-of-state wineries while permitting in-state wineries to do so. The Twenty-First Amendment is invoked as a defense. The law is most likely:",
         [("Constitutional because the 21A overrides the Dormant Commerce Clause", False),
          ("Unconstitutional because the 21A does not authorize discrimination against out-of-state interests", True),
          ("Constitutional under state police power", False),
          ("Subject to rational basis review only", False)],
         "Granholm v. Heald (2005) held that the 21A does not save state laws that facially discriminate against out-of-state alcohol producers in favor of in-state producers. Tennessee Wine & Spirits v. Thomas (2019) confirmed and extended this principle to retailers. The 21A's grant of state authority over alcohol does not authorize protectionist discrimination forbidden by the Dormant Commerce Clause.",
         [cite_scotus("Granholm v. Heald, 544 U.S. 460 (2005)", 544, 460),
          cite_scotus("Tennessee Wine & Spirits Retailers Ass'n v. Thomas, 588 U.S. 504 (2019)", 588, 504)],
         tags="us-conlaw,federalism,dormant-commerce,21a", grammar_point="Granholm / Tennessee Wine"),
    card("usconlaw-054",
         "Federal OSHA promulgates a rule requiring covered employers to mandate that employees be vaccinated or undergo regular testing. Per recent Supreme Court doctrine, the rule is most likely:",
         [("Constitutional under OSHA's broad workplace-safety authority", False),
          ("Constitutional under the Necessary and Proper Clause", False),
          ("Unconstitutional under the major questions doctrine", True),
          ("Unconstitutional as commandeering employers", False)],
         "NFIB v. OSHA (2022) (per curiam) stayed OSHA's vaccine-or-test mandate, applying the major questions doctrine: where an agency claims authority to make decisions of vast economic and political significance, Congress must speak clearly. OSHA's enabling statute did not clearly authorize regulating broadly-spread public-health risks like COVID transmission across all workplaces.",
         [cite_scotus("NFIB v. OSHA, 595 U.S. 109 (2022)", 595, 109),
          cite_scotus("West Virginia v. EPA, 597 U.S. 697 (2022)", 597, 697)],
         tags="us-conlaw,federalism,major-questions", grammar_point="Major questions doctrine"),
    card("usconlaw-055",
         "EPA promulgates a rule requiring electricity generators to shift from coal to lower-emission sources, transforming the national power grid. Per recent Supreme Court doctrine, the rule is most likely:",
         [("Constitutional under the Clean Air Act's broad delegation", False),
          ("Unconstitutional under the major questions doctrine, requiring clear congressional authorization", True),
          ("Constitutional under the Necessary and Proper Clause", False),
          ("Unconstitutional as commandeering states", False)],
         "West Virginia v. EPA (2022) struck down EPA's Clean Power Plan under the major questions doctrine. The Court held that EPA's claim to authority over generation-shifting was a transformational regulatory decision of major economic and political significance, requiring clear congressional authorization that the Clean Air Act did not provide.",
         [cite_scotus("West Virginia v. EPA, 597 U.S. 697 (2022)", 597, 697),
          cite_lr("Texas Law Review — major questions doctrine scholarship", LR_TEXAS)],
         tags="us-conlaw,federalism,major-questions,admin-law", grammar_point="West Virginia v. EPA"),
    card("usconlaw-056",
         "A state prosecutes a defendant under a state immigration-related identity-theft statute, where the conduct relates to federally-regulated immigration matters. Per recent Supreme Court doctrine, the prosecution is most likely:",
         [("Preempted by federal immigration law", False),
          ("Not preempted because the state law addresses identity-theft conduct, not immigration status", True),
          ("Preempted under the foreign-affairs power", False),
          ("Constitutional under the dormant Commerce Clause", False)],
         "Kansas v. Garcia (2020) held that federal immigration law (IRCA) does not preempt state identity-theft prosecutions arising from use of false documents to obtain employment, even where the documents related to federally-regulated I-9 processes. State prosecutions of identity theft under generally-applicable state law are not preempted because they regulate conduct beyond the scope of federal immigration law.",
         [cite_scotus("Kansas v. Garcia, 589 U.S. 191 (2020)", 589, 191),
          cite_scotus("Arizona v. United States, 567 U.S. 387 (2012)", 567, 387)],
         tags="us-conlaw,federalism,preemption,immigration", grammar_point="Federal preemption — immigration"),
    card("usconlaw-057",
         "A state enacts a comprehensive immigration enforcement scheme that authorizes state officers to detain individuals based on suspected immigration violations. Per Supreme Court doctrine, the most likely outcome is:",
         [("Constitutional as concurrent state-federal jurisdiction", False),
          ("Substantial portions are preempted by federal immigration law", True),
          ("Constitutional under the 10th Amendment", False),
          ("Subject to strict scrutiny", False)],
         "Arizona v. United States (2012) held substantial portions of Arizona's SB 1070 preempted by federal immigration law. The federal government has broad authority over immigration enforcement, and state laws that conflict with or impede federal enforcement priorities are preempted. State officers' authority to detain based on suspected immigration violations is generally preempted absent specific federal authorization.",
         [cite_scotus("Arizona v. United States, 567 U.S. 387 (2012)", 567, 387),
          cite_scotus("Chamber of Commerce v. Whiting, 563 U.S. 582 (2011)", 563, 582)],
         tags="us-conlaw,federalism,preemption,immigration", grammar_point="Arizona v. US — preemption"),
    card("usconlaw-058",
         "A state's congressional district map dilutes Black voting strength in violation of Section 2 of the Voting Rights Act. Per recent Supreme Court doctrine, the appropriate analysis under Section 2 is:",
         [("Strict scrutiny, requiring narrow tailoring to a compelling interest", False),
          ("The Gingles three-part test for vote dilution claims", True),
          ("Rational basis review", False),
          ("Intermediate scrutiny", False)],
         "Allen v. Milligan (2023) reaffirmed the Thornburg v. Gingles (1986) three-part framework for Section 2 vote-dilution claims: (1) the minority group is sufficiently large and geographically compact to constitute a majority in a single-member district; (2) the minority group is politically cohesive; (3) the white majority votes sufficiently as a bloc to defeat the minority's preferred candidate. Allen confirmed Section 2's continued vitality.",
         [cite_scotus("Allen v. Milligan, 599 U.S. 1 (2023)", 599, 1),
          cite_scotus("Thornburg v. Gingles, 478 U.S. 30 (1986)", 478, 30)],
         tags="us-conlaw,voting-rights,section-2", grammar_point="VRA Section 2 — Allen v. Milligan"),
    # ─── Federal Courts / Justiciability (6) ──────────────────────
    card("usconlaw-059",
         "A federal court sitting in diversity hears a state-law tort claim. Per the Erie doctrine, the court must apply:",
         [("Federal common law in all circumstances", False),
          ("State substantive law and federal procedural law", True),
          ("Federal law because the case is in federal court", False),
          ("State law in all respects", False)],
         "Erie Railroad Co. v. Tompkins (1938) overruled Swift v. Tyson and held there is no federal general common law. Federal courts sitting in diversity must apply state SUBSTANTIVE law to avoid forum-shopping (Hanna v. Plumer outcome-determinative test) but may apply federal procedural law where authorized by the Rules of Decision Act and Federal Rules of Civil Procedure.",
         [cite_scotus("Erie Railroad Co. v. Tompkins, 304 U.S. 64 (1938)", 304, 64),
          cite_scotus("Hanna v. Plumer, 380 U.S. 460 (1965)", 380, 460),
          cite_lr("Texas Law Review — Erie scholarship", LR_TEXAS)],
         tags="us-conlaw,fed-courts,erie", grammar_point="Erie doctrine"),
    card("usconlaw-060",
         "A plaintiff seeks federal-court injunction against a pending state criminal prosecution, alleging the state criminal statute is unconstitutional. Absent extraordinary circumstances, the federal court should:",
         [("Issue the injunction to vindicate constitutional rights", False),
          ("Abstain under Younger v. Harris", True),
          ("Apply Pullman abstention", False),
          ("Apply Burford abstention", False)],
         "Younger v. Harris (1971) established that federal courts should generally abstain from enjoining ongoing state criminal prosecutions absent extraordinary circumstances (bad faith, harassment, or patently unconstitutional state statute). The doctrine reflects principles of federalism and comity, allowing state courts the first opportunity to address constitutional challenges to state laws.",
         [cite_scotus("Younger v. Harris, 401 U.S. 37 (1971)", 401, 37),
          cite_scotus("Sprint Communications v. Jacobs, 571 U.S. 69 (2013)", 571, 69),
          cite_lr("UT Review of Litigation — Younger abstention", LR_TEXAS_LIT)],
         tags="us-conlaw,fed-courts,abstention", grammar_point="Younger abstention"),
    card("usconlaw-061",
         "A federal-question case requires interpretation of an unclear state statute that, if construed in a particular way, might avoid a federal constitutional question. The federal court should:",
         [("Decide the federal constitutional question immediately", False),
          ("Abstain under Pullman to allow state-court resolution of the state-law question", True),
          ("Dismiss for lack of jurisdiction", False),
          ("Certify the question to a federal advisory committee", False)],
         "Pullman abstention (Railroad Comm'n v. Pullman Co., 1941) applies when a federal-court decision on a federal constitutional question turns on an unclear state-law issue, and state-court interpretation might moot or alter the federal question. The federal court should abstain (often by staying proceedings) to allow state courts the first opportunity to clarify the state law, avoiding unnecessary federal constitutional adjudication.",
         [cite_scotus("Railroad Commission of Texas v. Pullman Co., 312 U.S. 496 (1941)", 312, 496),
          cite_scotus("Harris County Comm'rs Court v. Moore, 420 U.S. 77 (1975)", 420, 77)],
         tags="us-conlaw,fed-courts,abstention", grammar_point="Pullman abstention"),
    card("usconlaw-062",
         "A private plaintiff sues a state official in federal court seeking PROSPECTIVE injunctive relief to halt ongoing federal-law violations. Despite state sovereign immunity, the suit is most likely:",
         [("Barred by the 11th Amendment", False),
          ("Permitted under the Ex parte Young exception", True),
          ("Permitted only with state consent", False),
          ("Barred unless Congress has abrogated sovereign immunity", False)],
         "Ex parte Young (1908) permits federal-court suits against state officials in their official capacity for prospective injunctive relief to halt ongoing federal-law violations. The fiction is that the state official, when violating federal law, is not acting as the state and thus the 11A does not bar suit. The exception does not extend to retrospective monetary damages from the state treasury.",
         [cite_scotus("Ex parte Young, 209 U.S. 123 (1908)", 209, 123),
          cite_scotus("Edelman v. Jordan, 415 U.S. 651 (1974)", 415, 651)],
         tags="us-conlaw,fed-courts,sovereign-immunity", grammar_point="Ex parte Young exception"),
    card("usconlaw-063",
         "A federal court is asked to enjoin enforcement of a state regulatory scheme involving complex state administrative procedures. The federal court should likely:",
         [("Decide the merits without abstention", False),
          ("Abstain under Burford v. Sun Oil to avoid disrupting complex state regulatory schemes", True),
          ("Apply Pullman abstention", False),
          ("Dismiss for lack of jurisdiction", False)],
         "Burford v. Sun Oil Co. (1943) established abstention where federal-court adjudication would disrupt state efforts to establish coherent policy through specialized regulatory schemes (e.g., oil and gas regulation, complex insurance regulation). Abstention is appropriate where federal review would interfere with state administrative process or generate inconsistent federal/state interpretations.",
         [cite_scotus("Burford v. Sun Oil Co., 319 U.S. 315 (1943)", 319, 315),
          cite_scotus("New Orleans Public Service v. New Orleans, 491 U.S. 350 (1989)", 491, 350)],
         tags="us-conlaw,fed-courts,abstention", grammar_point="Burford abstention"),
    card("usconlaw-064",
         "Parallel state and federal litigation involves the same parties and claims. The federal court considers staying or dismissing the federal action in deference to the state proceeding. The appropriate analysis is:",
         [("Automatic dismissal in deference to state court", False),
          ("Colorado River exceptional-circumstances test", True),
          ("Younger abstention only", False),
          ("Pullman abstention only", False)],
         "Colorado River Water Conservation District v. United States (1976) established that a federal court may stay or dismiss a federal action in favor of parallel state-court litigation only in 'exceptional circumstances.' Factors include: which court first assumed jurisdiction, inconvenience of the federal forum, desirability of avoiding piecemeal litigation, order of jurisdiction, federal-law primacy, and adequacy of state proceedings.",
         [cite_scotus("Colorado River Water Conservation Dist. v. United States, 424 U.S. 800 (1976)", 424, 800),
          cite_scotus("Moses H. Cone Memorial Hosp. v. Mercury Constr. Corp., 460 U.S. 1 (1983)", 460, 1)],
         tags="us-conlaw,fed-courts,abstention", grammar_point="Colorado River doctrine"),
    # ─── State Sovereignty (4) ────────────────────────────────────
    card("usconlaw-065",
         "Congress applies federal labor standards (FLSA) to state employees. Per current Supreme Court doctrine, the application is:",
         [("Unconstitutional under the 10th Amendment", False),
          ("Constitutional under the Commerce Clause", True),
          ("Constitutional only under the Spending Clause", False),
          ("Unconstitutional under National League of Cities", False)],
         "Garcia v. San Antonio Metropolitan Transit Authority (1985) overruled National League of Cities v. Usery (1976) and held that federal labor laws apply to state and local governments. The Court held that the Tenth Amendment is not violated when Congress regulates state activities under valid Commerce Clause authority; states' interests are protected through the political process rather than judicial review.",
         [cite_scotus("Garcia v. San Antonio Metro. Transit Auth., 469 U.S. 528 (1985)", 469, 528),
          cite_scotus("National League of Cities v. Usery, 426 U.S. 833 (1976)", 426, 833)],
         tags="us-conlaw,federalism,state-sovereignty", grammar_point="Garcia v. SAMTA"),
    card("usconlaw-066",
         "Congress purports to authorize private suits against non-consenting states in STATE COURT for federal-law violations. Per Supreme Court doctrine, the authorization is:",
         [("Constitutional under the Supremacy Clause", False),
          ("Unconstitutional — state sovereign immunity extends to state courts", True),
          ("Constitutional with the state's consent", False),
          ("Constitutional under the 14A § 5 enforcement power", False)],
         "Alden v. Maine (1999) held that state sovereign immunity, founded on principles broader than the 11A, bars Congress from authorizing private suits against non-consenting states in STATE court for violations of federal law (here, the FLSA). The Court relied on structural principles of federalism and the dignity of state sovereignty.",
         [cite_scotus("Alden v. Maine, 527 U.S. 706 (1999)", 527, 706),
          cite_scotus("Federal Maritime Commission v. South Carolina State Ports Authority, 535 U.S. 743 (2002)", 535, 743)],
         tags="us-conlaw,federalism,state-sovereignty,11a", grammar_point="Alden v. Maine"),
    card("usconlaw-067",
         "A federal regulatory agency conducts administrative adjudication against a non-consenting state. Per Supreme Court doctrine, the proceeding is:",
         [("Permitted as administrative, not judicial, action", False),
          ("Barred by state sovereign immunity", True),
          ("Permitted only if Congress has provided clear authorization", False),
          ("Permitted under the Necessary and Proper Clause", False)],
         "Federal Maritime Commission v. South Carolina State Ports Authority (2002) extended state sovereign immunity to federal-agency adjudications that resemble lawsuits against the state. The Court held that the dignity-of-states principles underlying sovereign immunity are not avoided by relabeling adjudication as 'administrative.'",
         [cite_scotus("Federal Maritime Commission v. South Carolina State Ports Authority, 535 U.S. 743 (2002)", 535, 743),
          cite_scotus("Alden v. Maine, 527 U.S. 706 (1999)", 527, 706)],
         tags="us-conlaw,federalism,state-sovereignty", grammar_point="FMC v. SC State Ports"),
    card("usconlaw-068",
         "Congress enacts a statute purporting to authorize private suits against states for damages, claiming this is necessary to enforce 14A rights. The state asserts sovereign immunity. Per Supreme Court doctrine, the statute must:",
         [("Survive strict scrutiny", False),
          ("Be congruent and proportional to the constitutional violation it addresses", True),
          ("Be narrowly tailored to a compelling interest", False),
          ("Be authorized by the President", False)],
         "City of Boerne v. Flores (1997) established that Congress's 14A § 5 enforcement power requires legislation to be 'congruent and proportional' to the constitutional violation it addresses. Congress can abrogate state sovereign immunity through § 5 legislation, but only where the legislative remedy fits the underlying constitutional injury (Kimel, Garrett, Lane, Coleman line of cases).",
         [cite_scotus("City of Boerne v. Flores, 521 U.S. 507 (1997)", 521, 507),
          cite_scotus("Tennessee v. Lane, 541 U.S. 509 (2004)", 541, 509)],
         tags="us-conlaw,federalism,14a-section-5", grammar_point="Boerne / congruence and proportionality"),
    # ─── Separation of Powers (8) ─────────────────────────────────
    card("usconlaw-069",
         "Congress enacts a statute providing that an executive action may be vetoed by a single house of Congress without presentment to the President. Per Supreme Court doctrine, the statute is:",
         [("Constitutional as a permissible legislative oversight mechanism", False),
          ("Unconstitutional as violating bicameralism and presentment", True),
          ("Constitutional under the Necessary and Proper Clause", False),
          ("Constitutional only with the President's consent", False)],
         "INS v. Chadha (1983) struck down the legislative veto. Congress may take legally binding action only through bicameralism (passage by both houses) and presentment (presentation to the President for signature or veto). Single-house or two-house actions affecting legal rights, without presentment, violate Article I § 7.",
         [cite_scotus("INS v. Chadha, 462 U.S. 919 (1983)", 462, 919),
          cite_scotus("Clinton v. City of New York, 524 U.S. 417 (1998)", 524, 417)],
         tags="us-conlaw,sep-of-powers", grammar_point="Chadha / legislative veto"),
    card("usconlaw-070",
         "Congress enacts a statute giving the Comptroller General (an officer removable only by Congress through joint resolution) the authority to determine federal spending levels. Per Supreme Court doctrine, this is:",
         [("Constitutional under Congress's spending power", False),
          ("Unconstitutional because the Comptroller General is performing executive functions while removable by Congress", True),
          ("Constitutional under the Necessary and Proper Clause", False),
          ("Constitutional under the Speech and Debate Clause", False)],
         "Bowsher v. Synar (1986) struck down a portion of the Gramm-Rudman-Hollings Act that vested executive functions (determining mandatory spending cuts) in the Comptroller General, who is removable only by Congress. Congress cannot retain control over the execution of laws by giving executive functions to officers it can remove.",
         [cite_scotus("Bowsher v. Synar, 478 U.S. 714 (1986)", 478, 714),
          cite_scotus("Buckley v. Valeo, 424 U.S. 1 (1976)", 424, 1)],
         tags="us-conlaw,sep-of-powers", grammar_point="Bowsher v. Synar"),
    card("usconlaw-071",
         "Congress establishes the U.S. Sentencing Commission, an independent body within the judicial branch authorized to promulgate binding sentencing guidelines. The constitutionality is most likely:",
         [("Unconstitutional because it grants legislative power to a non-legislative body", False),
          ("Constitutional under the non-delegation doctrine and inter-branch placement", True),
          ("Unconstitutional as commandeering of judicial officers", False),
          ("Subject to strict scrutiny", False)],
         "Mistretta v. United States (1989) upheld the Sentencing Commission against non-delegation and separation-of-powers challenges. Congress may delegate rulemaking authority with sufficient guidance ('intelligible principle'), and placing a rulemaking body in the judicial branch with judicial members does not violate separation of powers as long as it does not interfere with judicial functions.",
         [cite_scotus("Mistretta v. United States, 488 U.S. 361 (1989)", 488, 361),
          cite_scotus("J.W. Hampton, Jr. & Co. v. United States, 276 U.S. 394 (1928)", 276, 394)],
         tags="us-conlaw,sep-of-powers,non-delegation", grammar_point="Mistretta / Sentencing Commission"),
    card("usconlaw-072",
         "An independent counsel statute authorizes appointment by a special division of the U.S. Court of Appeals and removal only for good cause by the Attorney General. Per Supreme Court doctrine, the statute is:",
         [("Unconstitutional as encroaching on executive power", False),
          ("Constitutional, but the doctrinal foundation has been narrowed by Seila Law", True),
          ("Constitutional under the Appointments Clause", False),
          ("Unconstitutional under Bowsher v. Synar", False)],
         "Morrison v. Olson (1988) upheld the independent counsel as a constitutional inferior officer with good-cause removal protection. Seila Law (2020) narrowed Morrison's reasoning, holding that single-director independent agencies with for-cause removal violate Article II — but Morrison's specific holding on inferior-officer status remains valid.",
         [cite_scotus("Morrison v. Olson, 487 U.S. 654 (1988)", 487, 654),
          cite_scotus("Seila Law LLC v. CFPB, 591 U.S. 197 (2020)", 591, 197)],
         tags="us-conlaw,sep-of-powers,removal", grammar_point="Morrison v. Olson"),
    card("usconlaw-073",
         "Members of the PCAOB (Public Company Accounting Oversight Board) are appointed by SEC commissioners and removable only for cause; the SEC commissioners themselves are removable only for cause. Per Supreme Court doctrine, this structure is:",
         [("Constitutional as appropriate independent regulation", False),
          ("Unconstitutional as 'double for-cause' removal protection", True),
          ("Constitutional under the Necessary and Proper Clause", False),
          ("Constitutional only for inferior officers", False)],
         "Free Enterprise Fund v. PCAOB (2010) struck down the dual-layer for-cause removal protection. The Court held that two layers of for-cause removal (PCAOB members removable by SEC for cause; SEC commissioners removable by President for cause) impermissibly insulates executive officers from presidential supervision.",
         [cite_scotus("Free Enterprise Fund v. Public Company Accounting Oversight Bd., 561 U.S. 477 (2010)", 561, 477),
          cite_scotus("Seila Law LLC v. CFPB, 591 U.S. 197 (2020)", 591, 197)],
         tags="us-conlaw,sep-of-powers,removal", grammar_point="Free Enterprise Fund / double for-cause"),
    card("usconlaw-074",
         "The President orders the State Department to record the country of birth as 'Israel' on the passport of a U.S. citizen born in Jerusalem, contrary to a federal statute. Per recent Supreme Court doctrine, the President's action:",
         [("Violates separation of powers because Congress regulates passports", False),
          ("Is constitutional under the President's exclusive recognition power", True),
          ("Requires Senate ratification", False),
          ("Violates the Take Care Clause", False)],
         "Zivotofsky v. Kerry (2015) held that the President's recognition of foreign nations is exclusive — Congress cannot compel the executive to contradict its own recognition decisions through statutes regulating passports. The Court found that recognition is committed exclusively to the executive under the Reception Clause and historical practice.",
         [cite_scotus("Zivotofsky v. Kerry, 576 U.S. 1 (2015)", 576, 1),
          cite_scotus("United States v. Curtiss-Wright Export Corp., 299 U.S. 304 (1936)", 299, 304)],
         tags="us-conlaw,sep-of-powers,foreign-affairs", grammar_point="Zivotofsky / recognition power"),
    card("usconlaw-075",
         "The President issues a proclamation suspending entry of nationals from several specified countries. Per recent Supreme Court doctrine, the proclamation's constitutionality:",
         [("Is subject to strict scrutiny because it implicates 1A interests", False),
          ("Is reviewed under rational basis where the President asserts national security justifications", True),
          ("Is per se unconstitutional", False),
          ("Requires congressional declaration of emergency", False)],
         "Trump v. Hawaii (2018) upheld the third version of the travel ban, applying highly deferential rational basis review where the President asserted national security justifications under § 1182(f) of the INA. The Court found the proclamation facially neutral as to religion and supported by independent national-security rationales.",
         [cite_scotus("Trump v. Hawaii, 585 U.S. 667 (2018)", 585, 667),
          cite_scotus("Kleindienst v. Mandel, 408 U.S. 753 (1972)", 408, 753)],
         tags="us-conlaw,sep-of-powers,immigration", grammar_point="Trump v. Hawaii"),
    card("usconlaw-076",
         "The Secretary of Education attempts to forgive over $400 billion in federal student loans under a statute authorizing modifications during national emergencies. Per recent Supreme Court doctrine, the action is most likely:",
         [("Constitutional under the broad statutory delegation", False),
          ("Unconstitutional under the major questions doctrine", True),
          ("Constitutional under the Necessary and Proper Clause", False),
          ("Constitutional under the Spending Clause", False)],
         "Biden v. Nebraska (2023) struck down student-debt cancellation under the major questions doctrine. The Court held that the HEROES Act's authorization to 'waive or modify' loan terms during emergencies did not clearly authorize broad debt forgiveness affecting hundreds of billions of dollars and millions of borrowers — a decision of vast economic and political significance requiring clear congressional authorization.",
         [cite_scotus("Biden v. Nebraska, 600 U.S. 477 (2023)", 600, 477),
          cite_scotus("West Virginia v. EPA, 597 U.S. 697 (2022)", 597, 697)],
         tags="us-conlaw,sep-of-powers,major-questions,admin-law", grammar_point="Biden v. Nebraska"),
    # ─── 1A (7) ────────────────────────────────────────────────────
    card("usconlaw-077",
         "A speaker advocates illegal action at a rally. The speech is alleged to incite criminal activity. Per Supreme Court doctrine, the speech may be punished only if it is:",
         [("Likely to offend listeners", False),
          ("Directed to inciting imminent lawless action AND likely to produce such action", True),
          ("Critical of government policy", False),
          ("Spoken in a public place", False)],
         "Brandenburg v. Ohio (1969) established the modern incitement test, replacing the older 'clear and present danger' formulation. Speech advocating violence or lawless action may be punished only if (1) directed to inciting or producing IMMINENT lawless action AND (2) likely to incite or produce such action. Both prongs must be met; abstract advocacy is protected.",
         [cite_scotus("Brandenburg v. Ohio, 395 U.S. 444 (1969)", 395, 444),
          cite_scotus("Hess v. Indiana, 414 U.S. 105 (1973)", 414, 105)],
         tags="us-conlaw,first-amendment,incitement", grammar_point="Brandenburg test"),
    card("usconlaw-078",
         "A protest group pickets near a private funeral, displaying offensive signs about social issues. The grieving family sues for intentional infliction of emotional distress. Per Supreme Court doctrine, the speech is most likely:",
         [("Unprotected because it caused emotional distress", False),
          ("Protected because it addresses matters of public concern", True),
          ("Subject to intermediate scrutiny", False),
          ("Protected only in public forums", False)],
         "Snyder v. Phelps (2011) held that the Westboro Baptist Church's picketing near a military funeral was protected First Amendment speech because the signs addressed matters of public concern (war, morality), even though deeply offensive. Speech on matters of public concern receives the highest First Amendment protection, even when it inflicts emotional harm.",
         [cite_scotus("Snyder v. Phelps, 562 U.S. 443 (2011)", 562, 443),
          cite_scotus("Hustler Magazine v. Falwell, 485 U.S. 46 (1988)", 485, 46)],
         tags="us-conlaw,first-amendment,public-concern", grammar_point="Snyder v. Phelps"),
    card("usconlaw-079",
         "A federal statute prohibits corporations from making independent expenditures in political campaigns. Per Supreme Court doctrine, the statute is most likely:",
         [("Constitutional under the Anti-Corruption interest", False),
          ("Unconstitutional as a content-based restriction on political speech", True),
          ("Constitutional under intermediate scrutiny", False),
          ("Constitutional under rational basis review", False)],
         "Citizens United v. FEC (2010) struck down restrictions on corporate independent political expenditures. The Court held that political speech does not lose First Amendment protection 'simply because its source is a corporation.' Independent expenditures (not direct contributions) cannot be restricted based on the speaker's corporate identity; only quid pro quo corruption justifies restrictions on political spending.",
         [cite_scotus("Citizens United v. FEC, 558 U.S. 310 (2010)", 558, 310),
          cite_scotus("Buckley v. Valeo, 424 U.S. 1 (1976)", 424, 1)],
         tags="us-conlaw,first-amendment,political-speech", grammar_point="Citizens United"),
    card("usconlaw-080",
         "A state requires public-sector employees who choose not to join their union to nonetheless pay 'agency fees' to fund collective-bargaining activities. Per recent Supreme Court doctrine, the requirement is:",
         [("Constitutional because the fees fund non-political activities", False),
          ("Unconstitutional as compelled subsidization of speech", True),
          ("Constitutional only with affirmative employee opt-out", False),
          ("Subject to rational basis review", False)],
         "Janus v. AFSCME (2018) overruled Abood v. Detroit Bd. of Educ. (1977) and held that public-sector agency fees violate the First Amendment as compelled subsidization of speech. Public-employee unions' speech on collective-bargaining matters is inherently political (involving public expenditures and policy). Employees must affirmatively opt IN, not out, of supporting union activities.",
         [cite_scotus("Janus v. AFSCME, 585 U.S. 878 (2018)", 585, 878),
          cite_scotus("Abood v. Detroit Bd. of Education, 431 U.S. 209 (1977)", 431, 209)],
         tags="us-conlaw,first-amendment,compelled-speech", grammar_point="Janus v. AFSCME"),
    card("usconlaw-081",
         "A custom-website designer refuses to design wedding websites for same-sex couples on religious grounds, in conflict with a state public-accommodation law. Per recent Supreme Court doctrine, the law as applied to the designer is most likely:",
         [("Constitutional under generally-applicable anti-discrimination law", False),
          ("Unconstitutional as compelling pure speech (custom expressive products)", True),
          ("Subject to rational basis review", False),
          ("Constitutional only if narrowly tailored", False)],
         "303 Creative LLC v. Elenis (2023) held that public-accommodation laws cannot compel a website designer to create CUSTOM expressive content (websites with bespoke speech) that violates her sincerely held beliefs. The Court framed this as compelled-speech doctrine: the state cannot force a speaker to convey messages she disagrees with through her own creative expression.",
         [cite_scotus("303 Creative LLC v. Elenis, 600 U.S. 570 (2023)", 600, 570),
          cite_scotus("Wooley v. Maynard, 430 U.S. 705 (1977)", 430, 705)],
         tags="us-conlaw,first-amendment,compelled-speech", grammar_point="303 Creative LLC"),
    card("usconlaw-082",
         "A state denies a religious school participation in a generally-available program providing public funds for school playground resurfacing. Per Supreme Court doctrine, the denial is most likely:",
         [("Constitutional under the Establishment Clause", False),
          ("Unconstitutional as religion-based discrimination violating Free Exercise", True),
          ("Constitutional under state Blaine Amendment provisions", False),
          ("Constitutional under rational basis review", False)],
         "Trinity Lutheran Church v. Comer (2017) held that excluding a religious institution from a generally-available secular benefit (playground resurfacing grants) solely because of its religious character violates the Free Exercise Clause. The Court rejected the argument that state Blaine Amendments could justify such exclusion. Espinoza (2020) and Carson (2022) extended this principle.",
         [cite_scotus("Trinity Lutheran Church v. Comer, 582 U.S. 449 (2017)", 582, 449),
          cite_scotus("Espinoza v. Montana Dept. of Revenue, 591 U.S. 464 (2020)", 591, 464)],
         tags="us-conlaw,first-amendment,free-exercise", grammar_point="Trinity Lutheran"),
    card("usconlaw-083",
         "A state provides tuition assistance for students in school districts without their own public schools, but excludes religious schools from the program. Per recent Supreme Court doctrine, the exclusion is:",
         [("Constitutional under the Establishment Clause", False),
          ("Unconstitutional under the Free Exercise Clause", True),
          ("Constitutional under state Blaine Amendment provisions", False),
          ("Constitutional under intermediate scrutiny", False)],
         "Carson v. Makin (2022) held that Maine's exclusion of religious schools from its tuition-assistance program violated the Free Exercise Clause. Once the state offers tuition assistance for private secular schools, it cannot exclude religious schools simply because of their religious nature or because of how they would use the funds. This builds on Trinity Lutheran and Espinoza.",
         [cite_scotus("Carson v. Makin, 596 U.S. 767 (2022)", 596, 767),
          cite_scotus("Espinoza v. Montana Dept. of Revenue, 591 U.S. 464 (2020)", 591, 464)],
         tags="us-conlaw,first-amendment,free-exercise", grammar_point="Carson v. Makin"),
    # ─── EP/DP (6) ─────────────────────────────────────────────────
    card("usconlaw-084",
         "A state law prohibits physician-assisted suicide. A challenge under substantive due process invokes a 'right to die.' Per Supreme Court doctrine, the law is most likely:",
         [("Subject to strict scrutiny", False),
          ("Constitutional under rational basis review because no fundamental right is implicated", True),
          ("Unconstitutional under the Liberty Clause", False),
          ("Subject to intermediate scrutiny", False)],
         "Washington v. Glucksberg (1997) held that physician-assisted suicide is not a fundamental right under substantive due process. The Court applied a methodology requiring (1) a 'careful description' of the asserted right and (2) demonstration that the right is 'deeply rooted in this Nation's history and tradition.' The asserted right to assistance in suicide failed both prongs; rational basis applied.",
         [cite_scotus("Washington v. Glucksberg, 521 U.S. 702 (1997)", 521, 702),
          cite_scotus("Vacco v. Quill, 521 U.S. 793 (1997)", 521, 793)],
         tags="us-conlaw,due-process,fundamental-rights", grammar_point="Glucksberg test"),
    card("usconlaw-085",
         "A state law criminalizes consensual same-sex sexual conduct. Per Supreme Court doctrine, the law is most likely:",
         [("Constitutional under rational basis review", False),
          ("Unconstitutional as violating substantive due process / liberty", True),
          ("Constitutional under the police power", False),
          ("Subject to intermediate scrutiny", False)],
         "Lawrence v. Texas (2003) overruled Bowers v. Hardwick (1986) and struck down Texas's homosexual-conduct statute. The Court held that the Due Process Clause protects intimate consensual sexual conduct between adults from state criminalization. The Court found that 'liberty presumes an autonomy of self that includes... certain intimate conduct.'",
         [cite_scotus("Lawrence v. Texas, 539 U.S. 558 (2003)", 539, 558),
          cite_scotus("Bowers v. Hardwick, 478 U.S. 186 (1986)", 478, 186)],
         tags="us-conlaw,due-process,liberty,sexual-orientation", grammar_point="Lawrence v. Texas"),
    card("usconlaw-086",
         "Section 3 of the Defense of Marriage Act denies federal recognition of state-recognized same-sex marriages. Per Supreme Court doctrine, this provision is:",
         [("Constitutional under the Necessary and Proper Clause", False),
          ("Unconstitutional as denying equal protection / liberty to same-sex couples", True),
          ("Constitutional under federal supremacy", False),
          ("Constitutional under rational basis review", False)],
         "United States v. Windsor (2013) struck down DOMA Section 3, which had denied federal recognition (and federal benefits) to same-sex couples lawfully married under state law. The Court held that the provision was motivated by 'a bare desire to harm a politically unpopular group' and violated the Fifth Amendment's equal-protection component. Obergefell (2015) followed.",
         [cite_scotus("United States v. Windsor, 570 U.S. 744 (2013)", 570, 744),
          cite_scotus("Obergefell v. Hodges, 576 U.S. 644 (2015)", 576, 644)],
         tags="us-conlaw,equal-protection,sexual-orientation", grammar_point="US v. Windsor — DOMA"),
    card("usconlaw-087",
         "A federal statute provides funds for parochial schools' secular educational activities. Historically, the constitutional analysis applied:",
         [("The historical-practices test from Kennedy v. Bremerton", False),
          ("The Lemon test (purpose, effect, entanglement) — now displaced by historical analysis", True),
          ("Strict scrutiny", False),
          ("Rational basis review", False)],
         "Lemon v. Kurtzman (1971) established the three-part Lemon test: (1) secular legislative purpose; (2) primary effect that neither advances nor inhibits religion; (3) no excessive government entanglement with religion. Kennedy v. Bremerton (2022) effectively abandoned Lemon in favor of an historical-practices analysis. The Lemon test is now of historical interest only.",
         [cite_scotus("Lemon v. Kurtzman, 403 U.S. 602 (1971)", 403, 602),
          cite_scotus("Kennedy v. Bremerton School Dist., 597 U.S. 507 (2022)", 597, 507)],
         tags="us-conlaw,first-amendment,establishment", grammar_point="Lemon test (history)"),
    card("usconlaw-088",
         "A state denies free public education to children of undocumented immigrants. Per Supreme Court doctrine, the denial is:",
         [("Constitutional under rational basis review (no suspect class, no fundamental right)", False),
          ("Unconstitutional under intermediate-rational-basis review for laws affecting innocent children", True),
          ("Constitutional under state immigration interest", False),
          ("Subject to strict scrutiny", False)],
         "Plyler v. Doe (1982) struck down a Texas law denying free public education to children of undocumented immigrants. The Court applied a heightened form of rational basis (sometimes called 'rational basis with bite'), recognizing that (1) the children themselves were not responsible for their immigration status and (2) education plays a 'fundamental role in maintaining the fabric of our society.' The state interest in deterring illegal immigration was insufficient.",
         [cite_scotus("Plyler v. Doe, 457 U.S. 202 (1982)", 457, 202),
          cite_scotus("San Antonio Indep. Sch. Dist. v. Rodriguez, 411 U.S. 1 (1973)", 411, 1)],
         tags="us-conlaw,equal-protection,education,immigration", grammar_point="Plyler v. Doe"),
    card("usconlaw-089",
         "A state's school-funding system relies primarily on local property taxes, resulting in significant disparities between districts. The challengers argue that wealth is a suspect classification and education is a fundamental right. Per Supreme Court doctrine, the system is most likely:",
         [("Unconstitutional under strict scrutiny", False),
          ("Constitutional under rational basis review", True),
          ("Subject to intermediate scrutiny", False),
          ("Per se unconstitutional", False)],
         "San Antonio Independent School District v. Rodriguez (1973) held that wealth is NOT a suspect classification and education is NOT a fundamental right under the federal Constitution. The school-funding system was reviewed under rational basis and survived. Education-funding equity claims must proceed under STATE constitutional law (where many state supreme courts have found state-law violations).",
         [cite_scotus("San Antonio Indep. Sch. Dist. v. Rodriguez, 411 U.S. 1 (1973)", 411, 1),
          cite_scotus("Plyler v. Doe, 457 U.S. 202 (1982)", 457, 202)],
         tags="us-conlaw,equal-protection,wealth,education", grammar_point="Rodriguez / wealth + education"),
    # ─── Death Penalty (3) — explicitly requested ─────────────────
    card("usconlaw-090",
         "A state imposes the death penalty under a statute that gives juries complete discretion in deciding whether to impose death or life, with no guiding standards. Per Supreme Court doctrine, the statute is most likely:",
         [("Constitutional as preserving jury discretion", False),
          ("Unconstitutional under the Eighth Amendment as administered", True),
          ("Constitutional under federalism principles", False),
          ("Subject to rational basis review", False)],
         "Furman v. Georgia (1972) struck down then-existing death-penalty statutes as 'cruel and unusual' as administered, due to the unbridled jury discretion that resulted in arbitrary and discriminatory imposition. Furman did not categorically prohibit capital punishment but required that statutes provide guided discretion to ensure rational, non-arbitrary application. Gregg (1976) upheld guided-discretion statutes.",
         [cite_scotus("Furman v. Georgia, 408 U.S. 238 (1972)", 408, 238),
          cite_scotus("Gregg v. Georgia, 428 U.S. 153 (1976)", 428, 153)],
         tags="us-conlaw,eighth-amendment,death-penalty", grammar_point="Furman v. Georgia"),
    card("usconlaw-091",
         "A state's death penalty statute provides a bifurcated guilt/sentencing trial, with specific aggravating and mitigating factors guiding the jury's death-or-life determination. Per Supreme Court doctrine, the statute is most likely:",
         [("Unconstitutional per Furman v. Georgia", False),
          ("Constitutional as providing guided discretion", True),
          ("Subject to strict scrutiny", False),
          ("Constitutional only with appellate proportionality review", False)],
         "Gregg v. Georgia (1976) upheld Georgia's revised death penalty statute, which provided bifurcated trials, specific statutory aggravating factors, jury consideration of mitigating evidence, and automatic appellate review. The Court found these procedural safeguards adequately addressed Furman's concerns about arbitrary application.",
         [cite_scotus("Gregg v. Georgia, 428 U.S. 153 (1976)", 428, 153),
          cite_scotus("Furman v. Georgia, 408 U.S. 238 (1972)", 408, 238)],
         tags="us-conlaw,eighth-amendment,death-penalty", grammar_point="Gregg v. Georgia"),
    card("usconlaw-092",
         "A defendant convicted of capital murder seeks to challenge the death sentence on the ground that he is intellectually disabled (formerly 'mentally retarded'). Per Supreme Court doctrine, the execution is:",
         [("Constitutional because intellectual disability does not bar capital punishment", False),
          ("Unconstitutional under the Eighth Amendment", True),
          ("Constitutional only with reduced safeguards", False),
          ("A matter for state legislative discretion", False)],
         "Atkins v. Virginia (2002) held that executing intellectually disabled persons violates the Eighth Amendment's prohibition on 'cruel and unusual' punishments. The Court relied on 'evolving standards of decency' as reflected in legislative trends and the diminished culpability of intellectually disabled defendants. Hall v. Florida (2014) and Moore v. Texas (2017) clarified the determination of intellectual disability.",
         [cite_scotus("Atkins v. Virginia, 536 U.S. 304 (2002)", 536, 304),
          cite_scotus("Hall v. Florida, 572 U.S. 701 (2014)", 572, 701)],
         tags="us-conlaw,eighth-amendment,death-penalty", grammar_point="Atkins v. Virginia"),
    # ─── 4A/5A/6A criminal procedure (5) ──────────────────────────
    card("usconlaw-093",
         "Police obtain evidence through an unconstitutional search and seek to introduce it at the defendant's STATE criminal trial. Per Supreme Court doctrine, the evidence is most likely:",
         [("Admissible because the exclusionary rule applies only in federal court", False),
          ("Inadmissible under the exclusionary rule, which is incorporated against the states", True),
          ("Admissible under the inevitable discovery doctrine in all cases", False),
          ("Admissible if the police acted in good faith", False)],
         "Mapp v. Ohio (1961) held that the Fourth Amendment's exclusionary rule is incorporated against the states through the Fourteenth Amendment Due Process Clause. Evidence obtained through unconstitutional searches is generally inadmissible in state criminal trials, subject to exceptions (Leon good faith, inevitable discovery, attenuation, etc.).",
         [cite_scotus("Mapp v. Ohio, 367 U.S. 643 (1961)", 367, 643),
          cite_scotus("Wolf v. Colorado, 338 U.S. 25 (1949)", 338, 25)],
         tags="us-conlaw,fourth-amendment,exclusionary-rule", grammar_point="Mapp v. Ohio"),
    card("usconlaw-094",
         "A police officer with reasonable suspicion that a person is armed and dangerous and engaged in criminal activity briefly detains and pat-down searches the person. Per Supreme Court doctrine, this is:",
         [("Unconstitutional without probable cause and a warrant", False),
          ("Constitutional under the Terry stop-and-frisk doctrine", True),
          ("Constitutional only with consent", False),
          ("Constitutional only after arrest", False)],
         "Terry v. Ohio (1968) established that a brief investigative stop and pat-down search is constitutional if the officer has REASONABLE SUSPICION (less than probable cause) that (1) criminal activity is afoot AND (2) the suspect is armed and dangerous. The pat-down (frisk) is limited in scope to weapons. Terry stops are a major Fourth Amendment exception to the warrant/probable-cause requirement.",
         [cite_scotus("Terry v. Ohio, 392 U.S. 1 (1968)", 392, 1),
          cite_scotus("Florida v. J.L., 529 U.S. 266 (2000)", 529, 266)],
         tags="us-conlaw,fourth-amendment,terry-stop", grammar_point="Terry v. Ohio"),
    card("usconlaw-095",
         "A criminal defendant claims his trial counsel was constitutionally ineffective. Per Supreme Court doctrine, to succeed the defendant must show:",
         [("That counsel failed to win the case", False),
          ("Both deficient performance AND prejudice (reasonable probability of different outcome)", True),
          ("That counsel was not licensed", False),
          ("That the conviction was based on insufficient evidence", False)],
         "Strickland v. Washington (1984) established the two-prong test for ineffective-assistance-of-counsel claims: (1) DEFICIENT PERFORMANCE — counsel's representation fell below an objective standard of reasonableness; AND (2) PREJUDICE — a reasonable probability that, but for counsel's deficient performance, the result would have been different. Both prongs must be satisfied; courts give strong deference to counsel's strategic choices.",
         [cite_scotus("Strickland v. Washington, 466 U.S. 668 (1984)", 466, 668),
          cite_scotus("Padilla v. Kentucky, 559 U.S. 356 (2010)", 559, 356)],
         tags="us-conlaw,sixth-amendment,counsel", grammar_point="Strickland v. Washington"),
    card("usconlaw-096",
         "At voir dire, a prosecutor uses peremptory challenges to strike all Black potential jurors. The defendant (also Black) objects. Per Supreme Court doctrine, the prosecutor must:",
         [("Provide a written explanation to the court", False),
          ("Provide a race-neutral explanation, which the court evaluates for pretext", True),
          ("Use peremptory challenges only for cause", False),
          ("Give equal numbers of challenges to all races", False)],
         "Batson v. Kentucky (1986) established a three-step framework: (1) defendant makes a prima facie showing of race-based discrimination; (2) prosecutor must offer a race-neutral explanation; (3) the court determines whether the defendant has shown purposeful discrimination, evaluating whether the explanation is pretext. Batson has been extended to gender (J.E.B.) and to civil cases (Edmonson).",
         [cite_scotus("Batson v. Kentucky, 476 U.S. 79 (1986)", 476, 79),
          cite_scotus("J.E.B. v. Alabama ex rel. T.B., 511 U.S. 127 (1994)", 511, 127)],
         tags="us-conlaw,equal-protection,jury-selection", grammar_point="Batson challenges"),
    card("usconlaw-097",
         "A state convicts a defendant of a serious crime by a 10-2 jury vote. Per recent Supreme Court doctrine, the conviction is:",
         [("Constitutional because state may set its own jury rules", False),
          ("Unconstitutional under the Sixth Amendment as incorporated against states", True),
          ("Constitutional only with the defendant's waiver of unanimity", False),
          ("Subject to harmless-error review", False)],
         "Ramos v. Louisiana (2020) held that the Sixth Amendment requires unanimous jury verdicts for serious offenses, and this requirement is incorporated against the states. The Court overruled Apodaca v. Oregon (1972) (which had allowed non-unanimous state-court verdicts). Edwards v. Vannoy (2021) held that Ramos is not retroactive on collateral review.",
         [cite_scotus("Ramos v. Louisiana, 590 U.S. 83 (2020)", 590, 83),
          cite_scotus("Apodaca v. Oregon, 406 U.S. 404 (1972)", 406, 404)],
         tags="us-conlaw,sixth-amendment,jury-trial", grammar_point="Ramos v. Louisiana"),
    # ─── 8A (3) — explicitly requested ────────────────────────────
    card("usconlaw-098",
         "A state imposes the death penalty on a defendant who was 17 years old at the time of the offense. Per Supreme Court doctrine, the execution is most likely:",
         [("Constitutional because the defendant was tried as an adult", False),
          ("Unconstitutional under the Eighth Amendment", True),
          ("Constitutional with parental notification", False),
          ("Constitutional only after appellate review", False)],
         "Roper v. Simmons (2005) held that the Eighth Amendment prohibits execution of those who were under 18 at the time of their crime. The Court relied on 'evolving standards of decency,' diminished culpability of juveniles (immaturity, susceptibility to peer pressure, less-developed character), and international consensus. Miller v. Alabama (2012) extended this approach to mandatory life-without-parole for juveniles.",
         [cite_scotus("Roper v. Simmons, 543 U.S. 551 (2005)", 543, 551),
          cite_scotus("Miller v. Alabama, 567 U.S. 460 (2012)", 567, 460)],
         tags="us-conlaw,eighth-amendment,death-penalty,juveniles", grammar_point="Roper v. Simmons"),
    card("usconlaw-099",
         "A state uses an IQ score above 70 as a categorical bar to claims of intellectual disability in capital cases. Per Supreme Court doctrine, this rule is:",
         [("Constitutional as a bright-line evidentiary standard", False),
          ("Unconstitutional because it ignores the standard error of measurement and clinical judgment", True),
          ("Constitutional under federalism principles", False),
          ("Subject to rational basis review", False)],
         "Hall v. Florida (2014) struck down Florida's strict IQ-score cutoff (70) for intellectual disability determinations in capital cases. The Court held that scientific consensus requires considering the standard error of measurement (typically ±5 points) and adaptive functioning. Moore v. Texas (2017) further required courts to use current medical standards rather than outdated stereotypes.",
         [cite_scotus("Hall v. Florida, 572 U.S. 701 (2014)", 572, 701),
          cite_scotus("Moore v. Texas, 581 U.S. 1 (2017)", 581, 1)],
         tags="us-conlaw,eighth-amendment,death-penalty", grammar_point="Hall v. Florida"),
    card("usconlaw-100",
         "A death-row inmate challenges the state's lethal-injection protocol as causing severe pain. Per Supreme Court doctrine, to prevail he generally must show:",
         [("That the protocol causes any pain at all", False),
          ("A substantial risk of severe pain AND a feasible, less painful alternative", True),
          ("That lethal injection is per se unconstitutional", False),
          ("That capital punishment violates evolving standards of decency", False)],
         "Bucklew v. Precythe (2019) reaffirmed Glossip v. Gross (2015): a death-row inmate challenging an execution method must show (1) the method is sure or very likely to cause severe pain AND (2) a known and available alternative that significantly reduces a substantial risk of severe pain. The mere fact that execution causes some pain does not violate the Eighth Amendment.",
         [cite_scotus("Bucklew v. Precythe, 587 U.S. 119 (2019)", 587, 119),
          cite_scotus("Glossip v. Gross, 576 U.S. 863 (2015)", 576, 863)],
         tags="us-conlaw,eighth-amendment,death-penalty", grammar_point="Bucklew v. Precythe"),
]


def main():
    data = json.loads(CARDS_PATH.read_text(encoding="utf-8"))
    cards = data["cards"]
    by_id = {c["id"]: c for c in cards}

    # 1. Backfill citations on the existing 50.
    backfilled = 0
    for cid, cites in BACKFILL.items():
        if cid in by_id:
            by_id[cid]["citations"] = cites
            backfilled += 1

    # 2. Append the 50 new cards.
    existing_ids = set(by_id.keys())
    added = 0
    for card_dict in NEW_CARDS:
        if card_dict["id"] not in existing_ids:
            cards.append(card_dict)
            added += 1

    # 3. Atomic write.
    tmp = CARDS_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps({"cards": cards}, ensure_ascii=False, indent=2) + "\n",
                   encoding="utf-8")
    tmp.replace(CARDS_PATH)

    print(f"Backfilled citations on {backfilled} existing cards.")
    print(f"Added {added} new cards. Total cards now: {len(cards)}.")


if __name__ == "__main__":
    main()
