"""PR #4 (v0.4) — keiko-engine ConLaw + URL-policy fix.

Two things:
  1. Replace ALL citation URLs in cards.json with Google search URLs.
     Justia's per-case page URL pattern doesn't work for every case
     (especially recent slip-ops where the U.S. Reports volume hasn't
     been published yet — 先輩 saw "Page not found" on a Justia link).
     Google search is guaranteed to surface the leading hit (SCOTUS
     opinion, Justia, Cornell LII, Wikipedia summary, all available).
  2. Add 50 NEW validated us-conlaw cards (cards 101-150) per the
     standing rule in CLAUDE.md §5.2.

Run from repo root:
    python scripts\\add_pr4_cards_and_google_urls.py
"""
from __future__ import annotations

import json
from pathlib import Path
from urllib.parse import quote_plus

CARDS_PATH = Path(__file__).resolve().parent.parent / "src" / "main" / "resources" / "subjects" / "us-conlaw" / "cards.json"


def google_url(label: str) -> str:
    """Build a Google search URL for a citation label. Guaranteed to
    resolve to *something* relevant — usually the SCOTUS opinion on
    supremecourt.gov, Justia, Cornell LII, or Wikipedia summary."""
    return f"https://www.google.com/search?q={quote_plus(label)}"


def cite_scotus(label: str) -> dict:
    return {"label": label, "url": google_url(label), "type": "scotus"}


def cite_circuit(label: str) -> dict:
    return {"label": label, "url": google_url(label), "type": "circuit"}


def cite_lr(label: str) -> dict:
    return {"label": label, "url": google_url(label), "type": "law-review"}


def card(id_, stem, choices_with_correct, explanation, citations,
         tags="us-conlaw", grammar_point="", difficulty=3):
    return {
        "id": id_, "kind": "grammar", "level": "",
        "stem": stem, "grammar_point": grammar_point,
        "choices": [{"text": t, "is_correct": c} for t, c in choices_with_correct],
        "translation_zh_tw": "", "translation_zh_cn": "", "translation_en": "",
        "explanation": explanation, "difficulty": difficulty, "tags": tags,
        "source": "claude-authored-may-2026",
        "provenance": "human_curated",
        "attribution": "Claude PR #4 (validated bank). Awaiting expert review.",
        "citations": citations,
    }


# 50 NEW cards, cards 101-150.
NEW_CARDS = [
    # ─── Voting Rights / Federalism continued (8) ────────────────
    card("usconlaw-101",
         "Section 5 of the Voting Rights Act required certain jurisdictions to obtain federal preclearance before changing voting laws. Per recent Supreme Court doctrine, the formula determining which jurisdictions are covered is:",
         [("Constitutional under the 15A enforcement power", False),
          ("Unconstitutional because the coverage formula is based on outdated data", True),
          ("Constitutional only with congressional re-authorization", False),
          ("Subject to rational basis review", False)],
         "Shelby County v. Holder (2013) struck down VRA § 4(b) (the coverage formula). The Court held that Congress's 1965 formula, last meaningfully updated in the 1970s, was no longer responsive to current conditions and violated the equal sovereignty of states. § 5 itself remains on the books but is functionally inoperative without a coverage formula.",
         [cite_scotus("Shelby County v. Holder, 570 U.S. 529 (2013)"),
          cite_scotus("South Carolina v. Katzenbach, 383 U.S. 301 (1966)")],
         tags="us-conlaw,voting-rights", grammar_point="Shelby County v. Holder"),
    card("usconlaw-102",
         "A federal court is asked to adjudicate a claim that a state's congressional redistricting was unconstitutionally partisan. Per recent Supreme Court doctrine, the claim presents:",
         [("A justiciable equal-protection question", False),
          ("A non-justiciable political question", True),
          ("A 1A association claim subject to strict scrutiny", False),
          ("A standing problem only", False)],
         "Rucho v. Common Cause (2019) held that partisan gerrymandering claims present non-justiciable political questions. The Court found no judicially manageable standard for distinguishing acceptable from excessive partisanship. State courts and state constitutions remain available avenues; federal racial gerrymandering claims (Shaw v. Reno line) remain justiciable.",
         [cite_scotus("Rucho v. Common Cause, 588 U.S. 684 (2019)"),
          cite_scotus("Vieth v. Jubelirer, 541 U.S. 267 (2004)")],
         tags="us-conlaw,voting-rights,political-question", grammar_point="Rucho v. Common Cause"),
    card("usconlaw-103",
         "A state's apportionment scheme weights rural districts more than urban districts of comparable population. Per Supreme Court doctrine, the scheme is most likely:",
         [("Constitutional under federalism principles", False),
          ("Unconstitutional under one-person-one-vote", True),
          ("Subject to rational basis review only", False),
          ("Constitutional under the political question doctrine", False)],
         "Reynolds v. Sims (1964) held that state legislative districts must be apportioned on a substantially equal-population basis under the Equal Protection Clause — 'one person, one vote.' Wesberry v. Sanders (1964) applied the same principle to congressional districting under Article I § 2.",
         [cite_scotus("Reynolds v. Sims, 377 U.S. 533 (1964)"),
          cite_scotus("Wesberry v. Sanders, 376 U.S. 1 (1964)")],
         tags="us-conlaw,voting-rights,one-person-one-vote", grammar_point="Reynolds v. Sims"),
    card("usconlaw-104",
         "In a presidential election dispute, a state supreme court orders a manual recount that uses inconsistent standards across counties. Per Supreme Court doctrine, the recount most likely:",
         [("Is constitutional under state sovereignty", False),
          ("Violates equal protection due to inconsistent standards", True),
          ("Is a non-justiciable political question", False),
          ("Is constitutional under the Necessary and Proper Clause", False)],
         "Bush v. Gore (2000) held that the Florida recount violated equal protection because different counties used different standards for evaluating ballots, leading to disparate treatment of similarly situated voters. The decision was expressly limited to the unique circumstances; subsequent recount-procedure challenges typically rely on different doctrines.",
         [cite_scotus("Bush v. Gore, 531 U.S. 98 (2000)"),
          cite_lr("Texas Law Review — Bush v. Gore scholarship")],
         tags="us-conlaw,voting-rights,equal-protection", grammar_point="Bush v. Gore"),
    card("usconlaw-105",
         "A state requires voters to present photo ID at the polls. Indigent voters lacking ID can obtain one for free with proper documentation. Per Supreme Court doctrine, the requirement is most likely:",
         [("Subject to strict scrutiny because voting is a fundamental right", False),
          ("Constitutional under the state's interest in preventing fraud and maintaining voter confidence", True),
          ("Per se unconstitutional under the 24A poll-tax prohibition", False),
          ("Subject to intermediate scrutiny", False)],
         "Crawford v. Marion County Election Board (2008) upheld Indiana's voter-ID law against a facial challenge. The Court applied the Anderson-Burdick balancing test (state's regulatory interest weighed against the burden on voters), finding the burden minimal for most voters and the state's interest in preventing fraud and maintaining electoral confidence sufficient.",
         [cite_scotus("Crawford v. Marion County Election Bd., 553 U.S. 181 (2008)"),
          cite_scotus("Anderson v. Celebrezze, 460 U.S. 780 (1983)")],
         tags="us-conlaw,voting-rights,equal-protection", grammar_point="Crawford v. Marion County"),
    card("usconlaw-106",
         "A state legislature passes congressional redistricting that the state supreme court invalidates as a violation of state constitutional law. Per recent Supreme Court doctrine, the federal Elections Clause:",
         [("Vests exclusive authority in state legislatures, immune from state-court review", False),
          ("Permits state-court review of state legislatures' election regulations", True),
          ("Requires automatic federal-court appeal", False),
          ("Preempts all state constitutional law", False)],
         "Moore v. Harper (2023) rejected the strong form of the 'independent state legislature' theory. State legislatures' authority under the Elections Clause is subject to state-constitutional limits and state-court review, though federal courts retain a narrow role in policing state-court overreach. State legislatures are not 'independent' of state constitutions in regulating federal elections.",
         [cite_scotus("Moore v. Harper, 600 U.S. 1 (2023)"),
          cite_scotus("Bush v. Gore, 531 U.S. 98 (2000) (Rehnquist concurrence raising ISL theory)")],
         tags="us-conlaw,voting-rights,elections-clause", grammar_point="Moore v. Harper"),
    card("usconlaw-107",
         "The Commerce Department adds a citizenship question to the decennial census, providing a stated rationale. Per Supreme Court doctrine, the agency's action is reviewed under:",
         [("Strict scrutiny because the census affects voting rights", False),
          ("Arbitrary-and-capricious review under the APA, including pretext analysis", True),
          ("Rational basis review with strong deference", False),
          ("The political question doctrine", False)],
         "Department of Commerce v. New York (2019) blocked the addition of a citizenship question to the 2020 census, finding the Commerce Secretary's stated rationale was pretextual. The Court applied APA arbitrary-and-capricious review and held that an agency's stated reasons must be the actual reasons; pretextual decision-making fails APA review.",
         [cite_scotus("Department of Commerce v. New York, 588 U.S. 752 (2019)"),
          cite_scotus("Citizens to Preserve Overton Park v. Volpe, 401 U.S. 402 (1971)")],
         tags="us-conlaw,admin-law,census", grammar_point="Dept. of Commerce v. NY"),
    card("usconlaw-108",
         "A state purges from its voter rolls registrants who haven't voted in two consecutive federal elections and who fail to respond to a notice. Per Supreme Court doctrine, this purge process is:",
         [("Per se unconstitutional under the National Voter Registration Act", False),
          ("Constitutional under the NVRA's failure-to-vote-plus-failure-to-respond procedure", True),
          ("Subject to strict scrutiny", False),
          ("Unconstitutional under the 24A", False)],
         "Husted v. APRI (2018) upheld Ohio's voter-purge process. The NVRA prohibits removal solely for failure to vote, but permits removal of registrants who fail to vote AND fail to respond to a forwardable notice over a multi-year period. The Court found Ohio's process compliant with NVRA's two-part requirement.",
         [cite_scotus("Husted v. A. Philip Randolph Institute, 584 U.S. 756 (2018)")],
         tags="us-conlaw,voting-rights,nvra", grammar_point="Husted v. APRI"),
    # ─── 14A Incorporation / Substantive (5) ─────────────────────
    card("usconlaw-109",
         "A city ordinance restricts handgun possession by residents in their homes. The challenger asserts a 2A right enforceable against the city. Per Supreme Court doctrine, the 2A is:",
         [("Not applicable to states under the original 14A jurisprudence", False),
          ("Incorporated against states and localities through the 14A Due Process Clause", True),
          ("Incorporated through the 14A Privileges or Immunities Clause", False),
          ("A federal-only protection", False)],
         "McDonald v. City of Chicago (2010) held that the Second Amendment is incorporated against the states through the Fourteenth Amendment Due Process Clause (plurality) or Privileges or Immunities Clause (Justice Thomas concurring). The 2A protects an individual right (Heller) that is fundamental to the American scheme of ordered liberty.",
         [cite_scotus("McDonald v. City of Chicago, 561 U.S. 742 (2010)"),
          cite_scotus("District of Columbia v. Heller, 554 U.S. 570 (2008)")],
         tags="us-conlaw,14a,2a-incorporation", grammar_point="McDonald v. Chicago"),
    card("usconlaw-110",
         "A state denies jury trial in a criminal case carrying a maximum sentence of two years' imprisonment. Per Supreme Court doctrine, the denial is most likely:",
         [("Constitutional because jury trial is a federal-only right", False),
          ("Unconstitutional under the 6A as incorporated by the 14A", True),
          ("Constitutional with appropriate procedural safeguards", False),
          ("Subject to harmless-error review", False)],
         "Duncan v. Louisiana (1968) held that the Sixth Amendment right to jury trial in serious criminal cases is incorporated against the states through the Fourteenth Amendment. Serious offenses are those punishable by imprisonment exceeding six months (Baldwin v. New York). Two-year maximum clearly qualifies.",
         [cite_scotus("Duncan v. Louisiana, 391 U.S. 145 (1968)"),
          cite_scotus("Baldwin v. New York, 399 U.S. 66 (1970)")],
         tags="us-conlaw,14a,6a-incorporation,jury-trial", grammar_point="Duncan v. Louisiana"),
    card("usconlaw-111",
         "A state law restricts certain economic privileges to a single corporate entity. The challenger invokes the 14A Privileges or Immunities Clause. Per longstanding Supreme Court doctrine, the clause:",
         [("Provides robust protection of all civil rights against state action", False),
          ("Has been narrowly construed to protect only privileges of national citizenship (Slaughter-House)", True),
          ("Has been overruled by subsequent decisions", False),
          ("Provides the same protection as the Equal Protection Clause", False)],
         "The Slaughter-House Cases (1873) narrowly construed the 14A Privileges or Immunities Clause to protect only privileges of NATIONAL citizenship (e.g., access to federal officials, navigable waterways). Most civil-rights protection moved to the Due Process and Equal Protection Clauses. Saenz v. Roe (1999) revived a narrow P&I role for the right to travel.",
         [cite_scotus("Slaughter-House Cases, 83 U.S. (16 Wall.) 36 (1873)"),
          cite_scotus("Saenz v. Roe, 526 U.S. 489 (1999)")],
         tags="us-conlaw,14a,privileges-immunities", grammar_point="Slaughter-House Cases"),
    card("usconlaw-112",
         "A state restricts welfare benefits for new residents (less than one year in state) to the lower of either the new state's or the prior state's benefit level. Per Supreme Court doctrine, the restriction is most likely:",
         [("Constitutional under the state's fiscal interest", False),
          ("Unconstitutional as burdening the right to interstate travel", True),
          ("Subject to rational basis review", False),
          ("Constitutional if applied uniformly", False)],
         "Saenz v. Roe (1999) struck down California's welfare differential for new residents under the 14A Privileges or Immunities Clause. The right to travel — including the right of new residents to be treated equally with longer-term residents — is a privilege of national citizenship. The state's fiscal interest was insufficient to justify the durational discrimination.",
         [cite_scotus("Saenz v. Roe, 526 U.S. 489 (1999)"),
          cite_scotus("Shapiro v. Thompson, 394 U.S. 618 (1969)")],
         tags="us-conlaw,14a,right-to-travel", grammar_point="Saenz v. Roe"),
    card("usconlaw-113",
         "A state law mandates sterilization for habitual criminals convicted of certain felonies. Per Supreme Court doctrine, the law is most likely:",
         [("Constitutional under rational basis review", False),
          ("Unconstitutional as violating equal protection because procreation is a fundamental right", True),
          ("Constitutional under the state's police power", False),
          ("Subject to intermediate scrutiny", False)],
         "Skinner v. Oklahoma (1942) struck down a state's sterilization-of-habitual-criminals law. The Court applied strict scrutiny because procreation is 'one of the basic civil rights of man.' The law's distinction between offenses (e.g., chicken stealing was covered, but embezzlement was not) failed strict scrutiny. This case foreshadowed substantive-due-process protection of intimate decisions.",
         [cite_scotus("Skinner v. Oklahoma, 316 U.S. 535 (1942)"),
          cite_scotus("Buck v. Bell, 274 U.S. 200 (1927) (older eugenics-era case)")],
         tags="us-conlaw,14a,fundamental-rights", grammar_point="Skinner v. Oklahoma"),
    # ─── 1A Speech (8) ───────────────────────────────────────────
    card("usconlaw-114",
         "A public official sues a newspaper for defamation based on a critical article. Per Supreme Court doctrine, the official must prove the statement was made with:",
         [("Negligence as to truth", False),
          ("Actual malice (knowledge of falsity or reckless disregard)", True),
          ("Mere falsity", False),
          ("Intent to harm reputation", False)],
         "New York Times Co. v. Sullivan (1964) held that public officials suing for defamation regarding their official conduct must prove ACTUAL MALICE — knowledge that the statement was false OR reckless disregard for whether it was false. The high standard reflects the 1A's protection of robust criticism of government. Curtis Publishing extended Sullivan to public figures.",
         [cite_scotus("New York Times Co. v. Sullivan, 376 U.S. 254 (1964)"),
          cite_scotus("Curtis Publishing Co. v. Butts, 388 U.S. 130 (1967)")],
         tags="us-conlaw,first-amendment,defamation", grammar_point="NY Times v. Sullivan"),
    card("usconlaw-115",
         "A federal statute criminalizes distribution of obscene materials. Per Supreme Court doctrine, material is obscene if:",
         [("It depicts nudity", False),
          ("It satisfies the three-part Miller test (prurient interest, patently offensive, lacks SLAPS value)", True),
          ("It would offend a reasonable observer", False),
          ("It is sexually explicit", False)],
         "Miller v. California (1973) established the three-part obscenity test: (1) whether the average person, applying contemporary community standards, would find the work appeals to the prurient interest; (2) whether it depicts sexual conduct in a patently offensive way as defined by state law; (3) whether the work, taken as a whole, lacks serious literary, artistic, political, or scientific value (SLAPS). Obscenity is unprotected speech.",
         [cite_scotus("Miller v. California, 413 U.S. 15 (1973)"),
          cite_scotus("Roth v. United States, 354 U.S. 476 (1957)")],
         tags="us-conlaw,first-amendment,obscenity", grammar_point="Miller test"),
    card("usconlaw-116",
         "A defendant uses 'fighting words' directly to a police officer. The state prosecutes under a fighting-words statute. Per Supreme Court doctrine, the statute is constitutional if:",
         [("It punishes speech that offends listeners", False),
          ("It punishes face-to-face words likely to provoke an immediate breach of the peace", True),
          ("It punishes any insulting language", False),
          ("It punishes vulgar language in public", False)],
         "Chaplinsky v. New Hampshire (1942) recognized 'fighting words' as a category of unprotected speech: face-to-face words that 'by their very utterance inflict injury or tend to incite an immediate breach of the peace.' The doctrine has been narrowly construed in subsequent cases (Cohen v. California, 1971; Texas v. Johnson, 1989).",
         [cite_scotus("Chaplinsky v. New Hampshire, 315 U.S. 568 (1942)"),
          cite_scotus("Cohen v. California, 403 U.S. 15 (1971)")],
         tags="us-conlaw,first-amendment,fighting-words", grammar_point="Chaplinsky / fighting words"),
    card("usconlaw-117",
         "A defendant burns an American flag at a political protest. The state prosecutes under a flag-desecration statute. Per Supreme Court doctrine, the prosecution is most likely:",
         [("Constitutional under the state's interest in protecting national symbols", False),
          ("Unconstitutional as suppression of expressive conduct", True),
          ("Constitutional under the O'Brien test", False),
          ("Subject to rational basis review", False)],
         "Texas v. Johnson (1989) struck down Texas's flag-desecration statute as applied to political flag-burning. The Court held that flag-burning is expressive conduct, and the state's interest in preserving the flag as a symbol was insufficient to justify suppressing political expression. United States v. Eichman (1990) struck down a similar federal statute.",
         [cite_scotus("Texas v. Johnson, 491 U.S. 397 (1989)"),
          cite_scotus("United States v. Eichman, 496 U.S. 310 (1990)")],
         tags="us-conlaw,first-amendment,symbolic-speech", grammar_point="Texas v. Johnson"),
    card("usconlaw-118",
         "A city ordinance prohibits 'hate speech' that conveys messages of racial, religious, or gender hostility. Per Supreme Court doctrine, the ordinance is most likely:",
         [("Constitutional under the fighting-words doctrine", False),
          ("Unconstitutional as content-based discrimination among unprotected speech categories", True),
          ("Constitutional under the state's anti-discrimination interest", False),
          ("Subject to intermediate scrutiny", False)],
         "R.A.V. v. City of St. Paul (1992) struck down a hate-speech ordinance that selectively criminalized 'fighting words' based on the topic of the message. Even within unprotected speech categories, the government may not engage in CONTENT-BASED or VIEWPOINT-BASED discrimination. The ordinance forbade hostile messages on race, religion, gender — but not on union membership, sexual orientation, etc.",
         [cite_scotus("R.A.V. v. City of St. Paul, 505 U.S. 377 (1992)"),
          cite_scotus("Virginia v. Black, 538 U.S. 343 (2003)")],
         tags="us-conlaw,first-amendment,hate-speech", grammar_point="R.A.V. v. St. Paul"),
    card("usconlaw-119",
         "A state criminalizes cross-burning with intent to intimidate. Per Supreme Court doctrine, the statute is:",
         [("Per se unconstitutional under R.A.V.", False),
          ("Constitutional as prohibiting true threats, but not when prima facie evidence of intent is presumed", True),
          ("Constitutional under any circumstances", False),
          ("Constitutional under fighting-words doctrine", False)],
         "Virginia v. Black (2003) held that states may criminalize cross-burning when done with INTENT TO INTIMIDATE, because cross-burning with intimidation intent constitutes a 'true threat' (unprotected speech). However, statutes that treat the act of cross-burning itself as PRIMA FACIE EVIDENCE of intent to intimidate violate the 1A by chilling protected expressive cross-burning.",
         [cite_scotus("Virginia v. Black, 538 U.S. 343 (2003)"),
          cite_scotus("R.A.V. v. City of St. Paul, 505 U.S. 377 (1992)")],
         tags="us-conlaw,first-amendment,true-threats", grammar_point="Virginia v. Black"),
    card("usconlaw-120",
         "A government employee is disciplined for statements made pursuant to her official duties. Per Supreme Court doctrine, the speech receives:",
         [("Strict scrutiny because government employment cannot be conditioned on giving up speech rights", False),
          ("No 1A protection — speech made pursuant to official duties is not citizen speech", True),
          ("The Pickering balancing test", False),
          ("Intermediate scrutiny", False)],
         "Garcetti v. Ceballos (2006) held that when public employees speak PURSUANT TO THEIR OFFICIAL DUTIES, they speak as employees not citizens, and the 1A does not protect them from discipline. This narrows Pickering v. Board of Education (1968), which protects public-employee speech on matters of public concern made AS A CITIZEN. Lane v. Franks (2014) clarified that subpoenaed truthful sworn testimony outside ordinary job duties is protected.",
         [cite_scotus("Garcetti v. Ceballos, 547 U.S. 410 (2006)"),
          cite_scotus("Pickering v. Board of Education, 391 U.S. 563 (1968)")],
         tags="us-conlaw,first-amendment,public-employee-speech", grammar_point="Garcetti v. Ceballos"),
    card("usconlaw-121",
         "A public school teacher writes a letter to a newspaper criticizing the school board's allocation of funds. The board fires her. Per Supreme Court doctrine, the firing is most likely:",
         [("Constitutional under the school board's hiring discretion", False),
          ("Unconstitutional under the Pickering balancing test", True),
          ("Constitutional under Garcetti v. Ceballos", False),
          ("Subject to rational basis review", False)],
         "Pickering v. Board of Education (1968) established balancing for public-employee speech AS A CITIZEN on matters of public concern. The court balances the employee's 1A interest against the employer's interest in efficient public service. The teacher's letter on funding allocation was protected because it addressed a matter of public concern, did not impair workplace relationships, and the employer's interest was minimal.",
         [cite_scotus("Pickering v. Board of Education, 391 U.S. 563 (1968)"),
          cite_scotus("Connick v. Myers, 461 U.S. 138 (1983)")],
         tags="us-conlaw,first-amendment,public-employee-speech", grammar_point="Pickering balancing"),
    # ─── 1A Religion (5) ─────────────────────────────────────────
    card("usconlaw-122",
         "A state legislature opens each session with a prayer by a state-paid chaplain. Per Supreme Court doctrine, the practice is:",
         [("Per se unconstitutional under the Establishment Clause", False),
          ("Constitutional under historical-practices analysis", True),
          ("Subject to strict scrutiny", False),
          ("Constitutional only if non-denominational", False)],
         "Marsh v. Chambers (1983) upheld Nebraska's legislative-chaplain practice based on the unbroken tradition of legislative prayer dating to the First Congress, which had paid chaplains while drafting the 1A. Town of Greece v. Galloway (2014) extended this analysis to municipal-board prayers, applying historical-practices analysis (anticipating Kennedy v. Bremerton's later framework).",
         [cite_scotus("Marsh v. Chambers, 463 U.S. 783 (1983)"),
          cite_scotus("Town of Greece v. Galloway, 572 U.S. 565 (2014)")],
         tags="us-conlaw,first-amendment,establishment", grammar_point="Marsh v. Chambers"),
    card("usconlaw-123",
         "A town opens public board meetings with a sectarian prayer, with prayer-givers drawn from local clergy of various faiths. Per recent Supreme Court doctrine, the practice is:",
         [("Per se unconstitutional under the Establishment Clause", False),
          ("Constitutional under historical-practices analysis", True),
          ("Constitutional only with non-sectarian prayers", False),
          ("Subject to strict scrutiny", False)],
         "Town of Greece v. Galloway (2014) upheld the practice of opening municipal-board meetings with sectarian prayer, applying Marsh's historical-practices analysis. The Court rejected requirements that prayers be non-sectarian; the relevant question is whether the prayers fit within historical American practice, not their theological content.",
         [cite_scotus("Town of Greece v. Galloway, 572 U.S. 565 (2014)"),
          cite_scotus("Marsh v. Chambers, 463 U.S. 783 (1983)")],
         tags="us-conlaw,first-amendment,establishment", grammar_point="Town of Greece"),
    card("usconlaw-124",
         "A federal statute requires employers to provide health insurance covering contraception. A closely-held for-profit corporation refuses on religious grounds, invoking RFRA. Per Supreme Court doctrine, the corporation:",
         [("Cannot exercise religion because it is a corporation", False),
          ("May exercise religion under RFRA, requiring strict scrutiny of the burden", True),
          ("Cannot use RFRA to evade neutral generally-applicable laws", False),
          ("Subject to rational basis review", False)],
         "Burwell v. Hobby Lobby Stores (2014) held that closely-held for-profit corporations are 'persons' under RFRA capable of exercising religion. The contraceptive mandate substantially burdened the corporation's religious exercise; while the government's interest in contraceptive access was compelling, less-restrictive alternatives existed (the accommodation already extended to religious nonprofits). Strict scrutiny under RFRA failed.",
         [cite_scotus("Burwell v. Hobby Lobby Stores, 573 U.S. 682 (2014)"),
          cite_scotus("City of Boerne v. Flores, 521 U.S. 507 (1997)")],
         tags="us-conlaw,first-amendment,rfra", grammar_point="Hobby Lobby"),
    card("usconlaw-125",
         "A state provides scholarships for students pursuing higher education but excludes students pursuing devotional theology degrees. Per Supreme Court doctrine, the exclusion is:",
         [("Per se unconstitutional under Free Exercise (Espinoza)", False),
          ("Constitutional under historical state-establishment-clause concerns about funding clergy training", True),
          ("Subject to strict scrutiny", False),
          ("Unconstitutional under Trinity Lutheran", False)],
         "Locke v. Davey (2004) upheld Washington State's exclusion of devotional-theology degrees from a generally-available scholarship program. The Court found the exclusion permissible because Washington was neither requiring religious adherence nor punishing religious belief; it was merely declining to fund clergy training, an area of historical state-establishment concern. Trinity Lutheran (2017) and Espinoza (2020) limited Locke to its narrow context.",
         [cite_scotus("Locke v. Davey, 540 U.S. 712 (2004)"),
          cite_scotus("Espinoza v. Montana Dept. of Revenue, 591 U.S. 464 (2020)")],
         tags="us-conlaw,first-amendment,free-exercise,funding", grammar_point="Locke v. Davey"),
    card("usconlaw-126",
         "A state's scholarship program for private K-12 schools excludes religious schools based on a state Blaine Amendment. Per recent Supreme Court doctrine, the exclusion is:",
         [("Constitutional under the state Blaine Amendment", False),
          ("Unconstitutional under Free Exercise — Blaine Amendments cannot justify religion-based exclusion from generally-available programs", True),
          ("Subject to strict scrutiny", False),
          ("Constitutional only if applied uniformly", False)],
         "Espinoza v. Montana Dept. of Revenue (2020) struck down Montana's exclusion of religious private schools from a generally-available tax-credit scholarship program. The Court held that disqualifying schools based solely on their religious character violates Free Exercise. Carson v. Makin (2022) extended this to direct tuition-assistance programs.",
         [cite_scotus("Espinoza v. Montana Dept. of Revenue, 591 U.S. 464 (2020)"),
          cite_scotus("Carson v. Makin, 596 U.S. 767 (2022)")],
         tags="us-conlaw,first-amendment,free-exercise,blaine", grammar_point="Espinoza v. Montana"),
    # ─── EP — Sex / LGBT / Race (6) ──────────────────────────────
    card("usconlaw-127",
         "A state law prefers males over females as administrators of decedent's estates. Per Supreme Court doctrine, the preference is reviewed under:",
         [("Strict scrutiny", False),
          ("At least rational basis with bite, the early sex-discrimination level", True),
          ("Pure rational basis review", False),
          ("Strict scrutiny because sex is a suspect classification", False)],
         "Reed v. Reed (1971) was the first Supreme Court case to strike down a sex-based classification under the EP Clause. The Court applied a heightened version of rational basis (not yet labeled intermediate scrutiny), finding the male-preference statute lacked a fair and substantial relation to its administrative-convenience justification. Craig v. Boren (1976) later formalized intermediate scrutiny.",
         [cite_scotus("Reed v. Reed, 404 U.S. 71 (1971)"),
          cite_scotus("Craig v. Boren, 429 U.S. 190 (1976)")],
         tags="us-conlaw,equal-protection,sex", grammar_point="Reed v. Reed"),
    card("usconlaw-128",
         "A federal statute provides automatic spousal benefits to wives of male servicemembers but requires female servicemembers to prove their husbands' dependency. Per Supreme Court doctrine, the differential treatment is:",
         [("Constitutional under military deference", False),
          ("Unconstitutional under heightened EP scrutiny", True),
          ("Subject to rational basis only", False),
          ("Constitutional under administrative convenience", False)],
         "Frontiero v. Richardson (1973) struck down the differential spousal-benefits scheme. A plurality would have applied strict scrutiny to sex classifications; the Court ultimately settled on intermediate scrutiny in Craig v. Boren (1976). Frontiero set the trajectory toward heightened review for sex-based classifications.",
         [cite_scotus("Frontiero v. Richardson, 411 U.S. 677 (1973)"),
          cite_scotus("Craig v. Boren, 429 U.S. 190 (1976)")],
         tags="us-conlaw,equal-protection,sex", grammar_point="Frontiero v. Richardson"),
    card("usconlaw-129",
         "A state nursing school admits only women, citing the goal of compensating for women's historical underrepresentation in nursing. Per Supreme Court doctrine, the male-exclusionary admission policy is:",
         [("Constitutional under intermediate scrutiny because the justification is compensatory", False),
          ("Unconstitutional because the asserted compensatory rationale is not exceedingly persuasive given that nursing is female-dominated", True),
          ("Subject to rational basis review", False),
          ("Constitutional under educational deference", False)],
         "Mississippi University for Women v. Hogan (1982) struck down MUW's male-exclusionary nursing admission policy. The state's claimed remedial justification (compensating for women's underrepresentation) failed because nursing is in fact female-dominated; the exclusion perpetuated rather than corrected stereotypes. United States v. Virginia (1996) reaffirmed the 'exceedingly persuasive justification' standard.",
         [cite_scotus("Mississippi University for Women v. Hogan, 458 U.S. 718 (1982)"),
          cite_scotus("United States v. Virginia, 518 U.S. 515 (1996)")],
         tags="us-conlaw,equal-protection,sex", grammar_point="MUW v. Hogan"),
    card("usconlaw-130",
         "A state constitutional amendment prohibits all anti-discrimination protections for LGBT individuals at the state and local level. Per Supreme Court doctrine, the amendment is:",
         [("Constitutional under federalism", False),
          ("Unconstitutional under Equal Protection — bare animus is not a legitimate state interest", True),
          ("Subject to rational basis review", False),
          ("Constitutional under the political-question doctrine", False)],
         "Romer v. Evans (1996) struck down Colorado's Amendment 2, which prohibited any anti-discrimination protections for LGBT individuals. The Court applied rational basis review but found that 'bare animus toward a politically unpopular group' is not a legitimate state interest. The breadth of the disability and the lack of any rational basis other than animus rendered the amendment unconstitutional.",
         [cite_scotus("Romer v. Evans, 517 U.S. 620 (1996)"),
          cite_scotus("Lawrence v. Texas, 539 U.S. 558 (2003)")],
         tags="us-conlaw,equal-protection,sexual-orientation", grammar_point="Romer v. Evans"),
    card("usconlaw-131",
         "An ordinance facially neutral about race is administered to deny laundry-business permits exclusively to Chinese applicants. Per Supreme Court doctrine, the discriminatory administration is:",
         [("Constitutional because the ordinance is facially neutral", False),
          ("Unconstitutional under Equal Protection because facially neutral law applied with discriminatory intent violates EP", True),
          ("Subject to rational basis only", False),
          ("Constitutional because business regulation is a state matter", False)],
         "Yick Wo v. Hopkins (1886) established that facially neutral laws applied with discriminatory intent violate Equal Protection. The Court found the city had granted nearly all non-Chinese applicants and denied nearly all Chinese applicants — pattern evidence of discriminatory administration. Yick Wo is foundational for proving EP violations through DISPARATE TREATMENT despite facial neutrality.",
         [cite_scotus("Yick Wo v. Hopkins, 118 U.S. 356 (1886)"),
          cite_scotus("Washington v. Davis, 426 U.S. 229 (1976)")],
         tags="us-conlaw,equal-protection,race", grammar_point="Yick Wo v. Hopkins"),
    card("usconlaw-132",
         "Under Title VII (statutory), an employer fires a worker for being gay. Per recent Supreme Court doctrine, the firing:",
         [("Is permitted because Title VII does not cover sexual orientation", False),
          ("Violates Title VII's prohibition on sex discrimination", True),
          ("Is governed by state law only", False),
          ("Requires strict scrutiny analysis", False)],
         "Bostock v. Clayton County (2020) held that Title VII's prohibition on sex discrimination encompasses discrimination based on sexual orientation and gender identity. Discharging an employee for being gay or transgender necessarily takes sex into account: the employer would not have fired a woman for being attracted to men, but did fire the male employee for being attracted to men.",
         [cite_scotus("Bostock v. Clayton County, 590 U.S. 644 (2020)")],
         tags="us-conlaw,statutory,title-vii,equal-protection", grammar_point="Bostock v. Clayton County"),
    # ─── Criminal procedure (8) ──────────────────────────────────
    card("usconlaw-133",
         "The prosecution withholds evidence favorable to the defense and material to guilt or punishment. The defendant later discovers the suppression. Per Supreme Court doctrine, the suppression:",
         [("Has no constitutional consequence absent bad faith", False),
          ("Violates due process and warrants relief if material to guilt or punishment", True),
          ("Is constitutional if the prosecution did not personally know", False),
          ("Is governed by harmless-error review only", False)],
         "Brady v. Maryland (1963) held that prosecution's suppression of evidence favorable to the accused violates due process if the evidence is material either to guilt or to punishment. Materiality is defined as a reasonable probability that the result would have been different (Bagley/Kyles standard). Brady applies to all evidence in the prosecution team's possession (Kyles v. Whitley).",
         [cite_scotus("Brady v. Maryland, 373 U.S. 83 (1963)"),
          cite_scotus("Kyles v. Whitley, 514 U.S. 419 (1995)")],
         tags="us-conlaw,5a,due-process,brady", grammar_point="Brady v. Maryland"),
    card("usconlaw-134",
         "Police arrest a suspect for a serious offense and collect a DNA cheek-swab incident to booking. Per Supreme Court doctrine, the swab is:",
         [("A search requiring a warrant", False),
          ("A constitutional search incident to arrest under reasonableness balancing", True),
          ("Per se unconstitutional", False),
          ("Constitutional only with consent", False)],
         "Maryland v. King (2013) upheld DNA cheek-swab collection from arrestees for serious offenses, applying a totality-of-circumstances reasonableness analysis. The Court found the intrusion minimal and the state's interest in identification compelling. The decision was 5-4; concerns about expansion to less-serious offenses persist.",
         [cite_scotus("Maryland v. King, 569 U.S. 435 (2013)")],
         tags="us-conlaw,fourth-amendment,dna", grammar_point="Maryland v. King"),
    card("usconlaw-135",
         "Police bring a drug-detection dog onto the front porch of a private home to sniff for drugs without a warrant. Per Supreme Court doctrine, the action is:",
         [("Not a Fourth Amendment search because dog sniffs reveal only contraband", False),
          ("A Fourth Amendment search because it physically intrudes on the curtilage", True),
          ("Constitutional under the plain-smell doctrine", False),
          ("Constitutional under the open-fields doctrine", False)],
         "Florida v. Jardines (2013) held that bringing a drug-detection dog to the front porch of a home is a Fourth Amendment SEARCH. The porch is part of the curtilage (protected area), and society does not implicitly license trained drug-detection dogs to investigate private homes. The Court relied on the property-trespass theory of Jones, not just Katz reasonable expectations.",
         [cite_scotus("Florida v. Jardines, 569 U.S. 1 (2013)"),
          cite_scotus("United States v. Jones, 565 U.S. 400 (2012)")],
         tags="us-conlaw,fourth-amendment,curtilage", grammar_point="Florida v. Jardines"),
    card("usconlaw-136",
         "A police officer stops a vehicle based on his reasonable but mistaken belief that the driver violated the law. Per Supreme Court doctrine, evidence found during the stop is:",
         [("Inadmissible because there was no actual violation", False),
          ("Admissible if the officer's mistake of law was OBJECTIVELY REASONABLE", True),
          ("Admissible only if the officer acted in subjective good faith", False),
          ("Inadmissible per se", False)],
         "Heien v. North Carolina (2014) held that an officer's REASONABLE mistake of law can support a Fourth Amendment stop. The officer mistakenly believed state law required two functioning brake lights; in fact, only one was required. Because the statute was ambiguous and the mistake objectively reasonable, the stop and resulting evidence were upheld.",
         [cite_scotus("Heien v. North Carolina, 574 U.S. 54 (2014)")],
         tags="us-conlaw,fourth-amendment,mistake-of-law", grammar_point="Heien v. North Carolina"),
    card("usconlaw-137",
         "Police arrest a vehicle's driver and secure him in the patrol car, then search the passenger compartment. Per Supreme Court doctrine, the search is:",
         [("Constitutional under any search-incident-to-arrest", False),
          ("Constitutional only if the arrestee could access the vehicle OR there is reason to believe evidence of the crime of arrest is in the vehicle", True),
          ("Constitutional under the automobile exception always", False),
          ("Per se unconstitutional", False)],
         "Arizona v. Gant (2009) limited the search-incident-to-arrest doctrine for vehicles. Police may search a vehicle's passenger compartment incident to arrest only if (1) the arrestee is unsecured and within reaching distance OR (2) it is reasonable to believe the vehicle contains evidence of the offense of arrest. Gant rejected New York v. Belton's broader bright-line rule.",
         [cite_scotus("Arizona v. Gant, 556 U.S. 332 (2009)"),
          cite_scotus("New York v. Belton, 453 U.S. 454 (1981)")],
         tags="us-conlaw,fourth-amendment,vehicle-search", grammar_point="Arizona v. Gant"),
    card("usconlaw-138",
         "A criminal defendant insists on representing himself at trial despite the trial court's determination that counsel would serve him better. Per Supreme Court doctrine, the defendant has:",
         [("No right to self-representation; the court may impose counsel", False),
          ("A 6A right to self-representation if the waiver of counsel is knowing and intelligent", True),
          ("A right only after consulting with counsel", False),
          ("A right limited to misdemeanor cases", False)],
         "Faretta v. California (1975) recognized a Sixth Amendment right to self-representation in criminal cases, provided the defendant's waiver of counsel is knowing, intelligent, and voluntary. The court must conduct a thorough colloquy. Indiana v. Edwards (2008) held that mentally-ill defendants competent to stand trial may nonetheless be denied self-representation if mental illness compromises their ability to conduct trial proceedings.",
         [cite_scotus("Faretta v. California, 422 U.S. 806 (1975)"),
          cite_scotus("Indiana v. Edwards, 554 U.S. 164 (2008)")],
         tags="us-conlaw,sixth-amendment,counsel", grammar_point="Faretta v. California"),
    card("usconlaw-139",
         "A noncitizen criminal defendant pleads guilty without being advised that the conviction will trigger automatic deportation. Per Supreme Court doctrine, the failure to advise is:",
         [("Not ineffective assistance because deportation is a collateral consequence", False),
          ("Ineffective assistance under Strickland's deficient-performance prong", True),
          ("Constitutional if defense counsel was generally competent", False),
          ("Subject to harmless-error review without plea-vacation", False)],
         "Padilla v. Kentucky (2010) held that defense counsel must advise a noncitizen client that a guilty plea carries a risk of deportation. Even though deportation was previously considered a 'collateral consequence,' the integral relationship between immigration consequences and modern criminal sentencing makes such advice constitutionally required under Strickland.",
         [cite_scotus("Padilla v. Kentucky, 559 U.S. 356 (2010)"),
          cite_scotus("Strickland v. Washington, 466 U.S. 668 (1984)")],
         tags="us-conlaw,sixth-amendment,counsel,immigration", grammar_point="Padilla v. Kentucky"),
    card("usconlaw-140",
         "Police stop a vehicle for a traffic violation. The passenger (not the driver) seeks to challenge the stop's legality at his own subsequent prosecution. Per Supreme Court doctrine, the passenger:",
         [("Lacks Fourth Amendment standing because he is not the driver", False),
          ("Has Fourth Amendment standing as a person seized by the stop", True),
          ("Has standing only if he owns the vehicle", False),
          ("Has no remedy under the exclusionary rule", False)],
         "Brendlin v. California (2007) held that a vehicle passenger is SEIZED for Fourth Amendment purposes when police stop the vehicle. Therefore, the passenger has standing to challenge the stop's legality, and evidence obtained as a result of an unlawful stop may be suppressed against the passenger as well as the driver.",
         [cite_scotus("Brendlin v. California, 551 U.S. 249 (2007)")],
         tags="us-conlaw,fourth-amendment,seizure,standing", grammar_point="Brendlin v. California"),
    # ─── Procedural Due Process — Punitive damages (3) ───────────
    card("usconlaw-141",
         "A state court awards $4 million in punitive damages on $4,000 in compensatory damages — a 1000:1 ratio. Per Supreme Court doctrine, the award is most likely:",
         [("Constitutional because punitive damages are within state discretion", False),
          ("Unconstitutional as a violation of substantive due process for being excessively disproportionate", True),
          ("Constitutional only with appellate review", False),
          ("Subject to rational basis review", False)],
         "BMW of North America v. Gore (1996) established three guideposts for evaluating constitutionally excessive punitive damages: (1) degree of reprehensibility; (2) ratio of punitive to compensatory damages; (3) sanctions for comparable misconduct. State Farm v. Campbell (2003) suggested ratios exceeding single digits would rarely satisfy due process. The 1000:1 ratio almost certainly fails.",
         [cite_scotus("BMW of North America v. Gore, 517 U.S. 559 (1996)"),
          cite_scotus("State Farm Mut. Auto. Ins. Co. v. Campbell, 538 U.S. 408 (2003)")],
         tags="us-conlaw,due-process,punitive-damages", grammar_point="BMW v. Gore"),
    card("usconlaw-142",
         "A jury awards $145 million punitive damages on $1 million compensatory damages — a 145:1 ratio. Per Supreme Court doctrine, the award is most likely:",
         [("Constitutional because punitive damages reflect community values", False),
          ("Unconstitutional because the ratio exceeds single-digit guidance", True),
          ("Subject only to state-law remittitur", False),
          ("Constitutional under the state's tort-deterrence interest", False)],
         "State Farm Mutual Auto Insurance Co. v. Campbell (2003) refined BMW v. Gore. The Court suggested that 'few awards exceeding a single-digit ratio between punitive and compensatory damages, to a significant degree, will satisfy due process.' A 145:1 ratio almost certainly fails. Cooper Industries v. Leatherman Tool established de novo appellate review of the constitutional question.",
         [cite_scotus("State Farm Mut. Auto. Ins. Co. v. Campbell, 538 U.S. 408 (2003)"),
          cite_scotus("BMW of North America v. Gore, 517 U.S. 559 (1996)")],
         tags="us-conlaw,due-process,punitive-damages", grammar_point="State Farm v. Campbell"),
    card("usconlaw-143",
         "A state requires sex offenders to register publicly. A registrant challenges the registration, arguing he is entitled to a hearing on his current dangerousness before being listed. Per Supreme Court doctrine, the procedural due process claim is most likely:",
         [("Sustained because registration imposes a stigma on liberty interest", False),
          ("Rejected because the registration scheme is based on conviction status, not current dangerousness", True),
          ("Sustained because registration affects employment and housing", False),
          ("Subject to strict scrutiny", False)],
         "Connecticut Dept. of Public Safety v. Doe (2003) rejected a procedural-due-process challenge to Megan's Law-style registration. The Court held that the statute's prerequisites (conviction of qualifying offenses) — not current dangerousness — were the operative factual predicates. Because the law required no individualized determination of dangerousness, no hearing was due on that question.",
         [cite_scotus("Connecticut Dept. of Public Safety v. Doe, 538 U.S. 1 (2003)"),
          cite_scotus("Smith v. Doe, 538 U.S. 84 (2003) (companion case on Ex Post Facto)")],
         tags="us-conlaw,due-process,procedural,sex-offender", grammar_point="Conn. DPS v. Doe"),
    # ─── Federal Courts — Personal Jurisdiction (4) ──────────────
    card("usconlaw-144",
         "A plaintiff sues in federal court asserting one federal-question claim and one closely related state-law claim against the same defendant. The federal court's authority to hear the state-law claim is grounded in:",
         [("Diversity jurisdiction only", False),
          ("Supplemental jurisdiction (28 U.S.C. § 1367)", True),
          ("Independent federal-question jurisdiction", False),
          ("State-court abstention", False)],
         "28 U.S.C. § 1367 codifies SUPPLEMENTAL JURISDICTION (formerly pendent and ancillary jurisdiction). Federal courts may hear state-law claims that form part of the same case or controversy as a federal-question claim, subject to discretionary declination grounds. Exxon Mobil v. Allapattah (2005) clarified application in diversity cases.",
         [cite_scotus("Exxon Mobil Corp. v. Allapattah Services, 545 U.S. 546 (2005)"),
          cite_scotus("United Mine Workers v. Gibbs, 383 U.S. 715 (1966)")],
         tags="us-conlaw,fed-courts,jurisdiction", grammar_point="Supplemental jurisdiction § 1367"),
    card("usconlaw-145",
         "A state court asserts personal jurisdiction over a non-resident defendant who has no contacts with the state. Per longstanding Supreme Court doctrine, the assertion is:",
         [("Constitutional under state sovereignty", False),
          ("Unconstitutional under the Due Process Clause requiring minimum contacts", True),
          ("Constitutional with notice", False),
          ("Constitutional under the Full Faith and Credit Clause", False)],
         "Pennoyer v. Neff (1878) established that personal jurisdiction is constrained by Fourteenth Amendment Due Process. International Shoe v. Washington (1945) reformulated this as the 'minimum contacts' test: defendants must have such minimum contacts with the forum that exercising jurisdiction does not offend traditional notions of fair play and substantial justice.",
         [cite_scotus("Pennoyer v. Neff, 95 U.S. 714 (1878)"),
          cite_scotus("International Shoe Co. v. Washington, 326 U.S. 310 (1945)")],
         tags="us-conlaw,fed-courts,personal-jurisdiction", grammar_point="Pennoyer v. Neff"),
    card("usconlaw-146",
         "A state court asserts personal jurisdiction over a defendant whose contacts with the forum are limited but who purposefully availed itself of the forum. Per Supreme Court doctrine, the analysis applies:",
         [("Pennoyer's territorial test", False),
          ("International Shoe's minimum contacts test", True),
          ("Strict scrutiny", False),
          ("Rational basis review", False)],
         "International Shoe Co. v. Washington (1945) is the foundational personal-jurisdiction case. Specific jurisdiction requires (1) purposeful availment of the forum + (2) the claim arising out of or relating to the contacts + (3) reasonableness/fair play. World-Wide Volkswagen, Burger King, and J. McIntyre Machinery refined the doctrine.",
         [cite_scotus("International Shoe Co. v. Washington, 326 U.S. 310 (1945)"),
          cite_scotus("World-Wide Volkswagen Corp. v. Woodson, 444 U.S. 286 (1980)")],
         tags="us-conlaw,fed-courts,personal-jurisdiction", grammar_point="International Shoe"),
    card("usconlaw-147",
         "A foreign corporation is sued in a state where it has only sporadic, attenuated contacts unrelated to the suit. Per recent Supreme Court doctrine, GENERAL personal jurisdiction is most likely:",
         [("Constitutional under the contacts-plus test", False),
          ("Unconstitutional because the corporation is not 'at home' in the forum", True),
          ("Constitutional under purposeful availment", False),
          ("Subject to rational basis review", False)],
         "Daimler AG v. Bauman (2014) substantially narrowed general personal jurisdiction over corporations. A corporation is generally 'at home' only in its (1) state of incorporation and (2) principal place of business. Continuous and systematic contacts that are not so 'continuous and systematic as to render the corporation essentially at home' do not support general jurisdiction.",
         [cite_scotus("Daimler AG v. Bauman, 571 U.S. 117 (2014)"),
          cite_scotus("Goodyear Dunlop Tires Operations v. Brown, 564 U.S. 915 (2011)")],
         tags="us-conlaw,fed-courts,personal-jurisdiction", grammar_point="Daimler AG v. Bauman"),
    # ─── Recent / Other (3) ──────────────────────────────────────
    card("usconlaw-148",
         "EPA asserts authority to regulate as 'Waters of the United States' all wetlands with a 'significant nexus' to traditional navigable waters. Per recent Supreme Court doctrine, the assertion is most likely:",
         [("Constitutional under the Commerce Clause", False),
          ("Unconstitutional as exceeding the Clean Water Act's coverage of wetlands with continuous surface connection to navigable waters", True),
          ("Constitutional under the Necessary and Proper Clause", False),
          ("Subject to rational basis review", False)],
         "Sackett v. EPA (2023) narrowed CWA jurisdiction over wetlands. The Court rejected the 'significant nexus' test (associated with Justice Kennedy's Rapanos concurrence) and held that 'Waters of the United States' include only wetlands with a continuous surface connection to traditional navigable waters. The decision substantially limited EPA/Corps regulatory reach.",
         [cite_scotus("Sackett v. EPA, 598 U.S. 651 (2023)"),
          cite_scotus("Rapanos v. United States, 547 U.S. 715 (2006)")],
         tags="us-conlaw,admin-law,environmental", grammar_point="Sackett v. EPA"),
    card("usconlaw-149",
         "Congress imposes a one-time 'transition tax' on accumulated foreign earnings of U.S. shareholders, attributing the foreign corporations' income to the shareholders. Per recent Supreme Court doctrine, the tax is:",
         [("Unconstitutional under the 16A as taxing unrealized gain", False),
          ("Constitutional because the tax attributes corporate income to shareholders, which is consistent with prior pass-through taxation", True),
          ("Constitutional only as a wealth tax", False),
          ("Subject to strict scrutiny", False)],
         "Moore v. United States (2024) upheld the Mandatory Repatriation Tax (a transition tax under the 2017 TCJA). The Court held that the tax was constitutional as an attribution of corporate income to shareholders, a long-recognized form of pass-through taxation. The decision avoided broader questions about whether income must be 'realized' to be taxable under the 16A.",
         [cite_scotus("Moore v. United States, 602 U.S. 572 (2024)")],
         tags="us-conlaw,16a,taxation", grammar_point="Moore v. United States (16A)"),
    card("usconlaw-150",
         "A state's law restricting medication abortion based on FDA-approved protocol changes is challenged in federal court. The plaintiffs are physicians who object to the FDA's relaxed protocols. Per recent Supreme Court doctrine, the standing analysis turns on:",
         [("The physicians' moral or aesthetic objections to providing abortion", False),
          ("Whether the physicians can show concrete and particularized injury from the FDA's actions", True),
          ("Whether the FDA's actions affect the public interest", False),
          ("Public-citizen standing under the APA", False)],
         "FDA v. Alliance for Hippocratic Medicine (2024) held that the physician-plaintiffs lacked Article III standing to challenge the FDA's mifepristone-protocol relaxation. The plaintiffs' theories of injury (conscience-burden, increased emergency-room workload, professional risk) were too speculative to satisfy injury-in-fact requirements. The case did not reach the merits of the regulatory challenge.",
         [cite_scotus("FDA v. Alliance for Hippocratic Medicine, 602 U.S. 367 (2024)"),
          cite_scotus("Lujan v. Defenders of Wildlife, 504 U.S. 555 (1992)")],
         tags="us-conlaw,standing,fda", grammar_point="FDA v. Alliance for Hippocratic Medicine"),
]


def main():
    data = json.loads(CARDS_PATH.read_text(encoding="utf-8"))
    cards = data["cards"]

    # 1. Replace ALL existing citation URLs with Google search URLs.
    rewritten = 0
    for c in cards:
        cites = c.get("citations") or []
        for cite in cites:
            label = cite.get("label", "")
            if label:
                cite["url"] = google_url(label)
                rewritten += 1

    # 2. Append the 50 new cards (with Google search URLs from the start).
    existing_ids = {c["id"] for c in cards}
    added = 0
    for card_dict in NEW_CARDS:
        if card_dict["id"] not in existing_ids:
            cards.append(card_dict)
            added += 1

    # 3. Atomic write.
    tmp = CARDS_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps({"cards": cards}, ensure_ascii=False, indent=2) + "\n",
                   encoding="utf-8")
    tmp.replace(CARDS_PATH)

    print(f"Rewrote {rewritten} citation URLs to Google search format.")
    print(f"Added {added} new cards. Total cards now: {len(cards)}.")


if __name__ == "__main__":
    main()
