"""PR #7 (v0.7) -- 50 NEW validated us-conlaw cards (251-300) under the
standing rule (CLAUDE.md sec 5.2). Topic mix per sec 5.2:
  Federalism (8), Fed Courts/Justiciability (6), State sovereignty (4),
  Sep of powers (8), 1A (7), EP/DP (6), Death penalty (3),
  4A/5A/6A (5), 8A (3) = 50.

Run from repo root:
    python scripts\\add_pr7_cards.py
"""
from __future__ import annotations

import json
from pathlib import Path
from urllib.parse import quote_plus

CARDS_PATH = Path(__file__).resolve().parent.parent / "src" / "main" / "resources" / "subjects" / "us-conlaw" / "cards.json"


def google_url(label: str) -> str:
    return f"https://www.google.com/search?q={quote_plus(label)}"


def cite_scotus(label: str) -> dict:
    return {"label": label, "url": google_url(label), "type": "scotus"}


def cite_circuit(label: str) -> dict:
    return {"label": label, "url": google_url(label), "type": "circuit"}


def cite_lr(label: str) -> dict:
    return {"label": label, "url": google_url(label), "type": "law-review"}


def card(id_, stem, choices_with_correct, explanation, citations,
         tags="us-conlaw", grammar_point="", difficulty=3):
    return {
        "id": id_, "kind": "grammar", "level": "",
        "stem": stem, "grammar_point": grammar_point,
        "choices": [{"text": t, "is_correct": c} for t, c in choices_with_correct],
        "translation_zh_tw": "", "translation_zh_cn": "", "translation_en": "",
        "explanation": explanation, "difficulty": difficulty, "tags": tags,
        "source": "claude-authored-may-2026",
        "provenance": "human_curated",
        "attribution": "Claude PR #7 (validated bank). Awaiting expert review.",
        "citations": citations,
    }


NEW_CARDS = [
    # --- Federalism / DCC (8) ----------------------------------
    card("usconlaw-251",
         "A state, acting in its proprietary capacity, refuses to sell state-owned cement to out-of-state buyers. Per Supreme Court doctrine, the refusal is:",
         [("Unconstitutional under the Dormant Commerce Clause", False),
          ("Constitutional under the market-participant exception", True),
          ("Subject to Pike balancing", False),
          ("Subject to strict scrutiny", False)],
         "Reeves v. Stake (1980) and White v. Massachusetts Council of Construction Employers (1983) recognize the MARKET PARTICIPANT EXCEPTION to the Dormant Commerce Clause: when a state acts as a participant in the market (buyer or seller of its own goods/services) rather than as a regulator, it is not constrained by the DCC. Limit: South-Central Timber Development v. Wunnicke (1984) confines the exception to the immediate transaction; downstream restrictions face DCC scrutiny.",
         [cite_scotus("Reeves Inc. v. Stake, 447 U.S. 429 (1980)"),
          cite_scotus("South-Central Timber Development v. Wunnicke, 467 U.S. 82 (1984)")],
         tags="us-conlaw,federalism,dormant-commerce-clause,market-participant", grammar_point="Reeves market-participant"),
    card("usconlaw-252",
         "A state law applies evenhandedly to in-state and out-of-state commerce but imposes some incidental burden on interstate commerce. Per Supreme Court doctrine, the law's validity is determined by:",
         [("Strict scrutiny", False),
          ("Pike balancing -- the law is valid unless the burden on interstate commerce is clearly excessive in relation to local benefits", True),
          ("Per se invalidity", False),
          ("Rational basis review only", False)],
         "Pike v. Bruce Church (1970) supplied the canonical balancing test for nondiscriminatory state laws affecting interstate commerce: the law is valid unless the BURDEN on interstate commerce is CLEARLY EXCESSIVE in relation to the putative LOCAL BENEFITS. Recent applications: National Pork Producers Council v. Ross (2023) reaffirmed Pike but emphasized that mere extraterritorial economic effects do not constitute prohibited regulation of out-of-state conduct.",
         [cite_scotus("Pike v. Bruce Church Inc., 397 U.S. 137 (1970)"),
          cite_scotus("National Pork Producers Council v. Ross, 598 U.S. 356 (2023)")],
         tags="us-conlaw,federalism,dormant-commerce-clause,pike", grammar_point="Pike balancing"),
    card("usconlaw-253",
         "A state requires out-of-state internet retailers without physical presence to collect state sales tax on sales to in-state customers. Per Supreme Court doctrine post-Wayfair, the requirement is:",
         [("Per se invalid under Quill's physical-presence rule", False),
          ("Constitutional -- substantial economic and virtual nexus suffices for sales-tax collection", True),
          ("Subject to strict scrutiny", False),
          ("Constitutional only with congressional authorization", False)],
         "South Dakota v. Wayfair (2018) overruled Quill v. North Dakota (1992) and National Bellas Hess (1967), abandoning the physical-presence rule for state sales-tax collection. The Court held that SUBSTANTIAL VIRTUAL/ECONOMIC NEXUS (e.g., $100,000 sales OR 200 transactions per year in the state) suffices to require remote sellers to collect sales tax under the Dormant Commerce Clause's Complete Auto framework.",
         [cite_scotus("South Dakota v. Wayfair Inc., 585 U.S. 162 (2018)"),
          cite_scotus("Complete Auto Transit v. Brady, 430 U.S. 274 (1977)")],
         tags="us-conlaw,federalism,dormant-commerce-clause,nexus", grammar_point="Wayfair v. South Dakota"),
    card("usconlaw-254",
         "Congress regulates an activity that is, in the aggregate, economic but locally non-commercial (e.g., personal-use marijuana cultivation in compliance with state law). Per Supreme Court doctrine, the regulation is:",
         [("Beyond Congress's commerce power under Lopez", False),
          ("Within the commerce power under Wickard's aggregation principle as applied in Raich", True),
          ("Constitutional only under the Necessary and Proper Clause", False),
          ("Subject to political-question doctrine", False)],
         "Gonzales v. Raich (2005) upheld federal CSA enforcement against a California medical-marijuana grower complying with state law. The Court applied Wickard v. Filburn (1942) aggregation: Congress may regulate purely local economic activity (cultivation IS economic, distinct from gun possession in Lopez) when the cumulative effect substantially affects interstate commerce. Raich is the modern outer limit: economic local activity stays in.",
         [cite_scotus("Gonzales v. Raich, 545 U.S. 1 (2005)"),
          cite_scotus("Wickard v. Filburn, 317 U.S. 111 (1942)")],
         tags="us-conlaw,federalism,commerce-clause,aggregation", grammar_point="Raich / Wickard aggregation"),
    card("usconlaw-255",
         "Congress imposes a tax on a class of importers, with proceeds dedicated to a specific federal program. Per Supreme Court doctrine, the tax must:",
         [("Be apportioned among the states by population", False),
          ("Not exceed the cost of regulation", False),
          ("Be uniform throughout the United States (Art. I sec 8 cl. 1) -- the constitutional limit on indirect taxes", True),
          ("Be authorized by the President", False)],
         "Article I sec 8 cl. 1 limits federal duties, imposts, and excises to UNIFORMITY throughout the United States. Direct taxes (other than income taxes per the 16A) must be APPORTIONED among the states by population (Art. I sec 9 cl. 4). Murphy v. NCAA, NFIB v. Sebelius, and Bailey v. Drexel Furniture together delineate the boundary between regulatory taxes (constitutional) and regulatory penalties (potentially unconstitutional commandeering or beyond-power).",
         [cite_scotus("NFIB v. Sebelius, 567 U.S. 519 (2012)"),
          cite_scotus("Bailey v. Drexel Furniture Co., 259 U.S. 20 (1922)")],
         tags="us-conlaw,federalism,taxing-power", grammar_point="Uniformity Clause"),
    card("usconlaw-256",
         "Congress passes the Family and Medical Leave Act, requiring states to provide unpaid family leave to employees, and abrogates state sovereign immunity for damages actions. Per Supreme Court doctrine, the abrogation is:",
         [("Invalid under Boerne", False),
          ("Valid under 14A sec 5 -- the FMLA's family-care provision is congruent and proportional to documented sex-discrimination injuries by states", True),
          ("Valid under the Commerce Clause (overriding 11A)", False),
          ("Subject to strict scrutiny", False)],
         "Nevada Dept. of Human Resources v. Hibbs (2003) upheld FMLA's abrogation of state sovereign immunity for the FAMILY-CARE provision. Sex classifications receive intermediate scrutiny, and Congress documented a pattern of state-fostered gender stereotypes about caregiving -- making the FMLA's family-care provision congruent and proportional under Boerne. Coleman v. Court of Appeals (2012) struck down FMLA's SELF-CARE provision under the same test.",
         [cite_scotus("Nevada Dept. of Human Resources v. Hibbs, 538 U.S. 721 (2003)"),
          cite_scotus("Coleman v. Court of Appeals of Maryland, 566 U.S. 30 (2012)")],
         tags="us-conlaw,federalism,abrogation,boerne", grammar_point="Hibbs v. Nevada"),
    card("usconlaw-257",
         "Congress, citing 14A sec 5, abrogates state sovereign immunity for ADA Title II claims as applied to courthouse access. Per Supreme Court doctrine, the abrogation is:",
         [("Invalid in all applications", False),
          ("Valid as applied to fundamental right of court access -- congruent and proportional given documented exclusion of disabled persons from courthouses", True),
          ("Valid only for non-monetary relief", False),
          ("Constitutional under the Commerce Clause", False)],
         "Tennessee v. Lane (2004) upheld ADA Title II's abrogation as applied to courthouse access. Although Garrett (2001) struck Title I's abrogation, Lane held that COURT ACCESS implicates the FUNDAMENTAL RIGHT to access courts (heightened scrutiny). Combined with the documented record of state exclusion of disabled persons from courts, the abrogation was congruent and proportional under Boerne. United States v. Georgia (2006) extended this to actual constitutional violations themselves.",
         [cite_scotus("Tennessee v. Lane, 541 U.S. 509 (2004)"),
          cite_scotus("United States v. Georgia, 546 U.S. 151 (2006)"),
          cite_scotus("Bd. of Trustees of Univ. of Alabama v. Garrett, 531 U.S. 356 (2001)")],
         tags="us-conlaw,federalism,abrogation,ada", grammar_point="Tennessee v. Lane"),
    card("usconlaw-258",
         "Congress regulates wages and hours of state and municipal employees engaged in traditional government functions. Per Supreme Court doctrine, the regulation is:",
         [("Unconstitutional as commandeering of state employment", False),
          ("Constitutional -- the FLSA's application to state employees is a valid exercise of the Commerce Clause", True),
          ("Subject to anti-commandeering analysis", False),
          ("Subject to political-question doctrine", False)],
         "Garcia v. San Antonio Metropolitan Transit Authority (1985) overruled National League of Cities v. Usery (1976) and held that Congress's Commerce Clause power extends to regulating state and local employment, including traditional state functions. Garcia explicitly rejected the 'traditional government function' test as unworkable. Procedural safeguards in the federal political process -- not judicially-enforced state-sovereignty doctrines -- protect state interests on commerce-clause matters.",
         [cite_scotus("Garcia v. San Antonio Metropolitan Transit Authority, 469 U.S. 528 (1985)"),
          cite_scotus("National League of Cities v. Usery, 426 U.S. 833 (1976)")],
         tags="us-conlaw,federalism,commerce-clause,state-employment", grammar_point="Garcia v. SAMTA"),
    # --- Federal Courts / Justiciability (6) -------------------
    card("usconlaw-259",
         "Plaintiffs challenge a state legislative-districting map as a partisan gerrymander, alleging excessive entrenchment of the dominant party. Per Supreme Court doctrine, the federal court should:",
         [("Apply strict scrutiny", False),
          ("Dismiss as a non-justiciable political question -- federal courts lack judicially manageable standards for partisan-gerrymander claims", True),
          ("Apply Pullman abstention", False),
          ("Apply Pike balancing", False)],
         "Rucho v. Common Cause (2019) held PARTISAN GERRYMANDERING claims to be NON-JUSTICIABLE political questions: federal courts lack judicially manageable standards. Distinguish RACIAL gerrymandering (justiciable, strict scrutiny -- Shaw v. Reno, Cooper v. Harris) and ONE-PERSON-ONE-VOTE malapportionment (justiciable -- Baker v. Carr, Reynolds v. Sims). State courts may still address partisan gerrymandering under state constitutions.",
         [cite_scotus("Rucho v. Common Cause, 588 U.S. 684 (2019)"),
          cite_scotus("Baker v. Carr, 369 U.S. 186 (1962)")],
         tags="us-conlaw,fed-courts,political-question,gerrymander", grammar_point="Rucho v. Common Cause"),
    card("usconlaw-260",
         "An association sues on behalf of its members. Per Supreme Court doctrine, the association has standing only if:",
         [("It can show direct organizational injury", False),
          ("(1) Its members would have standing in their own right, (2) the interests it seeks to protect are germane to its purpose, AND (3) neither the claim nor relief requires individual member participation", True),
          ("It is incorporated in the state where suit is filed", False),
          ("It is a 501(c)(3)", False)],
         "Hunt v. Washington State Apple Advertising Comm'n (1977) supplied the canonical THREE-PART TEST for organizational/associational standing. The third prong (no individual participation) typically excludes damages claims (which require individualized proof) but permits injunctive relief. Summers v. Earth Island Institute (2009) tightened the first prong: the organization must identify specific members who would have individual standing.",
         [cite_scotus("Hunt v. Washington State Apple Advertising Comm'n, 432 U.S. 333 (1977)"),
          cite_scotus("Summers v. Earth Island Institute, 555 U.S. 488 (2009)")],
         tags="us-conlaw,fed-courts,standing,associational", grammar_point="Hunt three-part test"),
    card("usconlaw-261",
         "After plaintiffs sue to enjoin a defendant's conduct, the defendant ceases the conduct voluntarily. The defendant moves to dismiss for mootness. Per Supreme Court doctrine, the case is:",
         [("Always moot upon voluntary cessation", False),
          ("Not moot unless the defendant carries the heavy burden of showing the conduct cannot reasonably be expected to recur", True),
          ("Subject to political-question doctrine", False),
          ("Moot only with the plaintiff's consent", False)],
         "Friends of the Earth v. Laidlaw Environmental Services (2000) reaffirmed the VOLUNTARY-CESSATION doctrine: a defendant's voluntary cessation of challenged conduct does not render a case moot unless the defendant carries the HEAVY BURDEN of showing it is ABSOLUTELY CLEAR the alleged wrongful behavior could not reasonably be expected to recur. Without this rule, defendants could manipulate jurisdiction by ceasing and resuming conduct strategically.",
         [cite_scotus("Friends of the Earth Inc. v. Laidlaw Environmental Services, 528 U.S. 167 (2000)"),
          cite_scotus("City of Mesquite v. Aladdin's Castle Inc., 455 U.S. 283 (1982)")],
         tags="us-conlaw,fed-courts,mootness,voluntary-cessation", grammar_point="Laidlaw voluntary cessation"),
    card("usconlaw-262",
         "Federal regulations are challenged in a pre-enforcement action. Per Supreme Court doctrine, the suit is ripe only if:",
         [("Enforcement has begun", False),
          ("Issues are fit for judicial decision AND withholding court consideration would impose hardship on the parties", True),
          ("The regulation is final agency action", False),
          ("The plaintiff has exhausted administrative remedies", False)],
         "Abbott Laboratories v. Gardner (1967) supplied the two-part RIPENESS test for pre-enforcement challenges: (1) FITNESS of the issues for judicial decision (purely legal, final agency action), and (2) HARDSHIP to the parties from withholding consideration. Toilet Goods Ass'n v. Gardner (companion) held a regulation unripe where compliance was minimal and challenge was available at enforcement.",
         [cite_scotus("Abbott Laboratories v. Gardner, 387 U.S. 136 (1967)"),
          cite_scotus("Toilet Goods Ass'n v. Gardner, 387 U.S. 158 (1967)")],
         tags="us-conlaw,fed-courts,ripeness", grammar_point="Abbott Labs ripeness"),
    card("usconlaw-263",
         "A statute creates a statutory right and authorizes private suits for any violation. The plaintiff alleges only a bare statutory violation without any concrete harm. Per Supreme Court doctrine, the plaintiff:",
         [("Has standing because the statute creates a cognizable interest", False),
          ("Lacks Article III standing -- bare statutory violation without concrete harm fails the injury-in-fact requirement", True),
          ("Has prudential standing only", False),
          ("Has standing if the statute is constitutional", False)],
         "TransUnion LLC v. Ramirez (2021) reinforced Spokeo Inc. v. Robins (2016): Article III standing requires CONCRETE injury-in-fact, even when a statute creates the right. Mere statutory violations are insufficient unless the plaintiff suffered some actual concrete harm (tangible OR intangible-but-traditionally-cognizable like reputational harm). Class members in TransUnion who never had their inaccurate credit reports disseminated to third parties LACKED standing despite the FCRA violation.",
         [cite_scotus("TransUnion LLC v. Ramirez, 594 U.S. 413 (2021)"),
          cite_scotus("Spokeo Inc. v. Robins, 578 U.S. 330 (2016)")],
         tags="us-conlaw,fed-courts,standing,concreteness", grammar_point="TransUnion v. Ramirez"),
    card("usconlaw-264",
         "Congress purports to confer Article III jurisdiction on bankruptcy judges (non-Article III judges) to enter final judgments on state-law counterclaims. Per Supreme Court doctrine, this:",
         [("Is constitutional under the Bankruptcy Clause", False),
          ("Violates Article III -- only Article III judges may exercise the judicial power of the United States on traditional common-law claims absent litigant consent", True),
          ("Is constitutional under the Necessary and Proper Clause", False),
          ("Subject to political-question doctrine", False)],
         "Stern v. Marshall (2011) held that Article III prohibits Congress from vesting bankruptcy judges (non-Article III) with final adjudicatory authority over state-law counterclaims that don't arise from the bankruptcy itself. Wellness International Network v. Sharif (2015) clarified that knowing and voluntary LITIGANT CONSENT permits non-Article III adjudication. The 'public rights' / 'private rights' distinction (Northern Pipeline) governs which matters non-Article III tribunals may decide without consent.",
         [cite_scotus("Stern v. Marshall, 564 U.S. 462 (2011)"),
          cite_scotus("Wellness International Network Ltd. v. Sharif, 575 U.S. 665 (2015)"),
          cite_scotus("Northern Pipeline Construction Co. v. Marathon Pipe Line Co., 458 U.S. 50 (1982)")],
         tags="us-conlaw,fed-courts,article-III", grammar_point="Stern v. Marshall"),
    # --- State Sovereignty (4) ---------------------------------
    card("usconlaw-265",
         "A state argues that Congress, when acting under Article I powers, may NOT abrogate state sovereign immunity. Per Supreme Court doctrine, the state is:",
         [("Incorrect -- Congress may abrogate via the Commerce Clause", False),
          ("Correct -- Congress may abrogate state sovereign immunity ONLY via 14A sec 5 enforcement power, NOT under Article I", True),
          ("Subject to strict scrutiny", False),
          ("Correct only as to monetary relief", False)],
         "Seminole Tribe v. Florida (1996) overruled Pennsylvania v. Union Gas (1989) and held that Congress may NOT use Article I powers (Commerce Clause, Indian Commerce Clause, Bankruptcy Clause) to abrogate state sovereign immunity. The 11A predates Article I as a constitutional principle. Only the 14A's enforcement power (sec 5) -- adopted AFTER 11A -- permits abrogation, and then only with congruence and proportionality (Boerne) and clear statement (Atascadero).",
         [cite_scotus("Seminole Tribe v. Florida, 517 U.S. 44 (1996)"),
          cite_scotus("Atascadero State Hosp. v. Scanlon, 473 U.S. 234 (1985)")],
         tags="us-conlaw,state-sovereignty,abrogation", grammar_point="Seminole Tribe v. Florida"),
    card("usconlaw-266",
         "Congress, exercising its bankruptcy power, abrogates state sovereign immunity in bankruptcy proceedings. Per Supreme Court doctrine, the abrogation is:",
         [("Invalid under Seminole Tribe", False),
          ("Valid -- the Bankruptcy Clause uniquely authorizes abrogation given the historical understanding of bankruptcy uniformity", True),
          ("Valid only with state consent", False),
          ("Subject to political-question doctrine", False)],
         "Central Virginia Community College v. Katz (2006) created a NARROW EXCEPTION to Seminole Tribe for the Bankruptcy Clause. The Court held that states surrendered sovereign immunity in bankruptcy proceedings as part of the original constitutional 'plan of the convention' -- the Framers understood that bankruptcy required uniform federal authority across state borders, including against state-creditor claims.",
         [cite_scotus("Central Virginia Community College v. Katz, 546 U.S. 356 (2006)"),
          cite_scotus("Seminole Tribe v. Florida, 517 U.S. 44 (1996)")],
         tags="us-conlaw,state-sovereignty,bankruptcy", grammar_point="Central Virginia v. Katz"),
    card("usconlaw-267",
         "An Indian tribe sues a state for damages under a federal statute regulating gaming. The statute purports to abrogate state sovereign immunity. Per Supreme Court doctrine, the suit is:",
         [("Permitted under federal supremacy", False),
          ("Barred -- Congress's Indian Commerce Clause power does NOT permit abrogation of state sovereign immunity", True),
          ("Subject to political-question doctrine", False),
          ("Permitted only with state consent", False)],
         "Seminole Tribe v. Florida (1996) involved exactly this situation: the Indian Gaming Regulatory Act's abrogation of state sovereign immunity for tribal suits. Held: Congress's Indian Commerce Clause power, like other Article I powers, cannot abrogate state sovereign immunity. The Court articulated the broader principle that ONLY 14A sec 5 supports abrogation, since 14A post-dated 11A and modified the constitutional balance.",
         [cite_scotus("Seminole Tribe v. Florida, 517 U.S. 44 (1996)")],
         tags="us-conlaw,state-sovereignty,indian-commerce", grammar_point="Seminole Tribe (IGRA)"),
    card("usconlaw-268",
         "A state employee sues the state in state court alleging an actual 14A constitutional violation. Per Supreme Court doctrine, the suit:",
         [("Is barred by sovereign immunity", False),
          ("May proceed -- where state conduct itself violates the 14A, abrogation is congruent by definition (United States v. Georgia step-2)", True),
          ("May proceed only with state consent", False),
          ("Is subject to political-question doctrine", False)],
         "United States v. Georgia (2006) clarified that Title II of the ADA validly abrogates state sovereign immunity AT LEAST for conduct that ITSELF violates the 14A (e.g., disability-based discrimination meeting the equal-protection test). Where the abrogated conduct is itself unconstitutional, congruence-and-proportionality analysis is satisfied a fortiori. The Court left for case-by-case determination Title II's validity for non-constitutional state conduct.",
         [cite_scotus("United States v. Georgia, 546 U.S. 151 (2006)"),
          cite_scotus("Tennessee v. Lane, 541 U.S. 509 (2004)")],
         tags="us-conlaw,state-sovereignty,abrogation,ada", grammar_point="United States v. Georgia"),
    # --- Sep of Powers (8) -------------------------------------
    card("usconlaw-269",
         "Congress vests rulemaking authority in an executive agency, prescribing only that the agency act 'in the public interest, convenience, or necessity.' Per Supreme Court doctrine, the delegation is:",
         [("Unconstitutional as a non-delegation violation", False),
          ("Constitutional -- the standard supplies an 'intelligible principle,' the long-standing modern test", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "J.W. Hampton Jr. & Co. v. United States (1928) and Mistretta v. United States (1989) articulate the modern non-delegation test: Congress satisfies Article I if it supplies an INTELLIGIBLE PRINCIPLE to guide the delegate's discretion. The standard is famously permissive -- the Court has not invalidated a delegation since Schechter Poultry (1935). Gundy v. United States (2019) signaled some Justices' interest in tightening the test, and Justice Gorsuch's dissent has been cited in subsequent major-questions cases.",
         [cite_scotus("J.W. Hampton Jr. & Co. v. United States, 276 U.S. 394 (1928)"),
          cite_scotus("Mistretta v. United States, 488 U.S. 361 (1989)"),
          cite_scotus("Gundy v. United States, 588 U.S. 128 (2019)")],
         tags="us-conlaw,sep-of-powers,non-delegation", grammar_point="Intelligible principle"),
    card("usconlaw-270",
         "The Clean Air Act directs EPA to set air-quality standards 'requisite to protect the public health' with 'an adequate margin of safety.' Per Supreme Court doctrine, the standard:",
         [("Is too vague and violates non-delegation", False),
          ("Supplies an intelligible principle and is constitutional", True),
          ("Requires consideration of regulatory costs", False),
          ("Subject to political-question doctrine", False)],
         "Whitman v. American Trucking Associations (2001) held that the Clean Air Act's 'requisite to protect the public health' standard supplied an intelligible principle, satisfying non-delegation. The Court also held the standard PROHIBITED EPA from considering regulatory costs in setting NAAQS -- statutory text and structure, not policy preference, controlled. Major-questions doctrine has since complicated EPA rulemaking in West Virginia v. EPA (2022).",
         [cite_scotus("Whitman v. American Trucking Associations, 531 U.S. 457 (2001)")],
         tags="us-conlaw,sep-of-powers,non-delegation,environment", grammar_point="Whitman v. American Trucking"),
    card("usconlaw-271",
         "The President asserts the power to recognize foreign governments and their territorial claims unilaterally, in defiance of a congressional statute requiring his recognition reflect specific congressional decisions about Jerusalem. Per Supreme Court doctrine:",
         [("The statute prevails under Congress's foreign-affairs power", False),
          ("The President's recognition power is exclusive; Congress cannot mandate contrary recognition", True),
          ("The matter is a non-justiciable political question", False),
          ("Both branches must agree", False)],
         "Zivotofsky v. Kerry (2015) (Zivotofsky II) held that the President possesses the EXCLUSIVE power to RECOGNIZE foreign sovereigns and their territorial boundaries (rooted in the Reception Clause, Art. II sec 3). Congress's statute requiring 'Israel' as the place-of-birth on passports for Jerusalem-born citizens unconstitutionally infringed that exclusive power. (Zivotofsky I, 2012, had held the dispute justiciable -- not a political question.)",
         [cite_scotus("Zivotofsky v. Kerry, 576 U.S. 1 (2015)"),
          cite_scotus("Zivotofsky v. Clinton, 566 U.S. 189 (2012)")],
         tags="us-conlaw,sep-of-powers,foreign-affairs", grammar_point="Zivotofsky v. Kerry"),
    card("usconlaw-272",
         "The President directs the Department of Commerce to add a citizenship question to the 2020 census. The administrative record reveals the stated reason was contrived. Per Supreme Court doctrine, the action:",
         [("Is unreviewable as committed to executive discretion", False),
          ("Is invalid -- the APA prohibits agency action based on a pretextual rationale; reasoned decisionmaking is required", True),
          ("Subject to political-question doctrine", False),
          ("Subject to rational basis review only", False)],
         "Department of Commerce v. New York (2019) blocked the citizenship-question addition. While the agency had statutory authority, the Court held that a contrived/pretextual reason violated the APA's reasoned-decisionmaking requirement. Reviewable agency action must rest on the actual reasons, not a constructed cover. Significant for executive accountability and the limits of judicial deference under Chevron (since further constrained by Loper Bright).",
         [cite_scotus("Department of Commerce v. New York, 588 U.S. 752 (2019)")],
         tags="us-conlaw,sep-of-powers,admin-law", grammar_point="Dept. of Commerce v. New York"),
    card("usconlaw-273",
         "The President invokes statutory authority to suspend entry of nationals of certain countries identified as security risks. Plaintiffs allege the proclamation was motivated by religious animus toward Muslims. Per Supreme Court doctrine, the proclamation is:",
         [("Per se unconstitutional under the Establishment Clause", False),
          ("Constitutional under rational basis review -- the Court applies a deferential standard to immigration entry restrictions", True),
          ("Subject to strict scrutiny", False),
          ("Subject to intermediate scrutiny", False)],
         "Trump v. Hawaii (2018) upheld the third iteration of the travel ban (Proclamation No. 9645). The Court applied a HIGHLY DEFERENTIAL rational-basis-style review to the executive's immigration-entry restrictions, holding they were facially neutral and supported by national-security justifications in the Worldwide Review process. The Court noted but did not endorse the President's pre-election statements; under Mandel v. Kleindienst (1972) the inquiry into facially-legitimate-and-bona-fide reasons remained deferential.",
         [cite_scotus("Trump v. Hawaii, 585 U.S. 667 (2018)"),
          cite_scotus("Kleindienst v. Mandel, 408 U.S. 753 (1972)")],
         tags="us-conlaw,sep-of-powers,immigration", grammar_point="Trump v. Hawaii"),
    card("usconlaw-274",
         "The Public Company Accounting Oversight Board's members are appointed by SEC commissioners who themselves enjoy for-cause removal protection. Per Supreme Court doctrine, the structure is:",
         [("Constitutional", False),
          ("Unconstitutional -- two layers of for-cause removal protection unduly insulate principal officers from presidential control", True),
          ("Subject to political-question doctrine", False),
          ("Subject to rational basis review", False)],
         "Free Enterprise Fund v. PCAOB (2010) struck down PCAOB's TWO-LAYER for-cause removal scheme: PCAOB members removable only for-cause by SEC commissioners, who themselves are removable only for-cause by the President. The Court held this 'double for-cause' insulation strips the President of his constitutional duty to ensure faithful execution of the laws. The Court severed the offending provision, leaving PCAOB intact but with at-will SEC removal of members.",
         [cite_scotus("Free Enterprise Fund v. PCAOB, 561 U.S. 477 (2010)")],
         tags="us-conlaw,sep-of-powers,removal", grammar_point="Free Enterprise Fund v. PCAOB"),
    card("usconlaw-275",
         "The President directs the heads of executive departments to provide written opinions on subjects relating to their duties. Per Supreme Court doctrine, the President's authority derives from:",
         [("The Commerce Clause", False),
          ("Article II sec 2 cl. 1 (the Opinion Clause) and the Take Care Clause", True),
          ("The Necessary and Proper Clause", False),
          ("The Spending Clause", False)],
         "Article II sec 2 cl. 1 (the OPINION CLAUSE) authorizes the President to require written opinions of executive department heads. Combined with the TAKE CARE CLAUSE (Art. II sec 3), this anchors the unitary-executive theory: the President is constitutionally responsible for the execution of federal law, and EXECUTIVE PRIVILEGE (United States v. Nixon, 1974) protects deliberative communications -- though the privilege yields to demonstrated need in criminal proceedings.",
         [cite_scotus("United States v. Nixon, 418 U.S. 683 (1974)")],
         tags="us-conlaw,sep-of-powers,executive-privilege", grammar_point="Opinion Clause / Take Care"),
    card("usconlaw-276",
         "Congress establishes the Sentencing Commission as an independent body within the judicial branch, composed of judges and non-judges, to promulgate binding sentencing guidelines. Per Supreme Court doctrine, the structure is:",
         [("Unconstitutional as judicial usurpation of legislative function", False),
          ("Constitutional -- the assignment of rulemaking to an entity within the judicial branch does not violate separation of powers if the commission is functionally distinct from courts", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "Mistretta v. United States (1989) upheld the Sentencing Commission. The Court held the Commission's location within the judicial branch did NOT violate separation of powers: judges' service was constitutionally compatible with Article III, and the Commission's rulemaking was distinct from adjudication. United States v. Booker (2005) later held the mandatory aspect of the Guidelines violated the Sixth Amendment, rendering them advisory.",
         [cite_scotus("Mistretta v. United States, 488 U.S. 361 (1989)"),
          cite_scotus("United States v. Booker, 543 U.S. 220 (2005)")],
         tags="us-conlaw,sep-of-powers,sentencing", grammar_point="Mistretta v. United States"),
    # --- 1A (7) ------------------------------------------------
    card("usconlaw-277",
         "A municipal sign code distinguishes among signs based on subject matter (e.g., political vs. ideological vs. directional), with different size and duration limits. Per Supreme Court doctrine, the code is:",
         [("Constitutional under intermediate scrutiny -- it regulates time/place/manner", False),
          ("Subject to strict scrutiny -- subject-matter distinctions are content-based on their face", True),
          ("Constitutional under the secondary-effects doctrine", False),
          ("Subject to rational basis review", False)],
         "Reed v. Town of Gilbert (2015) sharpened the content-based test: a regulation that distinguishes speech based on its SUBJECT MATTER, FUNCTION, or PURPOSE is content-based on its face and triggers strict scrutiny -- regardless of the government's motive. The decision overrode lower-court attempts to find subject-matter distinctions content-NEUTRAL. City of Austin v. Reagan National Advertising (2022) softened Reed: distinctions between on-premises and off-premises signs are content-NEUTRAL because they require only location, not content evaluation.",
         [cite_scotus("Reed v. Town of Gilbert, 576 U.S. 155 (2015)"),
          cite_scotus("City of Austin v. Reagan National Advertising of Austin, 596 U.S. 61 (2022)")],
         tags="us-conlaw,first-amendment,content-based", grammar_point="Reed v. Gilbert"),
    card("usconlaw-278",
         "A state public-accommodations law requires a custom website designer who opposes same-sex marriage to design wedding websites for same-sex couples. The designer's product is expressive and customized for each couple. Per Supreme Court doctrine, the application is:",
         [("Constitutional -- public-accommodations laws override speech objections", False),
          ("Unconstitutional -- compelling expressive product creation violates the First Amendment", True),
          ("Subject to rational basis review", False),
          ("Constitutional only with viewpoint-neutrality findings", False)],
         "303 Creative LLC v. Elenis (2023) held that Colorado could not compel a website designer to create custom wedding websites for same-sex couples. Custom expressive products are speech; compelling speech (Wooley v. Maynard) is presumptively unconstitutional. The decision rests on the COMPELLED-SPEECH doctrine, NOT a religious-exemption holding. Distinguish Masterpiece Cakeshop (2018, narrow holding -- religious-hostility violation by Colorado Civil Rights Commission).",
         [cite_scotus("303 Creative LLC v. Elenis, 600 U.S. 570 (2023)"),
          cite_scotus("Wooley v. Maynard, 430 U.S. 705 (1977)"),
          cite_scotus("Masterpiece Cakeshop v. Colorado Civil Rights Commission, 584 U.S. 617 (2018)")],
         tags="us-conlaw,first-amendment,compelled-speech", grammar_point="303 Creative v. Elenis"),
    card("usconlaw-279",
         "A public school football coach kneels in personal prayer at midfield after games. The school disciplines him under Establishment Clause concerns. Per Supreme Court doctrine, the discipline is:",
         [("Required by the Establishment Clause", False),
          ("Unconstitutional -- private religious expression by an employee is protected, and the Establishment Clause analysis is now historical, not Lemon-test", True),
          ("Constitutional under in loco parentis", False),
          ("Subject to rational basis review", False)],
         "Kennedy v. Bremerton School District (2022) held that the school district violated the coach's Free Exercise and Free Speech rights by disciplining him for personal prayer. Critically, the Court ABANDONED the LEMON test (and the endorsement test) and held that Establishment Clause analysis must be 'guided by reference to historical practices and understandings.' The decision substantially recasts EC doctrine going forward.",
         [cite_scotus("Kennedy v. Bremerton School District, 597 U.S. 507 (2022)"),
          cite_scotus("Lemon v. Kurtzman, 403 U.S. 602 (1971)")],
         tags="us-conlaw,first-amendment,religion", grammar_point="Kennedy v. Bremerton"),
    card("usconlaw-280",
         "A state legislature opens its sessions with prayers led by chaplains, predominantly Christian. Per Supreme Court doctrine, the practice is:",
         [("Unconstitutional under the Establishment Clause", False),
          ("Constitutional under the historical-practices framework -- legislative prayer has been continuous since the Founding", True),
          ("Subject to strict scrutiny", False),
          ("Constitutional only with rotating denominations", False)],
         "Marsh v. Chambers (1983) upheld Nebraska's legislative-prayer practice based on the unbroken tradition since the First Congress. Town of Greece v. Galloway (2014) extended Marsh to municipal-board meetings, even though prayers were predominantly Christian. The historical-practices methodology Marsh employed was a precursor to Kennedy v. Bremerton's (2022) general adoption of historical methodology for the Establishment Clause.",
         [cite_scotus("Marsh v. Chambers, 463 U.S. 783 (1983)"),
          cite_scotus("Town of Greece v. Galloway, 572 U.S. 565 (2014)")],
         tags="us-conlaw,first-amendment,establishment,legislative-prayer", grammar_point="Marsh / Town of Greece"),
    card("usconlaw-281",
         "A church terminates a minister whose duties include religious instruction and ceremonies. The minister sues for employment discrimination under federal antidiscrimination statutes. Per Supreme Court doctrine:",
         [("The suit may proceed under Title VII", False),
          ("The 1A's ministerial exception bars the suit -- religious organizations have autonomy over selection of their ministers", True),
          ("The matter is a non-justiciable political question", False),
          ("Subject to strict scrutiny", False)],
         "Hosanna-Tabor Evangelical Lutheran Church & School v. EEOC (2012) recognized the constitutional MINISTERIAL EXCEPTION rooted in the Religion Clauses: religious organizations have autonomy over selection of their ministers; antidiscrimination statutes cannot be applied to require their employment. Our Lady of Guadalupe School v. Morrissey-Berru (2020) BROADENED the exception to lay teachers whose duties include religious instruction.",
         [cite_scotus("Hosanna-Tabor Evangelical Lutheran Church & School v. EEOC, 565 U.S. 171 (2012)"),
          cite_scotus("Our Lady of Guadalupe School v. Morrissey-Berru, 591 U.S. 732 (2020)")],
         tags="us-conlaw,first-amendment,ministerial-exception", grammar_point="Hosanna-Tabor"),
    card("usconlaw-282",
         "A 40-foot World War I memorial cross sits on public land at a major intersection in suburban DC. A challenger argues the cross violates the Establishment Clause. Per Supreme Court doctrine, the cross is:",
         [("Unconstitutional under Lemon", False),
          ("Constitutional -- long-standing religiously-themed monuments enjoy a presumption of constitutionality under historical-practices analysis", True),
          ("Subject to strict scrutiny", False),
          ("Constitutional only with secular plaque", False)],
         "American Legion v. American Humanist Ass'n (2019) (Bladensburg cross) upheld the WWI memorial. The Court (plurality) held that long-established religiously-themed memorials enjoy a STRONG PRESUMPTION OF CONSTITUTIONALITY under the Establishment Clause. The decision marked another retreat from the Lemon test and a movement toward the historical-practices framework formalized in Kennedy v. Bremerton (2022).",
         [cite_scotus("American Legion v. American Humanist Ass'n, 588 U.S. 29 (2019)")],
         tags="us-conlaw,first-amendment,establishment,monuments", grammar_point="American Legion v. AHA"),
    card("usconlaw-283",
         "A state statute imposes strict liability for material that has been judged obscene. The statute does not require any scienter. Per Supreme Court doctrine, the statute is:",
         [("Constitutional under Miller v. California", False),
          ("Unconstitutional -- the 1A requires SCIENTER (knowledge of nature/character of materials) for obscenity convictions", True),
          ("Subject to rational basis review", False),
          ("Constitutional under the secondary-effects doctrine", False)],
         "Smith v. California (1959) held that strict-liability obscenity statutes are unconstitutional under the 1A: they would create a chilling effect on protected speech because booksellers would self-censor to avoid liability for unknown content. The Court required SCIENTER -- knowledge of the general nature/character of the materials. Miller v. California (1973) supplied the substantive obscenity test (community standards / lacks SLAPS value).",
         [cite_scotus("Smith v. California, 361 U.S. 147 (1959)"),
          cite_scotus("Miller v. California, 413 U.S. 15 (1973)")],
         tags="us-conlaw,first-amendment,obscenity,scienter", grammar_point="Smith v. California"),
    # --- EP/DP (6) ---------------------------------------------
    card("usconlaw-284",
         "A federal statute conditions the citizenship of children born abroad to unwed citizen parents on different physical-presence requirements depending on whether the U.S.-citizen parent is the mother or the father. Per Supreme Court doctrine, the gender-based distinction is:",
         [("Constitutional under congressional plenary immigration power", False),
          ("Subject to intermediate scrutiny -- and the gender distinction failed exceedingly persuasive justification", True),
          ("Subject to rational basis review", False),
          ("Subject to strict scrutiny", False)],
         "Sessions v. Morales-Santana (2017) struck down the differential physical-presence requirement (1 year for unwed mothers, 5 years for unwed fathers) under intermediate scrutiny. The gender distinction relied on outdated stereotypes about parenting and failed exceedingly-persuasive-justification. The Court LEVELED DOWN: it imposed the longer 5-year requirement on both parents, leaving citizenship-by-descent to Congress to fix.",
         [cite_scotus("Sessions v. Morales-Santana, 582 U.S. 47 (2017)"),
          cite_scotus("United States v. Virginia, 518 U.S. 515 (1996)")],
         tags="us-conlaw,equal-protection,sex,citizenship", grammar_point="Sessions v. Morales-Santana"),
    card("usconlaw-285",
         "A state university maintains a male-only admissions policy for a state military institute, citing the unique pedagogy of the program. Per Supreme Court doctrine, the policy is:",
         [("Constitutional under intermediate scrutiny -- the unique pedagogy supplies sufficient justification", False),
          ("Unconstitutional -- the state failed to supply an EXCEEDINGLY PERSUASIVE JUSTIFICATION for the gender-based exclusion", True),
          ("Subject to strict scrutiny", False),
          ("Subject to rational basis review", False)],
         "United States v. Virginia (VMI) (1996), per Justice Ginsburg, struck down VMI's male-only admissions policy. Sex classifications under the EP Clause require an EXCEEDINGLY PERSUASIVE JUSTIFICATION: the State must show that the classification serves IMPORTANT GOVERNMENTAL OBJECTIVES and that the discriminatory means are SUBSTANTIALLY RELATED to the achievement of those objectives. VMI's offered alternative (VWIL at Mary Baldwin) was 'separate but unequal.'",
         [cite_scotus("United States v. Virginia, 518 U.S. 515 (1996)"),
          cite_scotus("Mississippi Univ. for Women v. Hogan, 458 U.S. 718 (1982)")],
         tags="us-conlaw,equal-protection,sex", grammar_point="United States v. Virginia (VMI)"),
    card("usconlaw-286",
         "Congress enacts a statute granting Social Security benefits to widows but not widowers. Per Supreme Court doctrine, the gender classification is:",
         [("Constitutional under congressional plenary spending power", False),
          ("Unconstitutional -- gender classifications based on archaic stereotypes about dependency fail intermediate scrutiny", True),
          ("Subject to strict scrutiny", False),
          ("Subject to rational basis review", False)],
         "Weinberger v. Wiesenfeld (1975) and Califano v. Goldfarb (1977) struck down sex-based distinctions in Social Security spousal benefits. Both rested on archaic stereotypes that men are breadwinners and women are dependents. Reed v. Reed (1971) had earlier marked the modern beginning of meaningful EP review of sex classifications. The intermediate-scrutiny framework was formalized in Craig v. Boren (1976).",
         [cite_scotus("Weinberger v. Wiesenfeld, 420 U.S. 636 (1975)"),
          cite_scotus("Reed v. Reed, 404 U.S. 71 (1971)"),
          cite_scotus("Craig v. Boren, 429 U.S. 190 (1976)")],
         tags="us-conlaw,equal-protection,sex", grammar_point="Wiesenfeld / Reed / Craig"),
    card("usconlaw-287",
         "A state alimony statute requires only husbands, not wives, to pay alimony to spouses upon divorce. Per Supreme Court doctrine, the statute is:",
         [("Constitutional under traditional family law", False),
          ("Unconstitutional -- gender-based classification fails intermediate scrutiny when individualized assessment is feasible", True),
          ("Subject to strict scrutiny", False),
          ("Subject to rational basis review", False)],
         "Orr v. Orr (1979) struck down Alabama's gender-based alimony scheme. The Court applied intermediate scrutiny and held the gender-based distinction unjustified: any state interest in protecting needy spouses or compensating for past discrimination could be served by a gender-NEUTRAL statute that determined alimony based on individual circumstances rather than sex.",
         [cite_scotus("Orr v. Orr, 440 U.S. 268 (1979)")],
         tags="us-conlaw,equal-protection,sex", grammar_point="Orr v. Orr"),
    card("usconlaw-288",
         "A state statute distinguishes among voters based on property ownership for special-purpose district elections (water-storage). Per Supreme Court doctrine, the distinction:",
         [("Receives strict scrutiny under one-person-one-vote", False),
          ("Receives only rational basis review for limited-purpose, special-function districts", True),
          ("Receives intermediate scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "Salyer Land Co. v. Tulare Lake Basin Water Storage District (1973) created a NARROW EXCEPTION to one-person-one-vote (Reynolds v. Sims) for SPECIAL-PURPOSE, LIMITED-FUNCTION districts that disproportionately affect a discrete group (here, agricultural landowners). For such limited-purpose districts, weighting votes by land ownership receives only rational-basis review. The exception is genuinely narrow -- general-purpose government must observe one-person-one-vote.",
         [cite_scotus("Salyer Land Co. v. Tulare Lake Basin Water Storage District, 410 U.S. 719 (1973)"),
          cite_scotus("Reynolds v. Sims, 377 U.S. 533 (1964)")],
         tags="us-conlaw,equal-protection,voting", grammar_point="Salyer / one-person-one-vote exception"),
    card("usconlaw-289",
         "A defendant in a paternity suit invokes a state statute that imposes a one-year statute of limitations on the child's paternity actions, while permitting other claims to be brought longer. Per Supreme Court doctrine, the statute:",
         [("Is constitutional under the state's police power", False),
          ("Violates equal protection under intermediate scrutiny -- the time-bar is not substantially related to ensuring reliable proof", True),
          ("Subject to strict scrutiny", False),
          ("Subject to rational basis review", False)],
         "Mills v. Habluetzel (1982), Pickett v. Brown (1983), and Clark v. Jeter (1988) struck down successive iterations of restrictive paternity statutes of limitations as violating equal protection. Illegitimacy classifications receive intermediate scrutiny. Short SoLs imposed only for paternity actions discriminate against non-marital children and are not substantially related to ensuring reliable proof. Modern DNA evidence further undermines the proof-reliability rationale.",
         [cite_scotus("Clark v. Jeter, 486 U.S. 456 (1988)"),
          cite_scotus("Mills v. Habluetzel, 456 U.S. 91 (1982)")],
         tags="us-conlaw,equal-protection,illegitimacy", grammar_point="Mills / Pickett / Clark"),
    # --- Death penalty (3) -------------------------------------
    card("usconlaw-290",
         "A state capital-sentencing scheme permits the trial judge, not the jury, to find the aggravating factors that authorize a death sentence. Per Supreme Court doctrine, the scheme is:",
         [("Constitutional under traditional sentencing practice", False),
          ("Unconstitutional -- the Sixth Amendment requires the jury to find any aggravating factor that increases the maximum punishment", True),
          ("Subject to political-question doctrine", False),
          ("Subject to rational basis review", False)],
         "Hurst v. Florida (2016) struck down Florida's capital-sentencing scheme. Building on Ring v. Arizona (2002) and Apprendi v. New Jersey (2000), the Court held that the SIXTH AMENDMENT requires the JURY (not the judge) to find any fact that increases the maximum penalty -- in capital cases, the existence of an aggravating factor that authorizes death. McKinney v. Arizona (2020) clarified that Hurst applies retroactively only as the federal collateral-review framework dictates.",
         [cite_scotus("Hurst v. Florida, 577 U.S. 92 (2016)"),
          cite_scotus("Ring v. Arizona, 536 U.S. 584 (2002)"),
          cite_scotus("Apprendi v. New Jersey, 530 U.S. 466 (2000)")],
         tags="us-conlaw,sixth-amendment,death-penalty,jury", grammar_point="Hurst v. Florida"),
    card("usconlaw-291",
         "A death-row inmate, while awaiting execution, suffers severe vascular dementia and cannot rationally understand the connection between his crime and his execution. Per Supreme Court doctrine, the execution is:",
         [("Permissible if the condition was not present at trial", False),
          ("Barred by the 8A -- the Constitution prohibits executing a person who lacks rational understanding of the reason for his execution, regardless of the cause", True),
          ("Subject to political-question doctrine", False),
          ("Subject to rational basis review", False)],
         "Madison v. Alabama (2019) extended Ford v. Wainwright (1986) and Panetti v. Quarterman (2007). Ford barred executing the insane; Panetti held the inquiry is whether the prisoner has a RATIONAL UNDERSTANDING of the execution. Madison clarified that the underlying condition (e.g., dementia, mental illness, anything) is irrelevant -- what matters is whether the prisoner can rationally understand the reason for his punishment.",
         [cite_scotus("Madison v. Alabama, 586 U.S. 265 (2019)"),
          cite_scotus("Ford v. Wainwright, 477 U.S. 399 (1986)"),
          cite_scotus("Panetti v. Quarterman, 551 U.S. 930 (2007)")],
         tags="us-conlaw,eighth-amendment,death-penalty,competency", grammar_point="Madison / Ford / Panetti"),
    card("usconlaw-292",
         "A state abolishes the affirmative defense of insanity, allowing only mens-rea-based defenses for capital cases. Per Supreme Court doctrine, the abolition is:",
         [("Per se unconstitutional", False),
          ("Constitutional -- the Constitution does not require any specific formulation of an insanity defense", True),
          ("Subject to strict scrutiny", False),
          ("Subject to rational basis review", False)],
         "Kahler v. Kansas (2020) upheld Kansas's narrowed insanity rule (mens-rea-only, no moral-incapacity prong). The Court held that DUE PROCESS does not require any particular formulation of the insanity defense; states may choose among historical formulations (M'Naghten, Durham, Model Penal Code). The Court emphasized federalism in choice of criminal-justice rules and historical variation across the common-law tradition.",
         [cite_scotus("Kahler v. Kansas, 589 U.S. 271 (2020)")],
         tags="us-conlaw,due-process,death-penalty,insanity", grammar_point="Kahler v. Kansas"),
    # --- 4A/5A/6A (5) ------------------------------------------
    card("usconlaw-293",
         "Following a lawful arrest, police search the arrestee's smartphone without a warrant, examining its data. Per Supreme Court doctrine, the search is:",
         [("Constitutional as search incident to arrest", False),
          ("Unconstitutional -- the search-incident-to-arrest exception does not extend to digital data on cell phones; a warrant is generally required", True),
          ("Subject to good-faith exception", False),
          ("Subject to rational basis review", False)],
         "Riley v. California (2014) (and the companion United States v. Wurie) held that the search-incident-to-arrest exception does NOT apply to digital data on cell phones seized from an arrestee. The Court emphasized that cell phones contain immense quantities of personal data with no analog precedent; the Chimel rationales (officer safety, evidence preservation) do not justify warrantless review of data. Police generally need a WARRANT to search a phone's contents.",
         [cite_scotus("Riley v. California, 573 U.S. 373 (2014)"),
          cite_scotus("Chimel v. California, 395 U.S. 752 (1969)")],
         tags="us-conlaw,fourth-amendment,digital", grammar_point="Riley v. California"),
    card("usconlaw-294",
         "Police obtain a person's historical cell-site location information (CSLI) from his wireless carrier without a warrant, covering 127 days of his movements. Per Supreme Court doctrine, the acquisition is:",
         [("Constitutional under the third-party doctrine (Smith v. Maryland)", False),
          ("Unconstitutional -- the acquisition of comprehensive historical CSLI is a 4A search and generally requires a warrant", True),
          ("Subject to good-faith exception", False),
          ("Subject to rational basis review", False)],
         "Carpenter v. United States (2018) held that government acquisition of more than 7 days of historical CSLI is a Fourth Amendment SEARCH requiring a warrant supported by probable cause. The Court declined to extend the third-party doctrine (Smith v. Maryland's pen-register holding) to comprehensive location data, recognizing the deeply revealing, retrospective, and effortlessly compiled nature of CSLI. Major modern privacy precedent.",
         [cite_scotus("Carpenter v. United States, 585 U.S. 296 (2018)"),
          cite_scotus("Smith v. Maryland, 442 U.S. 735 (1979)")],
         tags="us-conlaw,fourth-amendment,digital,csli", grammar_point="Carpenter v. United States"),
    card("usconlaw-295",
         "A state criminalizes a DUI suspect's refusal to submit to a warrantless breath test (post-arrest). The state cites the search-incident-to-arrest doctrine. Per Supreme Court doctrine, the criminalization is:",
         [("Per se unconstitutional", False),
          ("Constitutional as to BREATH tests (low intrusion, search incident to arrest), unconstitutional as to BLOOD tests (significant intrusion, requires warrant)", True),
          ("Constitutional only with consent", False),
          ("Subject to strict scrutiny", False)],
         "Birchfield v. North Dakota (2016) drew a line: a state may criminalize REFUSAL of warrantless BREATH tests post-arrest (low physical intrusion, search-incident-to-arrest justifies), but NOT refusal of warrantless BLOOD tests (significant bodily intrusion, exigent circumstances or warrant required). Mitchell v. Wisconsin (2019) addressed unconscious-driver implied-consent statutes for blood tests under exigency.",
         [cite_scotus("Birchfield v. North Dakota, 579 U.S. 438 (2016)"),
          cite_scotus("Missouri v. McNeely, 569 U.S. 141 (2013)")],
         tags="us-conlaw,fourth-amendment,dui", grammar_point="Birchfield v. North Dakota"),
    card("usconlaw-296",
         "Police, upon arresting a serious-offense suspect, swab his cheek to obtain DNA for entry into a state DNA database. Per Supreme Court doctrine, the DNA collection is:",
         [("Unconstitutional without a warrant", False),
          ("Constitutional under the 4A as a reasonable search incident to arrest, given identification interest and minimal intrusion", True),
          ("Subject to strict scrutiny", False),
          ("Subject to rational basis review", False)],
         "Maryland v. King (2013) upheld warrantless DNA cheek swabs of arrestees for serious offenses. The Court applied a 4A REASONABLENESS BALANCING (not search-incident-to-arrest exclusively): the state's interest in identifying arrestees and processing them for booking outweighed the minimal intrusion of a cheek swab. The decision is contested but stands as the doctrinal framework for arrestee DNA collection.",
         [cite_scotus("Maryland v. King, 569 U.S. 435 (2013)")],
         tags="us-conlaw,fourth-amendment,dna", grammar_point="Maryland v. King"),
    card("usconlaw-297",
         "A criminal defendant pleads guilty after his attorney fails to advise him that the conviction will result in mandatory deportation. Per Supreme Court doctrine, the failure constitutes:",
         [("Acceptable strategic decision", False),
          ("Ineffective assistance of counsel under the Sixth Amendment", True),
          ("Subject to political-question doctrine", False),
          ("Subject to rational basis review", False)],
         "Padilla v. Kentucky (2010) extended Strickland v. Washington (1984) to immigration consequences: the Sixth Amendment requires defense counsel to ADVISE non-citizen clients about clear deportation consequences of guilty pleas. Failure to do so is deficient performance; petitioners must still show Strickland prejudice (reasonable probability of different outcome). Lee v. United States (2017) affirmed that prejudice can be shown even where the conviction was virtually certain.",
         [cite_scotus("Padilla v. Kentucky, 559 U.S. 356 (2010)"),
          cite_scotus("Strickland v. Washington, 466 U.S. 668 (1984)"),
          cite_scotus("Lee v. United States, 582 U.S. 357 (2017)")],
         tags="us-conlaw,sixth-amendment,counsel,padilla", grammar_point="Padilla v. Kentucky"),
    # --- 8A non-capital (3) ------------------------------------
    card("usconlaw-298",
         "A prison guard uses excessive physical force on an inmate, but the inmate suffers only minor injury. Per Supreme Court doctrine, the conduct:",
         [("Cannot violate the 8A absent significant injury", False),
          ("May violate the 8A even without significant injury -- the question is whether the force was applied in a good-faith effort to maintain discipline OR maliciously and sadistically to cause harm", True),
          ("Subject to rational basis review", False),
          ("Subject to political-question doctrine", False)],
         "Hudson v. McMillian (1992) held that the 8A inquiry for prison-guard excessive force is whether force was applied in GOOD FAITH to maintain discipline OR MALICIOUSLY AND SADISTICALLY to cause harm. The extent of injury is one factor but is NOT a threshold requirement -- minor injury can suffice if the force was malicious. Wilkins v. Gaddy (2010) reaffirmed Hudson against lower-court attempts to impose injury thresholds.",
         [cite_scotus("Hudson v. McMillian, 503 U.S. 1 (1992)"),
          cite_scotus("Wilkins v. Gaddy, 559 U.S. 34 (2010)")],
         tags="us-conlaw,eighth-amendment,prison,force", grammar_point="Hudson v. McMillian"),
    card("usconlaw-299",
         "A criminal defendant is sentenced under a statute that mandates life-without-parole for any third felony, including non-violent ones. The defendant's third felony was passing a $100 bad check. Per Supreme Court doctrine, the sentence is:",
         [("Per se unconstitutional", False),
          ("Subject to a narrow gross-disproportionality 8A inquiry, with substantial deference to legislative judgments", True),
          ("Subject to strict scrutiny", False),
          ("Subject to political-question doctrine", False)],
         "Solem v. Helm (1983) struck down LWOP for a non-violent third felony as grossly disproportionate. Harmelin v. Michigan (1991, plurality) and Ewing v. California (2003) significantly NARROWED proportionality review for non-capital sentences. The current standard: the 8A contains a narrow proportionality principle, but federal courts give substantial DEFERENCE to legislative judgments about appropriate punishment. Most adult-sentence challenges fail.",
         [cite_scotus("Solem v. Helm, 463 U.S. 277 (1983)"),
          cite_scotus("Ewing v. California, 538 U.S. 11 (2003)"),
          cite_scotus("Harmelin v. Michigan, 501 U.S. 957 (1991)")],
         tags="us-conlaw,eighth-amendment,proportionality", grammar_point="Solem / Ewing proportionality"),
    card("usconlaw-300",
         "A state imposes civil-asset forfeiture of a $42,000 vehicle following a defendant's conviction for selling $385 in heroin. The maximum statutory fine for the offense is $10,000. Per Supreme Court doctrine, the forfeiture:",
         [("Is constitutional as a civil-in-rem proceeding", False),
          ("Is subject to 8A excessive-fines analysis (incorporated against the states by Timbs) and may be unconstitutional if grossly disproportionate to the gravity of the offense", True),
          ("Subject to rational basis review", False),
          ("Subject to political-question doctrine", False)],
         "Timbs v. Indiana (2019) -- on facts similar to this hypo -- INCORPORATED the 8A's Excessive Fines Clause against the states via 14A Due Process. Civil-in-rem forfeitures that are at least partly punitive (and Bennis-style guilty-property fictions notwithstanding) face 8A excessive-fines analysis under the Bajakajian gross-disproportionality standard. On remand, Indiana courts ultimately ruled the forfeiture excessive.",
         [cite_scotus("Timbs v. Indiana, 586 U.S. 146 (2019)"),
          cite_scotus("United States v. Bajakajian, 524 U.S. 321 (1998)")],
         tags="us-conlaw,eighth-amendment,excessive-fines,forfeiture", grammar_point="Timbs (incorporation)"),
]


def main():
    data = json.loads(CARDS_PATH.read_text(encoding="utf-8"))
    cards = data["cards"]
    existing_ids = {c["id"] for c in cards}
    added = 0
    for card_dict in NEW_CARDS:
        if card_dict["id"] not in existing_ids:
            cards.append(card_dict)
            added += 1
    tmp = CARDS_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps({"cards": cards}, ensure_ascii=False, indent=2) + "\n",
                   encoding="utf-8")
    tmp.replace(CARDS_PATH)
    print(f"Added {added} new cards. Total cards now: {len(cards)}.")


if __name__ == "__main__":
    main()
